import type { Question } from "@/lib/types";

function q(
  prompt: string,
  choices: string[],
  answerIndex: number,
  explanation: string,
): Question {
  return { prompt, choices, answerIndex, explanation };
}

/** Original 54-item Scripture sitting. Public-domain biblical facts, not a sermon and not copied from another quiz site. */
export const OPEN_THE_BOOK_QUESTIONS: Question[] = [
  q("The first book of the Christian Old Testament is:", ["Exodus", "Genesis", "Psalms", "Matthew"], 1, "Genesis opens with creation and the patriarchs."),
  q("The last book of the New Testament is:", ["Acts", "Hebrews", "Revelation", "Malachi"], 2, "Revelation addresses churches in Asia Minor and closes the canon in Christian Bibles."),
  q("In Exodus, who leads Israel out of Egypt?", ["Aaron only, with no brother", "Moses", "Joshua as a child", "Samuel"], 1, "Moses, with Aaron, confronts Pharaoh."),
  q("Abraham and Sarah's promised son in Genesis is:", ["Ishmael as the child of promise in that chapter", "Isaac", "Esau", "Judah"], 1, "Isaac is the child of the promise; Ishmael is also Abraham's son."),
  q("Joseph, son of Jacob, is sold and later rises to power in:", ["Rome", "Egypt", "Nineveh", "Athens"], 1, "The Joseph cycle is set in Egypt."),
  q("The Ten Commandments are given at:", ["Mount Carmel", "Mount Sinai (Horeb)", "The Mount of Olives", "Mount Hermon only"], 1, "Exodus and Deuteronomy locate the law at Sinai/Horeb."),
  q("Ruth's mother-in-law is:", ["Hannah", "Naomi", "Deborah", "Rachel"], 1, "The book of Ruth follows Naomi and Ruth to Bethlehem."),
  q("Before he is king in Jerusalem, David is introduced as a:", ["Phoenician sailor", "Shepherd", "Roman centurion", "Babylonian magus"], 1, "1 Samuel describes the shepherd of Bethlehem."),
  q("Solomon is remembered in the narrative for:", ["Building the first temple in Jerusalem and for wisdom", "Writing Romans", "Baptizing Jesus", "Rebuilding the wall with Nehemiah as a teenager"], 0, "1 Kings: wisdom and the temple."),
  q("Elijah's contest with the prophets of Baal is set on:", ["Mount Carmel", "Mount Zion only", "Patmos", "Ararat"], 0, "1 Kings 18."),
  q("Jonah is sent to preach in:", ["Tarshish as his assignment", "Nineveh", "Rome", "Corinth"], 1, "He flees toward Tarshish; the commission is Nineveh."),
  q("Daniel serves in the court of:", ["Pharaoh in the Joseph story", "Babylon (and later Persia in the book)", "King Saul", "Herod Antipas"], 1, "The book is set in the exile."),
  q("Esther becomes queen in:", ["Judah under Josiah", "The Persian court", "Egypt under Joseph", "Rome under Nero"], 1, "The story is set in the Persian empire."),
  q("Isaiah's throne-room vision ('holy, holy, holy') is set in the:", ["Temple", "Fish's belly", "Prison in Rome", "Garden of Gethsemane"], 0, "Isaiah 6."),
  q("Psalm 23 opens with:", ["Blessed are the poor in spirit", "The Lord is my shepherd", "In the beginning was the Word", "Hear, O Israel"], 1, "A psalm of trust."),
  q("Proverbs is traditionally associated with:", ["Solomon's wisdom collection", "Paul's prison letters", "Luke's travel diary", "John's vision on Patmos"], 0, "The superscriptions name Solomon and other sages."),
  q("In Matthew and Luke, Bethlehem is the setting of:", ["Paul's conversion", "The birth of Jesus", "The giving of the law", "The fall of Jericho"], 1, "The infancy narratives."),
  q("The Gospels locate Jesus' baptism in the:", ["Nile", "Jordan River", "Tigris", "Sea of Galilee as a river baptism"], 1, "John the Baptist baptizes in the Jordan."),
  q("The Beatitudes open the Sermon on the:", ["Plain in every Gospel identically", "Mount (in Matthew)", "Areopagus", "Temple steps as a Roman speech"], 1, "Matthew 5–7. Luke has related teaching on a plain."),
  q("The parable of the prodigal son is in:", ["Mark only", "Luke", "Revelation", "Obadiah"], 1, "Luke 15."),
  q("Jesus raises Lazarus in:", ["Bethany", "Nineveh", "Corinth", "Babylon"], 0, "John 11."),
  q("The Last Supper is framed as a:", ["Roman banquet with Caesar", "Passover meal", "Wedding at Cana repeating", "Funeral in Nain"], 1, "The Synoptics set it at Passover."),
  q("Who denies Jesus three times before a rooster crows?", ["Thomas", "Peter", "Andrew", "Philip"], 1, "All four Gospels record Peter's denial."),
  q("Who betrays Jesus with a kiss in the Synoptic tradition?", ["Judas Iscariot", "Nicodemus", "Joseph of Arimathea", "Barnabas"], 0, "Gethsemane arrest scenes."),
  q("On the first Easter morning in the Gospels, the tomb is:", ["Sealed with Lazarus still inside", "Found empty", "Moved to Rome", "A metaphor with no location"], 1, "The women find it empty."),
  q("Pentecost in Acts is set in:", ["Jerusalem", "Athens", "Alexandria", "Carthage"], 0, "The Spirit and the gathered crowd in Jerusalem."),
  q("Saul of Tarsus is better known after his calling as:", ["Peter", "Paul", "Stephen", "Timothy"], 1, "Acts uses both names; the mission to the nations is under Paul."),
  q("Saul meets the risen Jesus on the road to:", ["Emmaus as Saul", "Damascus", "Jericho in the parable", "Joppa with Peter"], 1, "Acts 9."),
  q("Barnabas is known as a:", ["Companion of Paul and an encourager", "Roman governor of Syria", "Author of Revelation", "Pharaoh"], 0, "Acts pairs Barnabas with Paul."),
  q("Lydia, a dealer in purple cloth, is baptized in:", ["Philippi", "Ur", "Nineveh", "Bethlehem"], 0, "Acts 16, in Macedonia."),
  q("The New Testament letter addressed to believers in Rome is:", ["Hebrews as its only title", "Romans", "Jude", "Philemon as a city letter"], 1, "Paul's letter to Rome."),
  q("The letter of James emphasizes:", ["Faith lived out in works of mercy", "Building Solomon's temple", "The census of Quirinius as its theme", "Dietary law in Leviticus only"], 0, "Faith without works is dead, in James's argument."),
  q("1 Corinthians 13 is especially known as the chapter on:", ["Spiritual gifts only as a budget", "Love", "The armor of God", "The fruit of the Spirit list in Galatians"], 1, "The 'love is patient' passage."),
  q("The fruit of the Spirit (love, joy, peace…) is listed in:", ["Galatians", "Jonah", "Leviticus as the only list", "3 John"], 0, "Galatians 5."),
  q("The armor of God (belt, breastplate, shield…) is described in:", ["Ephesians", "Ruth", "Esther", "Obadiah"], 0, "Ephesians 6."),
  q("Hebrews presents Jesus as:", ["A high priest of a better covenant", "A Roman emperor", "Jonah's captain", "The author of Proverbs only"], 0, "Priest after the order of Melchizedek, in the book's argument."),
  q("Revelation is addressed to churches in:", ["Gaul", "Asia Minor (e.g. Ephesus, Smyrna)", "Ethiopia only", "Britain"], 1, "Seven churches of Asia."),
  q("After Moses, who leads Israel across the Jordan into the land in Joshua?", ["Joshua", "Saul", "Ezra", "Titus"], 0, "Joshua 3–4."),
  q("Gideon's small force against Midian is told in:", ["Judges", "Acts", "Philemon", "2 John"], 0, "Judges 6–8."),
  q("Samuel anoints which shepherd as future king?", ["David", "Herod", "Ahab", "Cyrus as an Israelite king"], 0, "1 Samuel 16."),
  q("Jezebel is an opponent of:", ["Elijah", "Luke", "Onesimus", "Simeon in the temple"], 0, "1 Kings."),
  q("Nehemiah is remembered for rebuilding:", ["The walls of Jerusalem", "Noah's ark", "The Colosseum", "Paul's ship"], 0, "Nehemiah's memoir."),
  q("In many Protestant English Bibles, the last book of the Old Testament is:", ["Malachi", "Matthew", "Revelation", "Psalms"], 0, "Order differs in some canons; Malachi often closes the OT in Protestant printings."),
  q("The magi in Matthew come from the:", ["West as fishermen", "East", "South Pole", "Island of Patmos"], 1, "Matthew 2."),
  q("The tax collector called to follow Jesus, associated with the first Gospel, is:", ["Matthew (Levi)", "Luke the governor", "Pontius Pilate", "Cornelius as the Gospel writer"], 0, "Matthew/Levi in the Synoptics."),
  q("Which disciple is remembered for wanting to see and touch the risen Jesus?", ["Thomas", "Judas Iscariot after Easter", "Ananias of Damascus as a disciple of the Twelve", "Barabbas"], 0, "John 20."),
  q("Mary Magdalene is a witness at:", ["The empty tomb", "Sinai in Exodus", "Solomon's dedication only", "Jonah's ship"], 0, "The resurrection narratives."),
  q("The parable of the good Samaritan is in:", ["Luke", "Nahum", "Titus as a parable chapter", "Jude"], 0, "Luke 10."),
  q("'In the beginning was the Word' opens:", ["Genesis again as a Gospel", "The Gospel of John", "Acts", "James"], 1, "John 1:1."),
  q("The early community in Acts 2 gathers in:", ["Jerusalem", "Babylon", "Rome as the first scene of Acts", "Nazareth as the Pentecost city"], 0, "Pentecost and the first preaching."),
  q("Timothy is a:", ["Young coworker of Paul", "Judge who defeated Midian", "Persian king", "Author of Genesis"], 0, "Acts and the letters to Timothy."),
  q("Philemon is a short letter about:", ["Onesimus and a plea for welcome", "Building the second temple", "The census in Bethlehem", "The armor of God"], 0, "Paul writes to Philemon about Onesimus."),
  q("The shortest verse in many English Bibles is:", ["Jesus wept", "In the beginning", "Amen", "Selah as a numbered verse"], 0, "John 11:35 in common Protestant numbering."),
  q("The 'Shema' ('Hear, O Israel…') is found in:", ["Deuteronomy", "Revelation 1 as its only home", "Acts 27", "Jude"], 0, "Deuteronomy 6:4–5, central in Jewish and Christian memory."),
];
