import type { Question, QuizChapter } from "@/lib/types";

function q(
  prompt: string,
  choices: string[],
  answerIndex: number,
  explanation: string,
): Question {
  return { prompt, choices, answerIndex, explanation };
}

export const OPEN_THE_BOOK_CHAPTERS: QuizChapter[] = [
  {
    title: "Act I: Patriarchs & Exodus",
    subtitle: "Creation, the Patriarchs, the Exodus, and Sinai Law",
    startIndex: 0,
  },
  {
    title: "Act II: Kings, Prophets & Wisdom",
    subtitle: "Judges, United Monarchy, Exile, Psalms, and Wisdom",
    startIndex: 13,
  },
  {
    title: "Act III: Gospels & The Life of Jesus",
    subtitle: "Infancy, Jordan Baptism, Parables, Passion, and Resurrection",
    startIndex: 26,
  },
  {
    title: "Act IV: Acts, Epistles & Revelation",
    subtitle: "Pentecost, Paul's Journeys, Letters, and the Vision on Patmos",
    startIndex: 40,
  },
];

/** Original 54-item Scripture sitting with rich multi-paragraph storytelling commentary. */
export const OPEN_THE_BOOK_QUESTIONS: Question[] = [
  q(
    "The first book of the Christian Old Testament is:",
    ["Exodus", "Genesis", "Psalms", "Matthew"],
    1,
    "Genesis opens with the majestic creation of the cosmos out of nothingness, declaring that God spoke light into darkness and formed humanity in the divine image.\n\nThe narrative quickly transitions into the foundational sagas of early mankind—the Garden of Eden, the fall of humanity, the Noahic covenant, and the collapse of human pride at Babel.\n\nFrom chapter 12 onward, the story focuses on Abraham and his descendants, laying down the covenant promises that thread through the entire biblical storyline.",
  ),
  q(
    "The last book of the New Testament is:",
    ["Acts", "Hebrews", "Revelation", "Malachi"],
    2,
    "Written by John during his exile on the rocky Aegean island of Patmos, Revelation opens with vivid messages to seven historical churches in Asia Minor.\n\nThe vision unfolds into cosmic apocalyptic imagery depicting the struggle between God's kingdom and worldly empires, highlighting ultimate spiritual victory.\n\nIt closes the biblical canon with a glorious vision of the New Jerusalem, where God dwells directly with His people and wipes away every tear.",
  ),
  q(
    "In Exodus, who leads Israel out of Egypt?",
    ["Aaron only, with no brother", "Moses", "Joshua as a child", "Samuel"],
    1,
    "Moses was rescued from the Nile as an infant by Pharaoh's daughter and raised in royal courts, but his heart remained tied to his enslaved Hebrew brethren.\n\nAfter spending forty years as a shepherd in Midian, God called Moses from a burning bush at Mount Horeb to return and confront the ruler of Egypt.\n\nAccompanied by his brother Aaron, Moses led Israel through the ten plagues, the institution of Passover, and the miraculous parting of the Red Sea.",
  ),
  q(
    "Abraham and Sarah's promised son in Genesis is:",
    ["Ishmael as the child of promise in that chapter", "Isaac", "Esau", "Judah"],
    1,
    "God promised Abraham and Sarah a son in their old age, assuring them that their descendants would be as numerous as the stars in the night sky.\n\nWhen Isaac was born, Sarah named him 'Laughter' because of the joyful surprise of bearing a child in her nineties.\n\nIsaac became the heir of God's covenant promises, passing the blessing down to his son Jacob.",
  ),
  q(
    "Joseph, son of Jacob, is sold and later rises to power in:",
    ["Rome", "Egypt", "Nineveh", "Athens"],
    1,
    "Envied by his ten elder brothers for his coat of many colors and prophetic dreams, Joseph was sold into slavery to passing Midianite merchants.\n\nThrough trials including false accusation and imprisonment in Egypt, Joseph retained his integrity and was given divine gift of dream interpretation.\n\nPharaoh appointed Joseph prime minister of Egypt, enabling him to save the ancient Near East from a severe seven-year famine.",
  ),
  q(
    "The Ten Commandments are given at:",
    ["Mount Carmel", "Mount Sinai (Horeb)", "The Mount of Olives", "Mount Hermon only"],
    1,
    "Following the dramatic deliverance from Egypt, God led Israel through the wilderness to the base of Mount Sinai, enveloped in smoke, thunder, and trumpet blasts.\n\nMoses ascended the mountain and received the Ten Commandments engraved on two stone tablets.\n\nThese commandments established the moral foundation of Israel's covenant, detailing duties toward God and fellow human beings.",
  ),
  q(
    "Ruth's mother-in-law is:",
    ["Hannah", "Naomi", "Deborah", "Rachel"],
    1,
    "During a severe famine in Bethlehem, Naomi moved to Moab with her husband and sons, but tragic deaths left her a grieving widow alongside her Moabite daughters-in-law.\n\nWhen Naomi decided to return home, Ruth refused to abandon her, uttering the famous vow: 'Where you go I will go, and where you stay I will stay.'\n\nRuth later married Boaz in Bethlehem, becoming the great-grandmother of King David and an ancestor in the lineage of Jesus.",
  ),
  q(
    "Before he is king in Jerusalem, David is introduced as a:",
    ["Phoenician sailor", "Shepherd", "Roman centurion", "Babylonian magus"],
    1,
    "Long before wearing royal robes, David was the youngest son of Jesse, tending his father's sheep in the rocky hills surrounding Bethlehem.\n\nWhile watching the flock, David developed brave courage defending his sheep against lions and bears, along with a poetic heart for writing psalms.\n\nWhen Samuel came to anoint Israel's next king, God instructed him to look beyond physical height, declaring that God looks at the heart.",
  ),
  q(
    "Solomon is remembered in the narrative for:",
    ["Building the first temple in Jerusalem and for wisdom", "Writing Romans", "Baptizing Jesus", "Rebuilding the wall with Nehemiah as a teenager"],
    0,
    "When young Solomon succeeded David on the throne, God appeared to him in a dream and offered him whatever he desired.\n\nSolomon famously asked not for wealth or long life, but for a discerning heart to govern the nation wisely, which pleased God greatly.\n\nSolomon's reign became legendary for architectural masterpieces, most notably constructing the First Temple in Jerusalem.",
  ),
  q(
    "Elijah's contest with the prophets of Baal is set on:",
    ["Mount Carmel", "Mount Zion only", "Patmos", "Ararat"],
    0,
    "During a severe three-year drought under King Ahab and Queen Jezebel, Elijah summoned Israel and 450 prophets of Baal to Mount Carmel.\n\nElijah challenged the pagan prophets to pray for fire to consume their sacrifice, but despite dancing and shouting all day, Baal gave no answer.\n\nElijah then drenched his altar with water and prayed a simple prayer, whereupon fire fell from heaven and consumed the altar completely.",
  ),
  q(
    "Jonah is sent to preach in:",
    ["Tarshish as his assignment", "Nineveh", "Rome", "Corinth"],
    1,
    "God commissioned Jonah to go to Nineveh, the ruthless capital of the Assyrian Empire, to call its citizens to repentance.\n\nUnwilling to extend grace to Israel's enemies, Jonah boarded a ship heading in the exact opposite direction toward Tarshish.\n\nAfter a terrifying storm and three days inside a great fish, Jonah obeyed God and witnessed one of the largest national revivals in ancient history.",
  ),
  q(
    "Daniel serves in the court of:",
    ["Pharaoh in the Joseph story", "Babylon (and later Persia in the book)", "King Saul", "Herod Antipas"],
    1,
    "Carried away as a young noble during the Babylonian exile, Daniel was chosen to serve in King Nebuchadnezzar's imperial court.\n\nDaniel and his three friends refused to compromise their dietary faith, remaining loyal to God amidst a pagan empire.\n\nDaniel rose to become a trusted advisor through empires, surviving the famous lions' den after refusing to stop daily prayer.",
  ),
  q(
    "Esther becomes queen in:",
    ["Judah under Josiah", "The Persian court", "Egypt under Joseph", "Rome under Nero"],
    1,
    "Esther was an orphaned Jewish girl raised by her cousin Mordecai in the Persian capital of Susa.\n\nWhen King Ahasuerus sought a new queen, Esther was chosen for her beauty and grace, though her Jewish heritage remained secret.\n\nWhen a wicked decree threatened her people with extinction, Esther risked her life by approaching the king, famously acting 'for such a time as this.'",
  ),
  q(
    "Isaiah's throne-room vision ('holy, holy, holy') is set in the:",
    ["Temple", "Fish's belly", "Prison in Rome", "Garden of Gethsemane"],
    0,
    "In the year King Uzziah died, the prophet Isaiah saw a breathtaking vision of the Lord seated on a throne, high and exalted.\n\nThe hem of God's robe filled the Temple, and seraphim flew above crying: 'Holy, holy, holy is the LORD Almighty; the whole earth is full of his glory!'\n\nOverwhelmed by his own unworthiness, Isaiah was cleansed by a burning coal from the altar and answered God's call saying: 'Here am I. Send me!'",
  ),
  q(
    "Psalm 23 opens with:",
    ["Blessed are the poor in spirit", "The Lord is my shepherd", "In the beginning was the Word", "Hear, O Israel"],
    1,
    "Authored by David, Psalm 23 is perhaps the most beloved poem in world literature, drawing on David's personal experience as a shepherd.\n\nIt portrays God as a caring Shepherd who guides His sheep to green pastures, quiet waters, and paths of righteousness.\n\nEven when walking through the valley of the shadow of death, the singer fears no evil, confident in divine comfort and eternal hospitality.",
  ),
  q(
    "Proverbs is traditionally associated with:",
    ["Solomon's wisdom collection", "Paul's prison letters", "Luke's travel diary", "John's vision on Patmos"],
    0,
    "The Book of Proverbs gathers practical life wisdom, moral maxims, and spiritual guidance for everyday living.\n\nSolomon is cited as the primary author and collector of these sayings, alongside other sages like Agur and Lemuel.\n\nThe central theme of Proverbs is stated early: 'The fear of the LORD is the beginning of knowledge.'",
  ),
  q(
    "In Matthew and Luke, Bethlehem is the setting of:",
    ["Paul's conversion", "The birth of Jesus", "The giving of the law", "The fall of Jericho"],
    1,
    "Bethlehem, a quiet hill town five miles south of Jerusalem, was the ancestral home of King David.\n\nTo fulfill prophecy and comply with a Roman census decree from Caesar Augustus, Joseph and Mary traveled from Nazareth to Bethlehem.\n\nThere, in humble surroundings, Jesus was born and laid in a manger, as angels announced the good news to shepherds in nearby fields.",
  ),
  q(
    "The Gospels locate Jesus' baptism in the:",
    ["Nile", "Jordan River", "Tigris", "Sea of Galilee as a river baptism"],
    1,
    "John the Baptist ministered in the Judean wilderness, calling people to repentance and baptizing them in the Jordan River.\n\nWhen Jesus came to be baptized, John hesitated, declaring that he needed to be baptized by Jesus instead.\n\nAs Jesus emerged from the water, the heavens opened, the Holy Spirit descended like a dove, and the Father's voice affirmed: 'This is my beloved Son.'",
  ),
  q(
    "The Beatitudes open the Sermon on the:",
    ["Plain in every Gospel identically", "Mount (in Matthew)", "Areopagus", "Temple steps as a Roman speech"],
    1,
    "Sitting on a grassy hillside overlooking the Sea of Galilee, Jesus delivered His foundational ethical teaching recorded in Matthew 5–7.\n\nThe Sermon opens with eight Beatitudes, reframing kingdom blessings for the poor in spirit, the meek, the merciful, and peacemakers.\n\nJesus called His followers to be the 'salt of the earth' and 'light of the world', elevating heart righteousness above mere legalism.",
  ),
  q(
    "The parable of the prodigal son is in:",
    ["Mark only", "Luke", "Revelation", "Obadiah"],
    1,
    "Luke 15 records three famous parables told by Jesus to answer Pharisees who criticized Him for welcoming sinners.\n\nThe story tells of a younger son who squandered his inheritance in wild living and returned home hoping to work as a hired servant.\n\nInstead, his father spotted him from afar, ran to embrace him, threw a feast, and declared: 'My son was dead and is alive again!'",
  ),
  q(
    "Jesus raises Lazarus in:",
    ["Bethany", "Nineveh", "Corinth", "Babylon"],
    0,
    "Lazarus and his sisters Martha and Mary were close friends of Jesus who lived in the village of Bethany near Jerusalem.\n\nWhen Lazarus fell ill and died, Jesus arrived four days after his burial, deeply moved and weeping at the tomb.\n\nJesus commanded the tomb stone to be rolled away and shouted: 'Lazarus, come out!', demonstrating His power over death.",
  ),
  q(
    "The Last Supper is framed as a:",
    ["Roman banquet with Caesar", "Passover meal", "Wedding at Cana repeating", "Funeral in Nain"],
    1,
    "On the night He was betrayed, Jesus gathered with His twelve apostles in an upper room in Jerusalem to celebrate Passover.\n\nDuring the meal, Jesus gave new significance to the bread and wine, identifying them as His body broken and blood shed for the forgiveness of sins.\n\nThis meal established the Christian sacrament of the Eucharist (Lord's Supper), remembered by churches worldwide.",
  ),
  q(
    "Who denies Jesus three times before a rooster crows?",
    ["Thomas", "Peter", "Andrew", "Philip"],
    1,
    "During the Last Supper, Simon Peter passionately swore that he would follow Jesus even to death, but Jesus warned that Peter would deny Him three times that very night.\n\nAfter Jesus was arrested and taken to the high priest's courtyard, three different onlookers recognized Peter as a follower.\n\nIn fear, Peter denied knowing Jesus three times, immediately hearing the rooster crow and weeping bitterly in repentance.",
  ),
  q(
    "Who betrays Jesus with a kiss in the Synoptic tradition?",
    ["Judas Iscariot", "Nicodemus", "Joseph of Arimathea", "Barnabas"],
    0,
    "Judas Iscariot, one of the original twelve apostles, agreed to hand Jesus over to the chief priests for thirty pieces of silver.\n\nLate at night in the Garden of Gethsemane, Judas led an armed band to Jesus and identified Him with a greeting kiss.\n\nJesus met Judas with sorrowful words: 'Judas, are you betraying the Son of Man with a kiss?'",
  ),
  q(
    "On the first Easter morning in the Gospels, the tomb is:",
    ["Sealed with Lazarus still inside", "Found empty", "Moved to Rome", "A metaphor with no location"],
    1,
    "At dawn on the first day of the week, Mary Magdalene and other faithful women brought spices to complete Jesus' burial rites.\n\nThey found the heavy stone rolled away from the tomb entrance and an angel clothed in bright white sitting upon it.\n\nThe angel delivered the glorious news: 'Do not be afraid... He is not here; He has risen, just as He said!'",
  ),
  q(
    "Pentecost in Acts is set in:",
    ["Jerusalem", "Athens", "Alexandria", "Carthage"],
    0,
    "Fifty days after Passover, 120 disciples were gathered together in Jerusalem praying in obedience to Jesus' command.\n\nSuddenly a sound like a mighty rushing wind filled the house, and tongues of fire rested above each believer as the Holy Spirit filled them.\n\nPeter preached a powerful sermon to gathered international crowds, resulting in 3,000 people believing and being baptized in a single day.",
  ),
  q(
    "Saul of Tarsus is better known after his calling as:",
    ["Peter", "Paul", "Stephen", "Timothy"],
    1,
    "Saul was a brilliant Pharisee educated under Gamaliel who vigorously persecuted early followers of Jesus.\n\nAfter his dramatic conversion encounter on the road to Damascus, Saul embraced his Roman name Paul and became the Apostle to the Gentiles.\n\nPaul traveled thousands of miles across the Mediterranean world planting churches and writing thirteen letters contained in the New Testament.",
  ),
  q(
    "Saul meets the risen Jesus on the road to:",
    ["Emmaus as Saul", "Damascus", "Jericho in the parable", "Joppa with Peter"],
    1,
    "Armed with official letters from the high priest to arrest Christians, Saul rode toward the ancient city of Damascus.\n\nSuddenly a blinding light from heaven flashed around him, throwing him to the ground as a voice asked: 'Saul, Saul, why do you persecute me?'\n\nBlinded for three days, Saul was led into Damascus where Ananias laid hands on him, restoring his sight and baptizing him into faith.",
  ),
  q(
    "Barnabas is known as a:",
    ["Companion of Paul and an encourager", "Roman governor of Syria", "Author of Revelation", "Pharaoh"],
    0,
    "Originally named Joseph, a Levite from Cyprus, the apostles nicknamed him Barnabas, which means 'Son of Encouragement.'\n\nBarnabas sold his field to support the poor Jerusalem church and was the first leader to embrace Paul after his conversion when others were afraid.\n\nBarnabas partnered with Paul on his first missionary trip, strengthening new churches across Cyprus and Asia Minor.",
  ),
  q(
    "Lydia, a dealer in purple cloth, is baptized in:",
    ["Philippi", "Ur", "Nineveh", "Bethlehem"],
    0,
    "In response to a heavenly vision of a Macedonian man pleading for help, Paul traveled to Europe for the first time, visiting Philippi.\n\nOn the Sabbath, Paul met a group of women praying by the river outside the city, including Lydia, a wealthy seller of luxury purple dye.\n\nGod opened Lydia's heart to believe, and she and her entire household were baptized, hosting the Philippian church in her home.",
  ),
  q(
    "The New Testament letter addressed to believers in Rome is:",
    ["Hebrews as its only title", "Romans", "Jude", "Philemon as a city letter"],
    1,
    "Written from Corinth around 57 AD, Romans is Paul's most thorough and systematic explanation of the Christian Gospel.\n\nIt explores human sinfulness, justification by faith through God's grace, spiritual life in the Holy Spirit, and Israel's role in redemption.\n\nRomans has transformed key leaders throughout history, including Saint Augustine, Martin Luther, and John Wesley.",
  ),
  q(
    "The letter of James emphasizes:",
    ["Faith lived out in works of mercy", "Building Solomon's temple", "The census of Quirinius as its theme", "Dietary law in Leviticus only"],
    0,
    "Authored by James, the brother of Jesus and leader of the Jerusalem church, this letter offers practical wisdom for Christian living.\n\nJames insists that genuine saving faith naturally produces good deeds, famously writing: 'Faith without works is dead.'\n\nThe book addresses controlling the tongue, caring for orphans and widows, praying for the sick, and avoiding favoritism.",
  ),
  q(
    "1 Corinthians 13 is especially known as the chapter on:",
    ["Spiritual gifts only as a budget", "Love", "The armor of God", "The fruit of the Spirit list in Galatians"],
    1,
    "In his first letter to the church at Corinth, Paul addressed division and spiritual pride by writing a poetic masterpiece on Christian love.\n\nPaul explains that even if one possesses miraculous gifts, without love it profits nothing.\n\nThe passage concludes: 'And now these three remain: faith, hope and love. But the greatest of these is love.'",
  ),
  q(
    "The fruit of the Spirit (love, joy, peace…) is listed in:",
    ["Galatians", "Jonah", "Leviticus as the only list", "3 John"],
    0,
    "In Galatians 5, Paul contrasts living according to selfish human nature with walking in the Holy Spirit.\n\nHe outlines nine spiritual virtues produced by the Spirit: love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control.\n\nPaul emphasizes that against such virtues there is no law, encouraging believers to keep in step with the Spirit.",
  ),
  q(
    "The armor of God (belt, breastplate, shield…) is described in:",
    ["Ephesians", "Ruth", "Esther", "Obadiah"],
    0,
    "Writing while chained to a Roman guard in prison, Paul used Roman military armor as a metaphor for spiritual warfare in Ephesians 6.\n\nHe urges believers to put on the full armor of God: the belt of truth, breastplate of righteousness, shoes of peace, shield of faith, helmet of salvation, and sword of the Spirit.\n\nPaul stresses that Christian battles are not against flesh and blood, but against spiritual forces of wickedness.",
  ),
  q(
    "Hebrews presents Jesus as:",
    ["A high priest of a better covenant", "A Roman emperor", "Jonah's captain", "The author of Proverbs only"],
    0,
    "Written to Jewish Christians facing pressure to return to temple Judaism, Hebrews demonstrates the supreme superiority of Jesus Christ.\n\nThe author shows that Jesus is greater than angels, Moses, and Levitical priests, serving as a permanent High Priest after the order of Melchizedek.\n\nThrough His own once-for-all sacrifice, Jesus established a better covenant grounded in eternal promises.",
  ),
  q(
    "Revelation is addressed to churches in:",
    ["Gaul", "Asia Minor (e.g. Ephesus, Smyrna)", "Ethiopia only", "Britain"],
    1,
    "The Book of Revelation opens with specific prophetic letters addressed to seven historic churches located in western Asia Minor (modern Turkey).\n\nThese churches—including Ephesus, Smyrna, Pergamum, Thyatira, Sardis, Philadelphia, and Laodicea—faced challenges ranging from persecution to lukewarm apathy.\n\nEach letter promises glorious heavenly rewards to believers who remain faithful and overcome.",
  ),
  q(
    "After Moses, who leads Israel across the Jordan into the land in Joshua?",
    ["Joshua", "Saul", "Ezra", "Titus"],
    0,
    "Following the death of Moses on Mount Nebo, Joshua son of Nun assumed leadership of Israel.\n\nGod commanded Joshua to 'Be strong and courageous', promising that His presence would accompany him into the Promised Land.\n\nJoshua led Israel across the flooded Jordan River on dry ground, marking the start of Canaan's conquest.",
  ),
  q(
    "Gideon's small force against Midian is told in:",
    ["Judges", "Acts", "Philemon", "2 John"],
    0,
    "When Midianite raiders oppressed Israel, an angel called Gideon while he was secretly threshing wheat in a winepress.\n\nGod instructed Gideon to reduce his army from 32,000 men down to just 300 so Israel would not boast in human strength.\n\nEquipped with torches, clay jars, and trumpets, Gideon's 300 men surrounded the enemy camp at night and achieved a miraculous victory.",
  ),
  q(
    "Samuel anoints which shepherd as future king?",
    ["David", "Herod", "Ahab", "Cyrus as an Israelite king"],
    0,
    "When King Saul disobeyed God, Samuel was sent to Bethlehem to anoint a new king from the house of Jesse.\n\nAfter examining Jesse's seven eldest sons, Samuel asked if there were any remaining children, and David was brought in from the fields.\n\nAs soon as David arrived, the Lord told Samuel: 'Rise and anoint him; he is the one.'",
  ),
  q(
    "Jezebel is an opponent of:",
    ["Elijah", "Luke", "Onesimus", "Simeon in the temple"],
    0,
    "Jezebel, a Phoenician princess married to King Ahab of Israel, introduced Baal worship and executed Lord's prophets across the land.\n\nShe became the bitter enemy of Elijah after his fiery triumph on Mount Carmel, threatening to take his life.\n\nHer name became synonymous in biblical memory with tyranny and pagan idolatry.",
  ),
  q(
    "Nehemiah is remembered for rebuilding:",
    ["The walls of Jerusalem", "Noah's ark", "The Colosseum", "Paul's ship"],
    0,
    "Nehemiah served as royal cupbearer to King Artaxerxes of Persia when news reached him that Jerusalem's walls remained broken down and vulnerable.\n\nGranted royal permission and supplies, Nehemiah traveled to Jerusalem and organized families to rebuild different wall sections simultaneously.\n\nDespite threats and mockery from neighboring enemies, the wall was completed in just 52 days.",
  ),
  q(
    "In many Protestant English Bibles, the last book of the Old Testament is:",
    ["Malachi", "Matthew", "Revelation", "Psalms"],
    0,
    "Malachi ministered in Jerusalem after the exile, rebuking cold worship and social injustice among priests and people.\n\nThe book closes with a striking prophecy promising that God will send the prophet Elijah before the great day of the Lord.\n\nThis prophecy forms the thematic bridge to the Gospels, fulfilled in the wilderness ministry of John the Baptist.",
  ),
  q(
    "The magi in Matthew come from the:",
    ["West as fishermen", "East", "South Pole", "Island of Patmos"],
    1,
    "Matthew 2 records that wise men (magi) from eastern lands arrived in Jerusalem following a miraculous star.\n\nThey inquired: 'Where is the one who has been born king of the Jews?', troubling King Herod and Jerusalem leaders.\n\nGuided to Bethlehem, the magi bowed down, worshiped the young child, and presented gifts of gold, frankincense, and myrrh.",
  ),
  q(
    "The tax collector called to follow Jesus, associated with the first Gospel, is:",
    ["Matthew (Levi)", "Luke the governor", "Pontius Pilate", "Cornelius as the Gospel writer"],
    0,
    "Matthew, also named Levi, was working at a tax booth in Capernaum collecting revenues for Herod Antipas when Jesus walked by.\n\nJesus said simply: 'Follow me', and Matthew immediately left his lucrative booth to follow Him.\n\nMatthew hosted a great dinner at his house where many tax collectors and sinners gathered to hear Jesus teach.",
  ),
  q(
    "Which disciple is remembered for wanting to see and touch the risen Jesus?",
    ["Thomas", "Judas Iscariot after Easter", "Ananias of Damascus as a disciple of the Twelve", "Barabbas"],
    0,
    "When Jesus first appeared to the disciples on Easter evening, Thomas was absent and refused to believe their eyewitness testimony.\n\nThomas declared he would not believe unless he saw the nail marks in Jesus' hands and touched His side.\n\nEight days later, Jesus appeared directly to Thomas, who declared in awe: 'My Lord and my God!'",
  ),
  q(
    "Mary Magdalene is a witness at:",
    ["The empty tomb", "Sinai in Exodus", "Solomon's dedication only", "Jonah's ship"],
    0,
    "Mary Magdalene was a devoted follower of Jesus from whom He had cast out seven demons.\n\nShe faithfully stood near the cross during the Crucifixion and was the first person to visit the tomb on Easter morning.\n\nJesus appeared to Mary first in the garden, commissioning her to tell the apostles that He had risen.",
  ),
  q(
    "The parable of the good Samaritan is in:",
    ["Luke", "Nahum", "Titus as a parable chapter", "Jude"],
    0,
    "In Luke 10, an expert in the law asked Jesus: 'And who is my neighbor?', prompting Jesus to tell a memorable story.\n\nA traveler was beaten by robbers and left half-dead; both a priest and a Levite walked by on the other side of the road without helping.\n\nHowever, a despised Samaritan stopped, bandaged his wounds, took him to an inn, and paid for his care, defining true neighborly love.",
  ),
  q(
    " 'In the beginning was the Word' opens:",
    ["Genesis again as a Gospel", "The Gospel of John", "Acts", "James"],
    1,
    "The Gospel of John opens with a magnificent prologue that echoes Genesis 1:1, introducing Jesus as the divine Logos ('Word').\n\nJohn explains that the Word was with God in the beginning, was God, and was the agent through whom all creation was made.\n\nJohn 1:14 declares the mystery of the Incarnation: 'The Word became flesh and made his dwelling among us.'",
  ),
  q(
    "The early community in Acts 2 gathers in:",
    ["Jerusalem", "Babylon", "Rome as the first scene of Acts", "Nazareth as the Pentecost city"],
    0,
    "Following the outpouring of the Holy Spirit on Pentecost, the early Christian community in Jerusalem formed a vibrant fellowship.\n\nBelievers devoted themselves to the apostles' teaching, breaking bread from house to house, sharing possessions, and praising God.\n\nActs records that God added to their number daily those who were being saved.",
  ),
  q(
    "Timothy is a:",
    ["Young coworker of Paul", "Judge who defeated Midian", "Persian king", "Author of Genesis"],
    0,
    "Timothy was a young disciple from Lystra with a Jewish mother and Greek father who joined Paul on his second missionary journey.\n\nPaul mentored Timothy as a son in the faith, entrusting him with pastoral leadership over the church in Ephesus.\n\nTwo pastoral letters in the New Testament (1 & 2 Timothy) contain Paul's final instructions and encouragement to Timothy.",
  ),
  q(
    "Philemon is a short letter about:",
    ["Onesimus and a plea for welcome", "Building the second temple", "The census in Bethlehem", "The armor of God"],
    0,
    "Philemon was a wealthy Christian leader in Colossae whose enslaved servant Onesimus had run away to Rome.\n\nWhile in Rome, Onesimus met Paul, was converted to Christ, and became a beloved coworker.\n\nPaul wrote this tender personal letter asking Philemon to welcome Onesimus back not as a slave, but as a brother in Christ.",
  ),
  q(
    "The shortest verse in many English Bibles is:",
    ["Jesus wept", "In the beginning", "Amen", "Selah as a numbered verse"],
    0,
    "John 11:35 consists of just two words in English: 'Jesus wept', spoken at the tomb of His friend Lazarus.\n\nThis brief verse reveals the profound compassion, humanity, and empathy of Jesus in the face of human grief and death.\n\nIt demonstrates that God is not indifferent to human suffering, but shares in our sorrows.",
  ),
  q(
    "The 'Shema' ('Hear, O Israel…') is found in:",
    ["Deuteronomy", "Revelation 1 as its only home", "Acts 27", "Jude"],
    0,
    "Deuteronomy 6:4–5 contains the central prayer and monotheistic confession of faith: 'Hear, O Israel: The LORD our God, the LORD is one.'\n\nIt commands believers to love God with all their heart, soul, and strength, and to teach these words diligently to their children.\n\nJesus cited the Shema as the greatest commandment in all of Scripture.",
  ),
];
