import type { Question } from "@/lib/types";

function q(
  prompt: string,
  choices: string[],
  answerIndex: number,
  explanation: string,
): Question {
  return { prompt, choices, answerIndex, explanation };
}

/** Original 52-item remix of a long-form restaurant quiz (fast / family / fine). Not Grizly copy. */
export const RESTAURANT_FILL_QUESTIONS: Question[] = [
  q("Michelin stars rate restaurants, not individual dishes. How many stars is the top mark?", ["Three", "Five", "Ten", "One hundred"], 0, "Three stars means exceptional cuisine worth a special journey."),
  q("In classic brigade kitchens, the chef de partie who runs sauces is the:", ["Saucier", "Poissonnier", "Boulanger", "Sommelier"], 0, "The saucier owns stocks, sauces, and often sauté work."),
  q("A prix fixe menu means:", ["You pay one set price for a composed meal", "Every item is half off after 9 p.m.", "You must tip 30%", "Only dessert is included"], 0, "Courses are bundled; à la carte is the opposite."),
  q("Mise en place refers to:", ["Having ingredients and tools ready before service", "A dessert from Alsace", "The check presenter", "A wine region in Chile"], 0, "It is the cook’s setup, not a dish."),
  q("The danger zone for perishable food is roughly:", ["40–140°F (4–60°C)", "0–10°F", "212–250°F", "Room temperature is always safe if salted"], 0, "Bacteria multiply fastest in that band."),
  q("A cover in restaurant math is:", ["One guest seated (or a meal served)", "A lid for a pan", "The awning", "A reservation app"], 0, "Covers measure how many people you served."),
  q("Family-style service typically means:", ["Platters for the table to share", "Each plate is assembled in a window like fast food", "Only tasting menus", "No silverware"], 0, "Guests pass shared dishes."),
  q("Fine dining’s silent service ideally:", ["Anticipates needs without hovering chatter", "Requires a microphone at every table", "Bans water until dessert", "Uses only plastic ware"], 0, "Presence without interruption."),
  q("A sommelier’s core job is:", ["Wine (and often beverage) counsel and service", "Only baking bread", "Valet parking", "Writing the lease"], 0, "They pair and pour, not just memorize vintages."),
  q("Al dente pasta is:", ["Firm to the bite, not mushy", "Served ice cold", "Fried after boiling", "Always whole wheat"], 0, "Italian for “to the tooth.”"),
  q("Umami is best described as:", ["Savory depth from glutamates", "Only sweetness", "A type of chili heat", "The crunch of ice"], 0, "Soy, Parmesan, mushrooms, and broths carry it."),
  q("A Roux is:", ["Flour cooked in fat, used to thicken", "A raw egg foam", "Smoked salt only", "A Japanese grill"], 0, "White, blond, or brown depending on cook time."),
  q("Ceviche “cooks” fish primarily with:", ["Acid (citrus)", "A deep fryer", "Liquid nitrogen", "Only soy sauce"], 0, "Acid denatures proteins; it is not heat."),
  q("Sushi and sashimi differ because sashimi is typically:", ["Sliced raw fish without vinegared rice", "Always cooked eel", "A dessert mochi", "Only vegetarian"], 0, "Sushi implies rice; sashimi does not."),
  q("Dim sum is traditionally:", ["Small plates, often from carts, rooted in Cantonese tea houses", "A single giant dumpling as an entrée", "Only Korean BBQ", "A French pastry case"], 0, "Think har gow, siu mai, and tea."),
  q("Tapas culture started as:", ["Small bites with drinks in Spain", "Airport snack kiosks in Texas", "A Michelin category", "Only seafood towers"], 0, "The name relates to a “cover” on a glass."),
  q("A bistro, historically, is:", ["A modest Parisian neighborhood restaurant", "A 400-seat banquet hall", "A food truck only", "A hotel room-service brand"], 0, "Casual, not palace dining."),
  q("A diner in the U.S. is most associated with:", ["Counter service, booths, and all-day breakfast", "Tasting menus and dress codes", "Only sushi", "Airline catering"], 0, "Chrome, coffee, and a long grill."),
  q("Fast casual usually means:", ["Counter order, higher quality than burger-window chains, no full table service", "White tablecloth and captains", "Gas-station taquitos only", "Private clubs"], 0, "Chipotle-style lanes, not white-glove."),
  q("QSR in industry jargon is:", ["Quick-service restaurant", "Qualified sous-vide rating", "Queen’s service ritual", "Queueing systems regulation"], 0, "The trade term for fast food."),
  q("The first White Castle opened in:", ["1921, Wichita", "1965, Seattle", "1890, London", "2001, Dubai"], 0, "It helped invent the U.S. hamburger chain."),
  q("Ray Kroc scaled McDonald’s after seeing a:", ["Speedy assembly-line hamburger stand in California", "Paris brasserie", "Tokyo ramen stall", "London chip shop"], 0, "The McDonald brothers’ San Bernardino system."),
  q("Colonel Sanders is the public face of:", ["KFC", "Wendy’s", "Burger King", "Arby’s"], 0, "Fried chicken franchise built on his image."),
  q("In-N-Out is famous for a:", ["Not-secret “secret menu” and fresh-never-frozen beef", "Michelin three-star tasting menu", "Only breakfast burritos", "Robot waiters"], 0, "West Coast cult chain."),
  q("A drive-thru exists to:", ["Serve people who stay in the car", "Replace kitchens", "Only deliver wine", "Host wedding banquets"], 0, "Speed and convenience, invented mid-century."),
  q("Tipping in full-service U.S. restaurants is:", ["A large part of server pay; customs vary by country", "Illegal in all states", "Always included as 50%", "Paid only in coins"], 0, "Europe often builds service into prices."),
  q("A tasting menu is:", ["A chef-chosen sequence of small courses", "An all-you-can-eat buffet", "Kids’ chicken fingers", "A wine flight without food"], 0, "You surrender the à la carte steering wheel."),
  q("Amuse-bouche is:", ["A tiny complimentary bite before the meal", "The dessert cart", "A cocktail shaker", "The check"], 0, "French for a little mouth amusement."),
  q("Farm-to-table marketing claims you should still:", ["Ask what’s actually local and seasonal", "Assume every tomato is from next door", "Ignore food safety", "Skip vegetables"], 0, "The phrase is not a legal grade."),
  q("A food cost percentage is roughly:", ["Cost of ingredients ÷ food sales", "Rent ÷ covers", "Tips ÷ hours", "Stars ÷ seats"], 0, "Operators live and die on that ratio."),
  q("The pass (or pass window) is where:", ["Finished plates leave the kitchen for the floor", "Guests hang coats", "Wine is stored long-term", "Reservations print"], 0, "Expediters work the pass."),
  q("86 on a ticket means:", ["We’re out of that item", "Fire two more steaks", "Comp the table", "Seat the bar"], 0, "Kitchen slang for sold out."),
  q("Fire it, in kitchen slang, means:", ["Start cooking that ticket now", "Call the fire department", "Turn off the grill", "Print the menu"], 0, "Timing language between FOH and BOH."),
  q("FOH and BOH mean:", ["Front of house and back of house", "Forks on hand / bowls on hand", "Fine or budget hospitality", "Friday or brunch hours"], 0, "Service floor vs kitchen."),
  q("A host stand’s job includes:", ["Greeting, waitlists, and pacing the dining room", "Only washing pans", "Only making espresso", "Auditing taxes"], 0, "The room’s traffic cop."),
  q("Turn time is:", ["How long a table is occupied before it can be reseated", "Oven preheat", "The sommelier’s shift", "Happy hour length"], 0, "Faster turns can mean more covers — or worse hospitality."),
  q("A tasting spoon at the pass is for:", ["The chef tasting and correcting seasoning", "Guests to keep as souvenirs", "Only desserts", "Measuring wine"], 0, "Quality control, not a course."),
  q("Gluten-free service requires:", ["Avoiding cross-contact with wheat, barley, rye", "Only skipping the bread basket visually", "Frying in the same oil as beer-battered items with no change", "A different ZIP code"], 0, "Shared fryers and flour dust matter."),
  q("A nut allergy on a ticket should trigger:", ["Clear labeling, separate tools, and manager awareness", "Extra peanut sauce as a test", "Ignoring it if the guest looks fine", "Only a verbal shrug"], 0, "Allergens are a safety system, not a preference."),
  q("Espresso is:", ["A short, pressurized coffee extraction", "Drip coffee left on a burner all day", "Decaf tea", "A blender drink by default"], 0, "Nine bars, short shot, crema if you’re lucky."),
  q("Cappuccino classically is:", ["Espresso, steamed milk, and foam in roughly even parts", "Only whipped cream", "Iced tea", "A 32-oz soda"], 0, "Ratio is the whole point."),
  q("A digestif is typically served:", ["After the meal to close the service", "As the first amuse", "Instead of water", "With breakfast only"], 0, "Amaro, cognac, grappa, and friends."),
  q("Aperitif timing is:", ["Before the meal to open the appetite", "With the check", "Only at 3 a.m.", "Instead of dessert forever"], 0, "Spritz, vermouth, champagne."),
  q("MSG in cooking is:", ["A sodium salt of glutamic acid that boosts umami", "Always illegal", "A type of mold", "Only a cleaning chemical"], 0, "It occurs naturally in tomatoes and cheese too."),
  q("Sous-vide cooks food:", ["In a sealed bag in a precise water bath", "Only over open flame", "In a deep fryer at 400°F as the definition", "In a microwave on high as the only method"], 0, "Time and temperature, not smoke."),
  q("A wood-fired pizza oven’s advantage is:", ["Very high heat and char", "It refrigerates dough", "It removes gluten", "It proves wine"], 0, "Neapolitan-style heat."),
  q("The Maillard reaction is:", ["Browning of proteins and sugars that builds flavor", "Only caramel melting", "A wine fault", "Ice crystallization"], 0, "Seared steak and baked bread live here."),
  q("Resting a steak after grilling:", ["Lets juices redistribute so they don’t all run out on the board", "Makes it raw again", "Is only for fish", "Replaces seasoning"], 0, "A few minutes, loosely tented."),
  q("A tasting menu wine pairing should:", ["Match intensity and reset the palate between courses", "Always be the cheapest bottle", "Ignore the food", "Be soda only"], 0, "Weight, acid, and tannin vs the plate."),
  q("Open kitchen design trades:", ["Showmanship and noise for transparency", "Always lower food cost automatically", "No need for ventilation", "Guaranteed Michelin stars"], 0, "Guests see the work — and hear it."),
  q("Ghost kitchens are:", ["Delivery-only cooking sites with little or no dining room", "Haunted diners as a legal category", "Michelin’s secret third room", "Food trucks that never move"], 0, "Brands without a storefront."),
  q("A pop-up restaurant is:", ["A short-run concept in a borrowed or temporary space", "A permanent 200-year lease", "Only vending machines", "A hotel breakfast always"], 0, "Chefs test ideas without a full build-out."),
  q("The check presenter is:", ["The billfold or tray used to drop the check", "The person who only greets", "A wine list", "The reservation book"], 0, "FOH tool, not a course."),
  q("Comp in restaurant slang means:", ["Give it away (complimentary)", "Compress the dough", "Compost only", "A computer crash"], 0, "Managers comp to recover a mistake — or to schmooze."),
];
