import type { Chapter, WordSpark } from "../types";

export const WEEK_4_ARC = "Week 4: The Church, Grace & New Creation";

export const SPARKS_WEEK_4: Record<string, WordSpark> = {
  koinonia: {
    id: "koinonia",
    term: "fellowship / sacred community",
    language: "Greek",
    originalScript: "κοινωνία",
    transliteration: "koinōnia",
    rootMeaning: "intimate sharing in common, sacred mutual partnership",
    culturalInsight:
      "Acts 2:42 describes the apostolic community devoted to the 'koinonia'. It was not superficial socialization, but a radical sharing of hearts, meals, resources, and worship.",
  },
  eklektos: {
    id: "eklektos",
    term: "chosen vessel",
    language: "Greek",
    originalScript: "ἐκλεκτός",
    transliteration: "eklektos",
    rootMeaning: "picked out, selected for sacred commission",
    culturalInsight:
      "When the Lord sent Ananias to the blinded Saul on Straight Street, He called him a 'chosen instrument' (skeuos ekloges) to carry Christ's name before kings and Gentiles.",
  },
  huiothesia: {
    id: "huiothesia",
    term: "adoption as sons",
    language: "Greek",
    originalScript: "υἱοθεσία",
    transliteration: "huiothesia",
    rootMeaning: "legal placement as a full heir with family rights",
    culturalInsight:
      "In Roman law, an adopted son gained all privileges of natural birth and had all previous debts completely wiped clean. In Romans 8, believers receive the Spirit of adoption, crying 'Abba, Father!'",
  },
  agape: {
    id: "agape",
    term: "unconditional self-giving love",
    language: "Greek",
    originalScript: "ἀγάπη",
    transliteration: "agapē",
    rootMeaning: "sacrificial, active, unconditional benevolence",
    culturalInsight:
      "Unlike eros (romantic desire) or philia (friendship affinity), agape does not depend on the worthiness of the recipient. It pours itself out expecting nothing in return.",
  },
  panoplia: {
    id: "panoplia",
    term: "full armor",
    language: "Greek",
    originalScript: "πανοπλία",
    transliteration: "panoplia",
    rootMeaning: "complete suit of defensive and offensive military armor",
    culturalInsight:
      "Chained to Roman legionaries in prison, Paul used the soldier’s breastplate, shield, helmet, and sword to illustrate the spiritual defenses of the believer.",
  },
  chara: {
    id: "chara",
    term: "joy",
    language: "Greek",
    originalScript: "χαρά",
    transliteration: "chara",
    rootMeaning: "deep-seated delight rooted in God's grace (charis)",
    culturalInsight:
      "Writing from Roman imprisonment, Paul wrote 'Rejoice in the Lord always!' Chara is not circumstantial happiness, but steady soul-anchored confidence in Christ.",
  },
  hypostasis: {
    id: "hypostasis",
    term: "substance / assurance",
    language: "Greek",
    originalScript: "ὑπόστασις",
    transliteration: "hypostasis",
    rootMeaning: "firm foundation, title deed, underlying reality",
    culturalInsight:
      "Hebrews 11:1: 'Faith is the substance (hypostasis) of things hoped for.' In ancient commerce, hypostasis referred to the title deed verifying ownership before taking possession.",
  },
  hypomone: {
    id: "hypomone",
    term: "steadfast endurance",
    language: "Greek",
    originalScript: "ὑπομονή",
    transliteration: "hypomonē",
    rootMeaning: "remaining under pressure without wavering, resilient grit",
    culturalInsight:
      "James 1:3 encourages counting trials as joy because testing produces hypomone—the triumphant resilience that stands firm beneath heavy loads.",
  },
  kainos: {
    id: "kainos",
    term: "new in quality / fresh",
    language: "Greek",
    originalScript: "καινός",
    transliteration: "kainos",
    rootMeaning: "new in nature and splendor, uncorrupted, fresh",
    culturalInsight:
      "Revelation 21:5: 'Behold, I make all things new (kaina).' God does not scrap His creation into oblivion; He redeems, purges, and glorifies it into a dazzling new cosmic reality.",
  },
};

export const WEEK_4_CHAPTERS: Chapter[] = [
  // DAY 22: Acts 2
  {
    bookSlug: "acts",
    bookTitle: "Acts",
    chapterNumber: 2,
    dayNumber: 22,
    arcName: WEEK_4_ARC,
    title: "The Day of Pentecost & The First Church",
    subtitle: "Rushing wind, tongues of fire, and the birth of the global church.",
    thematicHook: "A sound like the blowing of a violent wind fills the house. Resting on each of them are tongues of fire, and three thousand are baptized in a day.",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q23.png",
    coinsReward: 50,
    sparks: {
      koinonia: SPARKS_WEEK_4.koinonia,
    },
    verses: [
      { number: 1, text: "When the day of Pentecost came, they were all together in one place." },
      { number: 2, text: "Suddenly a sound like the blowing of a violent wind came from heaven and filled the whole house where they were sitting." },
      { number: 3, text: "They saw what seemed to be tongues of fire that separated and came to rest on each of them." },
      { number: 4, text: "All of them were filled with the Holy Spirit and began to speak in other tongues as the Spirit enabled them." },
      { number: 38, text: "Peter replied, 'Repent and be baptized, every one of you, in the name of Jesus Christ for the forgiveness of your sins. And you will receive the gift of the Holy Spirit.'" },
      { number: 42, text: "They devoted themselves to the apostles' teaching and to fellowship, to the breaking of bread and to prayer.", sparkIds: ["koinonia"] },
      { number: 44, text: "All the believers were together and had everything in common." },
    ],
    checkInQuestions: [
      {
        prompt: "What visible manifestation rested upon the disciples at Pentecost?",
        choices: ["Golden halos", "Tongues like fire that separated and rested on each", "A pillar of white cloud", "Rain from heaven"],
        correctIndex: 1,
        explanation: "Acts 2:3 records tongues like fire dividing and resting upon each believer present.",
      },
      {
        prompt: "How many people were baptized following Peter's sermon in Jerusalem on that day?",
        choices: ["About three hundred", "About three thousand", "About twelve thousand", "Seventy elders"],
        correctIndex: 1,
        explanation: "Acts 2:41 notes that about three thousand souls accepted the message and were baptized.",
      },
      {
        prompt: "What four core disciplines did the early church devote themselves to in Acts 2:42?",
        choices: [
          "Military strategy, civil law, trade, and building walls",
          "The apostles' teaching, fellowship (koinonia), breaking bread, and prayer",
          "Fasting alone in deserts, silence, and ritual washing",
          "Tax collecting and politics",
        ],
        correctIndex: 1,
        explanation: "Acts 2:42 forms the timeless charter of Christian community.",
      },
    ],
    storySlides: [
      {
        id: "act2-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q23.png",
        badge: "Day 22 · Pentecost",
        title: "The Fire Falls",
        text: "One hundred and twenty disciples waiting in an upper room. Suddenly, celestial wind roars through Jerusalem and fire crowns each brow.",
      },
      {
        id: "act2-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q23.png",
        scriptureRef: "Acts 2:2–4",
        text: "“Suddenly a sound like a violent wind came from heaven... They saw what seemed to be tongues of fire... All of them were filled with the Holy Spirit.”",
      },
      {
        id: "act2-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q23.png",
        scriptureRef: "Acts 2:42",
        text: "“They devoted themselves to the apostles’ teaching and to fellowship, to the breaking of bread and to prayer.”",
        spark: SPARKS_WEEK_4.koinonia,
      },
      {
        id: "act2-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q23.png",
        title: "Koinonia: Sacred Oneness",
        text: "The church was born not as a corporation, but as a living body sharing one Spirit, one bread, and one unwavering mission.",
      },
      {
        id: "act2-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q23.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Greek word signifies radical, sacred fellowship and mutual partnership in Christ?",
          choices: ["Koinonia", "Panoplia", "Kainos"],
          correctIndex: 0,
          explanation: "Koinonia is deep spiritual communion and fellowship.",
        },
      },
    ],
  },

  // DAY 23: Acts 9
  {
    bookSlug: "acts",
    bookTitle: "Acts",
    chapterNumber: 9,
    dayNumber: 23,
    arcName: WEEK_4_ARC,
    title: "The Damascus Road & Paul's Calling",
    subtitle: "From chief persecutor of Christians to chosen vessel of the Gospel.",
    thematicHook: "Breathing threats and murder against the followers of Jesus, Saul approaches Damascus. A blinding celestial light knocks him to the earth.",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q24.png",
    coinsReward: 50,
    sparks: {
      eklektos: SPARKS_WEEK_4.eklektos,
    },
    verses: [
      { number: 3, text: "As he neared Damascus on his journey, suddenly a light from heaven flashed around him." },
      { number: 4, text: "He fell to the ground and heard a voice say to him, 'Saul, Saul, why do you persecute me?'" },
      { number: 5, text: "'Who are you, Lord?' Saul asked. 'I am Jesus, whom you are persecuting,' he replied." },
      { number: 6, text: "'Now get up and go into the city, and you will be told what you must do.'" },
      { number: 15, text: "But the Lord said to Ananias, 'Go! This man is my chosen instrument to proclaim my name to the Gentiles and their kings and to the people of Israel.'", sparkIds: ["eklektos"] },
      { number: 18, text: "Immediately, something like scales fell from Saul's eyes, and he could see again. He got up and was baptized," },
      { number: 20, text: "At once he began to preach in the synagogues that Jesus is the Son of God." },
    ],
    checkInQuestions: [
      {
        prompt: "What question did the risen Jesus ask Saul when he fell to the earth?",
        choices: [
          "'Why do you persecute Me?'",
          "'Where are your papers from Jerusalem?'",
          "'Do you know the Roman law?'",
          "'Why have you fled from Judea?'",
        ],
        correctIndex: 0,
        explanation: "Jesus said: 'Saul, Saul, why do you persecute Me?'—revealing that persecuting His church is persecuting Christ Himself.",
      },
      {
        prompt: "Who did God send in Damascus to lay hands on Saul so that he might regain his sight?",
        choices: ["Peter", "Barnabas", "Ananias", "Stephen"],
        correctIndex: 2,
        explanation: "Acts 9:10–17 records that a humble disciple named Ananias obeyed God's voice to minister to Saul.",
      },
      {
        prompt: "What fell from Saul's eyes when Ananias prayed over him?",
        choices: ["Tears of blood", "Something like scales", "A veil of cloth", "Sand from the road"],
        correctIndex: 1,
        explanation: "Acts 9:18 notes that something like scales dropped from his eyes, restoring physical and spiritual vision.",
      },
    ],
    storySlides: [
      {
        id: "act9-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q24.png",
        badge: "Day 23 · The Conversion",
        title: "The Blinding Light",
        text: "The church’s fiercest enemy was riding hard toward Damascus with arrest warrants. One flash of heavenly glory shattered his self-righteous armor.",
      },
      {
        id: "act9-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q24.png",
        scriptureRef: "Acts 9:4–5",
        text: "“He fell to the ground and heard a voice: 'Saul, Saul, why do you persecute Me?' 'Who are you, Lord?' Saul asked. 'I am Jesus, whom you are persecuting.'”",
      },
      {
        id: "act9-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q24.png",
        scriptureRef: "Acts 9:15",
        text: "“The Lord said to Ananias: 'Go! This man is my chosen instrument to proclaim my name to the Gentiles and their kings.'”",
        spark: SPARKS_WEEK_4.eklektos,
      },
      {
        id: "act9-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q24.png",
        title: "No One is Beyond Grace",
        text: "If grace can turn Saul the persecutor into Paul the apostle of love, no soul is too far gone for the redeeming reach of Jesus Christ.",
      },
      {
        id: "act9-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q24.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Greek term meaning 'chosen instrument' designated Paul's commission?",
          choices: ["Eklektos", "Hypostasis", "Koinonia"],
          correctIndex: 0,
          explanation: "Eklektos means chosen and appointed for sacred service.",
        },
      },
    ],
  },

  // DAY 24: Romans 8
  {
    bookSlug: "romans",
    bookTitle: "Romans",
    chapterNumber: 8,
    dayNumber: 24,
    arcName: WEEK_4_ARC,
    title: "No Condemnation & Life in the Spirit",
    subtitle: "The mountain peak of the Epistles: adoption, intercession, and unbreakable love.",
    thematicHook: "'If God is for us, who can be against us?... Neither death nor life, neither angels nor demons, will be able to separate us from the love of God in Christ Jesus.'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q25.png",
    coinsReward: 50,
    sparks: {
      huiothesia: SPARKS_WEEK_4.huiothesia,
    },
    verses: [
      { number: 1, text: "Therefore, there is now no condemnation for those who are in Christ Jesus," },
      { number: 14, text: "For those who are led by the Spirit of God are the children of God." },
      { number: 15, text: "The Spirit you received does not make you slaves, so that you live in fear again; rather, the Spirit you received brought about your adoption to sonship. And by him we cry, 'Abba, Father.'", sparkIds: ["huiothesia"] },
      { number: 16, text: "The Spirit himself testifies with our spirit that we are God's children." },
      { number: 28, text: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose." },
      { number: 31, text: "What, then, shall we say in response to these things? If God is for us, who can be against us?" },
      { number: 38, text: "For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers," },
      { number: 39, text: "neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord." },
    ],
    checkInQuestions: [
      {
        prompt: "What glorious declaration opens Romans chapter 8 in verse 1?",
        choices: [
          "There is now no condemnation for those in Christ Jesus",
          "The law must be observed with fear",
          "Only the circumcised shall stand",
          "Tribulation will conquer the saints",
        ],
        correctIndex: 0,
        explanation: "Romans 8:1 announces total freedom from guilt: 'There is now no condemnation for those who are in Christ Jesus.'",
      },
      {
        prompt: "What spirit did believers receive instead of a spirit of slavery to fear?",
        choices: ["The spirit of the world", "The Spirit of adoption as sons (huiothesia)", "The spirit of judgment", "A spirit of solitary exile"],
        correctIndex: 1,
        explanation: "Romans 8:15 reveals we received the Spirit of adoption, by whom we cry 'Abba, Father!'",
      },
      {
        prompt: "Can anything in all creation separate the believer from God's love in Christ Jesus?",
        choices: [
          "Severe poverty can",
          "Roman swords can",
          "Nothing in all creation can separate us",
          "Angels of the abyss can",
        ],
        correctIndex: 2,
        explanation: "Romans 8:38–39 rings with triumphant certainty: nothing in heaven, earth, or hell can sever us from His love.",
      },
    ],
    storySlides: [
      {
        id: "rom8-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q25.png",
        badge: "Day 24 · The High Peak",
        title: "No Condemnation",
        text: "Martin Luther called Romans 8 the brightest gem of all Scripture. It begins with no condemnation and ends with no separation.",
      },
      {
        id: "rom8-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q25.png",
        scriptureRef: "Romans 8:1, 15",
        text: "“There is now no condemnation for those who are in Christ Jesus... You received the Spirit of adoption to sonship, and by Him we cry, 'Abba, Father.'”",
        spark: SPARKS_WEEK_4.huiothesia,
      },
      {
        id: "rom8-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q25.png",
        scriptureRef: "Romans 8:31, 38–39",
        text: "“If God is for us, who can be against us?... Neither death nor life, neither angels nor demons, will be able to separate us from the love of God in Christ Jesus.”",
      },
      {
        id: "rom8-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q25.png",
        title: "More Than Conquerors",
        text: "We are not merely survivors of trials. In Christ, every suffering, distress, and sword becomes the very soil where God's triumphant love is proved.",
      },
      {
        id: "rom8-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q25.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Greek legal term in Romans 8 describes our placement into God's family with full inheritance?",
          choices: ["Huiothesia", "Agape", "Koinonia"],
          correctIndex: 0,
          explanation: "Huiothesia is adoption as full sons and daughters of God.",
        },
      },
    ],
  },

  // DAY 25: 1 Corinthians 13
  {
    bookSlug: "1-corinthians",
    bookTitle: "1 Corinthians",
    chapterNumber: 13,
    dayNumber: 25,
    arcName: WEEK_4_ARC,
    title: "The Greatest of These is Love",
    subtitle: "The hymn of Agape: patient, kind, never failing, and enduring beyond all gifts.",
    thematicHook: "'If I speak in the tongues of men or of angels, but do not have love, I am only a resounding gong or a clanging cymbal.'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q26.png",
    coinsReward: 50,
    sparks: {
      agape: SPARKS_WEEK_4.agape,
    },
    verses: [
      { number: 1, text: "If I speak in the tongues of men or of angels, but do not have love, I am only a resounding gong or a clanging cymbal.", sparkIds: ["agape"] },
      { number: 2, text: "If I have the gift of prophecy and can fathom all mysteries and all knowledge, and if I have a faith that can move mountains, but do not have love, I am nothing." },
      { number: 4, text: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud." },
      { number: 5, text: "It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs." },
      { number: 7, text: "It always protects, always trusts, always hopes, always perseveres." },
      { number: 8, text: "Love never fails. But where there are prophecies, they will cease; where there are tongues, they will be stilled; where there is knowledge, it will pass away." },
      { number: 13, text: "And now these three remain: faith, hope and love. But the greatest of these is love." },
    ],
    checkInQuestions: [
      {
        prompt: "What are eloquence, knowledge, and mountain-moving faith without love according to Paul?",
        choices: [
          "Impressive human achievements",
          "Worth half their spiritual value",
          "A resounding gong, a clanging cymbal, and nothing",
          "Acceptable for leaders only",
        ],
        correctIndex: 2,
        explanation: "1 Corinthians 13:1–2 warns that even supernatural spiritual gifts without love amount to zero in God's eyes.",
      },
      {
        prompt: "What does love never keep according to verse 5?",
        choices: ["A record of wrongs", "Financial ledgers", "A journal of prayers", "A copy of the law"],
        correctIndex: 0,
        explanation: "Agape love does not store up offenses or nurse bitterness; it keeps no record of wrongs.",
      },
      {
        prompt: "Of the three eternal virtues that remain—faith, hope, and love—which is the greatest?",
        choices: ["Faith", "Hope", "Love (Agape)", "Prophecy"],
        correctIndex: 2,
        explanation: "1 Corinthians 13:13 crowns love as the greatest, for God Himself is love.",
      },
    ],
    storySlides: [
      {
        id: "1c13-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q26.png",
        badge: "Day 25 · The Hymn",
        title: "The Clanging Cymbal",
        text: "The Corinthian church chased spiritual fireworks, eloquence, and status. Paul stopped them in their tracks with thirteen verses on true greatness.",
      },
      {
        id: "1c13-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q26.png",
        scriptureRef: "1 Corinthians 13:4–5",
        text: "“Love is patient, love is kind. It does not envy, it does not boast, it is not proud... It keeps no record of wrongs.”",
        spark: SPARKS_WEEK_4.agape,
      },
      {
        id: "1c13-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q26.png",
        scriptureRef: "1 Corinthians 13:8, 13",
        text: "“Love never fails... And now these three remain: faith, hope and love. But the greatest of these is love.”",
      },
      {
        id: "1c13-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q26.png",
        title: "The Portrait of Christ",
        text: "Substitute the name 'Jesus' wherever Paul writes 'love': Jesus is patient. Jesus is kind. Jesus keeps no record of wrongs. Love is not a sentiment; it is Christ Himself.",
      },
      {
        id: "1c13-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q26.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Greek word signifies unconditional, self-giving sacrificial love?",
          choices: ["Agape", "Chara", "Panoplia"],
          correctIndex: 0,
          explanation: "Agape is divine, unconditional love.",
        },
      },
    ],
  },

  // DAY 26: Ephesians 6
  {
    bookSlug: "ephesians",
    bookTitle: "Ephesians",
    chapterNumber: 6,
    dayNumber: 26,
    arcName: WEEK_4_ARC,
    title: "The Whole Armor of God",
    subtitle: "Spiritual warfare, standing firm, and the sword of the Spirit.",
    thematicHook: "'For our struggle is not against flesh and blood, but against the rulers, against the authorities, against the powers of this dark world.'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q27.png",
    coinsReward: 50,
    sparks: {
      panoplia: SPARKS_WEEK_4.panoplia,
    },
    verses: [
      { number: 10, text: "Finally, be strong in the Lord and in his mighty power." },
      { number: 11, text: "Put on the full armor of God, so that you can take your stand against the devil's schemes.", sparkIds: ["panoplia"] },
      { number: 12, text: "For our struggle is not against flesh and blood, but against the rulers, against the authorities, against the powers of this dark world and against the spiritual forces of evil in the heavenly realms." },
      { number: 14, text: "Stand firm then, with the belt of truth buckled around your waist, with the breastplate of righteousness in place," },
      { number: 15, text: "and with your feet fitted with the readiness that comes from the gospel of peace." },
      { number: 16, text: "In addition to all this, take up the shield of faith, with which you can extinguish all the flaming arrows of the evil one." },
      { number: 17, text: "Take the helmet of salvation and the sword of the Spirit, which is the word of God." },
    ],
    checkInQuestions: [
      {
        prompt: "Against whom does Paul declare our true struggle is waged in Ephesians 6:12?",
        choices: [
          "Against flesh and blood human enemies",
          "Against rulers, authorities, and spiritual powers of darkness in heavenly realms",
          "Against Roman magistrates only",
          "Against philosophical teachers",
        ],
        correctIndex: 1,
        explanation: "Ephesians 6:12 reminds us our battle is spiritual, requiring divine weaponry.",
      },
      {
        prompt: "What is the single offensive weapon listed in the armor of God?",
        choices: [
          "The spear of truth",
          "The sword of the Spirit, which is the Word of God",
          "The chariot of fire",
          "The bow of righteousness",
        ],
        correctIndex: 1,
        explanation: "The sword of the Spirit (the Word of God) is the active offensive instrument for spiritual victory.",
      },
      {
        prompt: "What does the shield of faith extinguish in Ephesians 6:16?",
        choices: [
          "All the flaming arrows of the evil one",
          "The sun's desert heat",
          "The words of detractors",
          "The swords of Rome",
        ],
        correctIndex: 0,
        explanation: "The large Roman-style shield (thureos) quenches fiery darts of doubt and temptation.",
      },
    ],
    storySlides: [
      {
        id: "eph6-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q27.png",
        badge: "Day 26 · The Armor",
        title: "The Invisible Battle",
        text: "Chained to a Roman guard day and night, Paul looked at the soldier’s gear and saw a picture of the believer’s spiritual defense.",
      },
      {
        id: "eph6-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q27.png",
        scriptureRef: "Ephesians 6:10–11",
        text: "“Be strong in the Lord and in His mighty power. Put on the full armor of God, so that you can take your stand against the devil’s schemes.”",
        spark: SPARKS_WEEK_4.panoplia,
      },
      {
        id: "eph6-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q27.png",
        scriptureRef: "Ephesians 6:16–17",
        text: "“Take up the shield of faith... and the sword of the Spirit, which is the Word of God.”",
      },
      {
        id: "eph6-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q27.png",
        title: "Standing Firm",
        text: "Notice that Paul does not command believers to advance and conquer new ground—Christ already conquered at the cross. We are commanded to stand firm in what He won.",
      },
      {
        id: "eph6-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q27.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Greek term denotes the full panoply / armor of God?",
          choices: ["Panoplia", "Kainos", "Hypomone"],
          correctIndex: 0,
          explanation: "Panoplia means the complete suit of spiritual armor.",
        },
      },
    ],
  },

  // DAY 27: Philippians 4
  {
    bookSlug: "philippians",
    bookTitle: "Philippians",
    chapterNumber: 4,
    dayNumber: 27,
    arcName: WEEK_4_ARC,
    title: "Peace That Surpasses Understanding",
    subtitle: "Joy in all circumstances, the secret of contentment, and strength in Christ.",
    thematicHook: "'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q28.png",
    coinsReward: 50,
    sparks: {
      chara: SPARKS_WEEK_4.chara,
    },
    verses: [
      { number: 4, text: "Rejoice in the Lord always. I will say it again: Rejoice!", sparkIds: ["chara"] },
      { number: 6, text: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God." },
      { number: 7, text: "And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus." },
      { number: 8, text: "Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable—if anything is excellent or praiseworthy—think about such things." },
      { number: 11, text: "I have learned to be content whatever the circumstances." },
      { number: 13, text: "I can do all this through him who gives me strength." },
      { number: 19, text: "And my God will meet all your needs according to the riches of his glory in Christ Jesus." },
    ],
    checkInQuestions: [
      {
        prompt: "What prescription does Paul give against anxiety in Philippians 4:6?",
        choices: [
          "Suppressing negative thoughts",
          "Prayer and petition with thanksgiving, presenting requests to God",
          "Working harder to solve the dilemma",
          "Consulting political authorities",
        ],
        correctIndex: 1,
        explanation: "Philippians 4:6 directs us to trade anxiety for prayer, supplication, and thanksgiving.",
      },
      {
        prompt: "What will the peace of God do for believers according to verse 7?",
        choices: [
          "Guard our hearts and minds in Christ Jesus",
          "Guarantee immunity from sickness",
          "Make us wealthy in Rome",
          "Prevent all future trials",
        ],
        correctIndex: 0,
        explanation: "The peace of God acts as a heavenly garrison guarding our thoughts and emotional core.",
      },
      {
        prompt: "What is the true context of Paul's declaration 'I can do all this through Him who gives me strength' (v. 13)?",
        choices: [
          "Winning athletic competitions",
          "Contentment in all circumstances—whether in plenty or in hunger",
          "Accumulating gold and land",
          "Building architectural monuments",
        ],
        correctIndex: 1,
        explanation: "Verses 11–12 show the secret is Christ-centered contentment through poverty or abundance.",
      },
    ],
    storySlides: [
      {
        id: "php4-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q28.png",
        badge: "Day 27 · Contentment",
        title: "The Epistle of Joy",
        text: "Writing from chains in a damp Roman cell, Paul pens the most radiant letter of joy ever written. True peace cannot be imprisoned.",
      },
      {
        id: "php4-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q28.png",
        scriptureRef: "Philippians 4:6–7",
        text: "“Do not be anxious about anything, but in every situation, by prayer and petition with thanksgiving, present your requests to God. And the peace of God will guard your hearts.”",
      },
      {
        id: "php4-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q28.png",
        scriptureRef: "Philippians 4:13",
        text: "“I can do all this through Him who gives me strength.”",
        spark: SPARKS_WEEK_4.chara,
      },
      {
        id: "php4-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q28.png",
        title: "The Garrison of Peace",
        text: "The Greek word for 'guard' is a military sentinel standing sentry at the city gate. God's peace posts a watch over your heart so worry cannot breach.",
      },
      {
        id: "php4-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q28.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Greek word for joy describes soul-anchored delight in God's grace?",
          choices: ["Chara", "Panoplia", "Makarios"],
          correctIndex: 0,
          explanation: "Chara is joy flowing directly from divine grace.",
        },
      },
    ],
  },

  // DAY 28: Hebrews 11
  {
    bookSlug: "hebrews",
    bookTitle: "Hebrews",
    chapterNumber: 11,
    dayNumber: 28,
    arcName: WEEK_4_ARC,
    title: "The Great Hall of Faith",
    subtitle: "The title deed of unseen realities and the cloud of witnesses.",
    thematicHook: "'Now faith is confidence in what we hope for and assurance about what we do not see. This is what the ancients were commended for.'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q29.png",
    coinsReward: 50,
    sparks: {
      hypostasis: SPARKS_WEEK_4.hypostasis,
    },
    verses: [
      { number: 1, text: "Now faith is confidence in what we hope for and assurance about what we do not see.", sparkIds: ["hypostasis"] },
      { number: 2, text: "This is what the ancients were commended for." },
      { number: 6, text: "And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him." },
      { number: 7, text: "By faith Noah, when warned about things not yet seen, in holy fear built an ark to save his family." },
      { number: 8, text: "By faith Abraham, when called to go to a place he would later receive as his inheritance, obeyed and went, even though he did not know where he was going." },
      { number: 13, text: "All these people were still living by faith when they died. They did not receive the things promised; they only saw them and welcomed them from a distance, admitting that they were foreigners and strangers on earth." },
      { number: 16, text: "Instead, they were longing for a better country—a heavenly one. Therefore God is not ashamed to be called their God, for he has prepared a city for them." },
    ],
    checkInQuestions: [
      {
        prompt: "How does Hebrews 11:1 define faith?",
        choices: [
          "Blind wishful thinking",
          "Confidence in what we hope for, assurance about what we do not see",
          "A philosophical exercise",
          "An inheritance from parents",
        ],
        correctIndex: 1,
        explanation: "Hebrews 11:1 defines faith as the solid substance (hypostasis) and evidence of unseen realities.",
      },
      {
        prompt: "Why is it impossible to please God without faith according to verse 6?",
        choices: [
          "Because God requires ritual sacrifices",
          "Because anyone who comes to Him must believe He exists and rewards those who seek Him",
          "Because angels demand proof",
          "Because faith replaces love",
        ],
        correctIndex: 1,
        explanation: "Hebrews 11:6 states faith is the indispensable posture: believing God is, and that He rewards earnest seekers.",
      },
      {
        prompt: "What were the patriarchs and matriarchs longing for according to verse 16?",
        choices: [
          "Return to the cities of Ur and Haran",
          "A better country—a heavenly one prepared by God",
          "Gold pyramids like Pharaoh",
          "Military mastery of Canaan",
        ],
        correctIndex: 1,
        explanation: "They recognized they were pilgrim foreigners, seeking an eternal city whose architect is God.",
      },
    ],
    storySlides: [
      {
        id: "heb11-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q29.png",
        badge: "Day 28 · The Hall of Faith",
        title: "The Cloud of Witnesses",
        text: "Abel, Enoch, Noah, Abraham, Sarah, Moses, Rahab, David... A grand gallery of pilgrims who marched into the unknown trusting a promise.",
      },
      {
        id: "heb11-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q29.png",
        scriptureRef: "Hebrews 11:1, 6",
        text: "“Now faith is confidence in what we hope for and assurance about what we do not see... Without faith it is impossible to please God.”",
        spark: SPARKS_WEEK_4.hypostasis,
      },
      {
        id: "heb11-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q29.png",
        scriptureRef: "Hebrews 11:16",
        text: "“They were longing for a better country—a heavenly one. Therefore God is not ashamed to be called their God, for He has prepared a city for them.”",
      },
      {
        id: "heb11-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q29.png",
        title: "The Title Deed",
        text: "Hypostasis was the ancient title deed. When you hold the deed, the house is legally yours even before you step across the threshold. Faith is our title deed to eternity.",
      },
      {
        id: "heb11-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q29.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Greek term in Hebrews 11 signifies the foundational substance and title deed of faith?",
          choices: ["Hypostasis", "Koinonia", "Logos"],
          correctIndex: 0,
          explanation: "Hypostasis represents solid underlying assurance and title deed.",
        },
      },
    ],
  },

  // DAY 29: James 1
  {
    bookSlug: "james",
    bookTitle: "James",
    chapterNumber: 1,
    dayNumber: 29,
    arcName: WEEK_4_ARC,
    title: "Faith in Action & Steadfast Endurance",
    subtitle: "Counting trials as joy, asking for wisdom without wavering, and being doers of the Word.",
    thematicHook: "'Do not merely listen to the word, and so deceive yourselves. Do what it says. Anyone who listens to the word but does not do what it says is like someone who looks at his face in a mirror and immediately forgets.'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q2.png",
    coinsReward: 50,
    sparks: {
      hypomone: SPARKS_WEEK_4.hypomone,
    },
    verses: [
      { number: 2, text: "Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds," },
      { number: 3, text: "because you know that the testing of your faith produces perseverance.", sparkIds: ["hypomone"] },
      { number: 4, text: "Let perseverance finish its work so that you may be mature and complete, not lacking anything." },
      { number: 5, text: "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you." },
      { number: 12, text: "Blessed is the one who perseveres under trial because, having stood the test, that person will receive the crown of life that the Lord has promised to those who love him." },
      { number: 17, text: "Every good and perfect gift is from above, coming down from the Father of the heavenly lights, who does not change like shifting shadows." },
      { number: 22, text: "Do not merely listen to the word, and so deceive yourselves. Do what it says." },
      { number: 27, text: "Religion that God our Father accepts as pure and faultless is this: to look after orphans and widows in their distress and to keep oneself from being polluted by the world." },
    ],
    checkInQuestions: [
      {
        prompt: "Why does James instruct believers to consider trials 'pure joy' in verses 2–3?",
        choices: [
          "Because pain is pleasant",
          "Because the testing of faith produces perseverance (hypomonē)",
          "To ignore reality",
          "To boast in front of enemies",
        ],
        correctIndex: 1,
        explanation: "The testing of faith builds steadfast endurance and spiritual maturity.",
      },
      {
        prompt: "According to James 1:5, what should someone lacking wisdom do?",
        choices: [
          "Study worldly philosophy alone",
          "Ask God, who gives generously to all without finding fault",
          "Give up trying to understand",
          "Rely entirely on chance",
        ],
        correctIndex: 1,
        explanation: "God gives wisdom generously to those who ask in faith without wavering.",
      },
      {
        prompt: "What metaphor does James use in verses 23–24 for someone who hears the Word but does not do it?",
        choices: [
          "A ship without a rudder",
          "A person who looks in a mirror and immediately forgets what they look like",
          "A withered vine",
          "A broken amphora",
        ],
        correctIndex: 1,
        explanation: "Hearing without doing is like glancing at oneself in a mirror and forgetting your true identity.",
      },
    ],
    storySlides: [
      {
        id: "jas1-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q2.png",
        badge: "Day 29 · Faith in Action",
        title: "The Crucible of Joy",
        text: "Trials are not interruptions to your spiritual journey; they are the workshop where steadfast character (hypomonē) is forged under pressure.",
      },
      {
        id: "jas1-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q2.png",
        scriptureRef: "James 1:2–3",
        text: "“Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance.”",
        spark: SPARKS_WEEK_4.hypomone,
      },
      {
        id: "jas1-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q2.png",
        scriptureRef: "James 1:22",
        text: "“Do not merely listen to the word, and so deceive yourselves. Do what it says.”",
      },
      {
        id: "jas1-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q2.png",
        title: "The Mirror and the Deeds",
        text: "Scripture is a living mirror showing who we truly are in God. True religion is active compassion: caring for the vulnerable and standing uncompromised.",
      },
      {
        id: "jas1-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q2.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Greek word for steadfast endurance under trial is emphasized in James 1?",
          choices: ["Hypomonē", "Phronesis", "Gnosis"],
          correctIndex: 0,
          explanation: "Hypomonē is active, resilient staying power under pressure.",
        },
      },
    ],
  },

  // DAY 30: Revelation 21
  {
    bookSlug: "revelation",
    bookTitle: "Revelation",
    chapterNumber: 21,
    dayNumber: 30,
    arcName: WEEK_4_ARC,
    title: "The New Jerusalem & Final Restoration",
    subtitle: "All tears wiped away, death swallowed in victory, and God dwelling with humanity forever.",
    thematicHook: "'He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away.'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q30.png",
    coinsReward: 100, // 30-Day Completion Bonus!
    sparks: {
      kainos: SPARKS_WEEK_4.kainos,
    },
    verses: [
      { number: 1, text: "Then I saw a new heaven and a new earth, for the first heaven and the first earth had passed away, and there was no longer any sea.", sparkIds: ["kainos"] },
      { number: 2, text: "I saw the Holy City, the new Jerusalem, coming down out of heaven from God, prepared as a bride beautifully dressed for her husband." },
      { number: 3, text: "And I heard a loud voice from the throne saying, 'Look! God's dwelling place is now among the people, and he will dwell with them. They will be his people, and God himself will be with them and be their God.'" },
      { number: 4, text: "'He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away.'" },
      { number: 5, text: "He who was seated on the throne said, 'I am making everything new!' Then he said, 'Write this down, for these words are trustworthy and true.'" },
      { number: 6, text: "He said to me: 'It is done. I am the Alpha and the Omega, the Beginning and the End. To the thirsty I will give water without cost from the spring of the water of life.'" },
      { number: 23, text: "The city does not need the sun or the moon to shine on it, for the glory of God gives it light, and the Lamb is its lamp." },
    ],
    checkInQuestions: [
      {
        prompt: "What will God personally wipe away from every eye in Revelation 21:4?",
        choices: ["Every tear", "Dust from the desert", "Traces of sweat", "The memory of names"],
        correctIndex: 0,
        explanation: "Revelation 21:4 contains one of the most tender promises in all Scripture: God wipes every tear away.",
      },
      {
        prompt: "What does the voice from the throne declare regarding God's dwelling in verse 3?",
        choices: [
          "God has retired to the third heaven",
          "God's dwelling place is now with humanity, and He will live with them",
          "Humanity must build a stone temple in space",
          "Only angels may enter the throne room",
        ],
        correctIndex: 1,
        explanation: "The grand goal of the entire biblical narrative: God dwelling in intimate, unhindered communion with redeemed humanity.",
      },
      {
        prompt: "Why does the Holy City have no need for sun or moon in verse 23?",
        choices: [
          "The stars are twice as bright",
          "For the glory of God gives it light, and the Lamb is its lamp",
          "Torches burn along every pearl gate",
          "It is illuminated by comets",
        ],
        correctIndex: 1,
        explanation: "The uncreated glory of God and the Lamb illuminates the New Jerusalem—the eternal Lampstand.",
      },
    ],
    storySlides: [
      {
        id: "rev21-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q30.png",
        badge: "Day 30 · Course Grand Finale",
        title: "The Destination",
        text: "The story that began in Genesis in a garden arrives at its celestial consummation: a holy city, a redeemed bride, and Paradise restored.",
      },
      {
        id: "rev21-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q30.png",
        scriptureRef: "Revelation 21:3–4",
        text: "“'God’s dwelling place is now with man... He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain.'”",
      },
      {
        id: "rev21-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q30.png",
        scriptureRef: "Revelation 21:5, 23",
        text: "“He who was seated on the throne said: 'Behold, I make all things new!'... For the glory of God gives it light, and the Lamb is its lamp.”",
        spark: SPARKS_WEEK_4.kainos,
      },
      {
        id: "rev21-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q30.png",
        title: "The Lamb is the Lamp",
        text: "From the first 'Let there be light' in Genesis 1 to the Lamb lighting the New Jerusalem in Revelation 21, the scarlet thread of redemption is complete.",
      },
      {
        id: "rev21-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q30.png",
        title: "30-Day Course Milestone!",
        text: "You have completed the 30-Day Anchors of Scripture course:",
        question: {
          prompt: "What Greek word for 'new in quality and nature' describes God making all things brand new?",
          choices: ["Kainos", "Logos", "Hypostasis"],
          correctIndex: 0,
          explanation: "Kainos describes the glorious, fresh new creation of God.",
        },
      },
    ],
  },
];
