import type { Chapter, WordSpark } from "../types";

export const WEEK_3_ARC = "Week 3: The Living Word & The Risen Christ";

export const SPARKS_WEEK_3: Record<string, WordSpark> = {
  logos: {
    id: "logos",
    term: "Word / Cosmic Reason",
    language: "Greek",
    originalScript: "λόγος",
    transliteration: "logos",
    rootMeaning: "divine utterance, principle of cosmic order and truth",
    culturalInsight:
      "Greek philosophers used 'Logos' for the abstract force holding the universe together. John boldly declares this principle is not an abstract theory, but a Person—Jesus Christ.",
  },
  skenoo: {
    id: "skenoo",
    term: "dwelt among us",
    language: "Greek",
    originalScript: "ἐσκήνωσεν",
    transliteration: "eskēnōsen",
    rootMeaning: "pitched His tent, tabernacled",
    culturalInsight:
      "A direct allusion to the wilderness Tabernacle where God's Shekinah glory rested. In Christ, the transcendent Creator pitched His tent among ordinary human flesh.",
  },
  makarios: {
    id: "makarios",
    term: "blessed / deeply satisfied",
    language: "Greek",
    originalScript: "μακάριος",
    transliteration: "makarios",
    rootMeaning: "supremely happy, spiritually whole, favored by heaven",
    culturalInsight:
      "In the Greco-Roman world, happiness depended on wealth and power. Jesus inverts the cosmos: true heaven-approved joy belongs to the poor in spirit and pure in heart.",
  },
  pleroo: {
    id: "pleroo",
    term: "fulfill",
    language: "Greek",
    originalScript: "πληρόω",
    transliteration: "plēroō",
    rootMeaning: "to fill to the brim, bring to completion and full design",
    culturalInsight:
      "Jesus did not come to discard the Old Testament law, but to 'fill it to the full'—perfecting its moral intent through sacrificial love.",
  },
  abba: {
    id: "abba",
    term: "Father",
    language: "Aramaic",
    originalScript: "אַבָּא",
    transliteration: "’abbā’",
    rootMeaning: "intimate, affectionate familial term for Father",
    culturalInsight:
      "Jewish rabbis rarely if ever addressed the Almighty as 'Abba'. Jesus invited His disciples into startling familial intimacy with the Creator of galaxies.",
  },
  splagchnizomai: {
    id: "splagchnizomai",
    term: "moved with deep compassion",
    language: "Greek",
    originalScript: "σπλαγχνίζομαι",
    transliteration: "splagchnizomai",
    rootMeaning: "visceral yearning in one's deepest core / guts",
    culturalInsight:
      "In ancient thought, intense emotions originated in the bowels. When the father saw the prodigal returning, he was shaken to his deepest core with visceral pity.",
  },
  parakletos: {
    id: "parakletos",
    term: "Advocate / Comforter",
    language: "Greek",
    originalScript: "παράκλητος",
    transliteration: "paraklētos",
    rootMeaning: "one called alongside to defend, comfort, and counsel",
    culturalInsight:
      "In Roman legal courts, a parakletos was the defense advocate standing beside an accused person. Jesus promised the Holy Spirit as our permanent divine Helper.",
  },
  diermeneuo: {
    id: "diermeneuo",
    term: "explained / unfolded",
    language: "Greek",
    originalScript: "διερμηνεύω",
    transliteration: "diermēneuō",
    rootMeaning: "to thoroughly interpret and unlock meaning",
    culturalInsight:
      "On the road to Emmaus, Jesus showed how every strand of Moses, the Prophets, and the Psalms converged upon His suffering and resurrection glory.",
  },
  rabboni: {
    id: "rabboni",
    term: "Master / Teacher",
    language: "Aramaic",
    originalScript: "ῥαββουνί",
    transliteration: "rhabbouni",
    rootMeaning: "my highest master, my esteemed teacher",
    culturalInsight:
      "Mary Magdalene's joyful recognition outside the empty tomb. An intensified honorific expressing tender devotion to her living Lord.",
  },
};

export const WEEK_3_CHAPTERS: Chapter[] = [
  // DAY 15: John 1
  {
    bookSlug: "john",
    bookTitle: "John",
    chapterNumber: 1,
    dayNumber: 15,
    arcName: WEEK_3_ARC,
    title: "The Word Made Flesh",
    subtitle: "The sublime cosmic prologue of the Incarnation and uncreated Light.",
    thematicHook: "Before the cosmos was born, the Word was with God, and the Word was God. Then, the impossible happened: He pitched His tent among us.",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q16.png",
    coinsReward: 50,
    sparks: {
      logos: SPARKS_WEEK_3.logos,
      skenoo: SPARKS_WEEK_3.skenoo,
    },
    verses: [
      { number: 1, text: "In the beginning was the Word, and the Word was with God, and the Word was God.", sparkIds: ["logos"] },
      { number: 2, text: "He was with God in the beginning." },
      { number: 3, text: "Through him all things were made; without him nothing was made that has been made." },
      { number: 4, text: "In him was life, and that life was the light of all mankind." },
      { number: 5, text: "The light shines in the darkness, and the darkness has not overcome it." },
      { number: 12, text: "Yet to all who did receive him, to those who believed in his name, he gave the right to become children of God—" },
      { number: 14, text: "The Word became flesh and made his dwelling among us. We have seen his glory, the glory of the one and only Son, who came from the Father, full of grace and truth.", sparkIds: ["skenoo"] },
      { number: 17, text: "For the law was given through Moses; grace and truth came through Jesus Christ." },
    ],
    checkInQuestions: [
      {
        prompt: "What profound claim does John 1:1 make concerning the Word (Logos)?",
        choices: [
          "The Word was created by angels",
          "The Word was with God, and the Word was God",
          "The Word began at Mount Sinai",
          "The Word is an impersonal rule",
        ],
        correctIndex: 1,
        explanation: "John 1:1 establishes the eternal deity of Christ: He was with God and He was God.",
      },
      {
        prompt: "According to John 1:5, what power does darkness have over the light?",
        choices: [
          "Darkness will eventually extinguish the light",
          "The darkness has not overcome it",
          "They are equal opposing forces",
          "Darkness existed before the light",
        ],
        correctIndex: 1,
        explanation: "The Light shines into darkness, and the darkness cannot extinguish or comprehend it.",
      },
      {
        prompt: "What Greek verb in verse 14 means the Word 'pitched His tent' or tabernacled among us?",
        choices: ["Skenoo", "Logos", "Bara", "Makarios"],
        correctIndex: 0,
        explanation: "Skenoo directly evokes the wilderness Tabernacle where God's Shekinah glory dwelt.",
      },
    ],
    storySlides: [
      {
        id: "jn1-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q16.png",
        badge: "Day 15 · The Incarnation",
        title: "The Uncreated Word",
        text: "John echoes the opening chords of Genesis. But where Moses spoke of the universe's dawn, John unveils the Person through whom all things came to be.",
      },
      {
        id: "jn1-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q16.png",
        scriptureRef: "John 1:1, 4",
        text: "“In the beginning was the Word, and the Word was with God, and the Word was God... In Him was life, and that life was the light of all mankind.”",
        spark: SPARKS_WEEK_3.logos,
      },
      {
        id: "jn1-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q16.png",
        scriptureRef: "John 1:14",
        text: "“The Word became flesh and made His dwelling among us. We have seen His glory, full of grace and truth.”",
        spark: SPARKS_WEEK_3.skenoo,
      },
      {
        id: "jn1-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q16.png",
        title: "Grace Upon Grace",
        text: "The law came through Moses carved in stone. In Christ, God’s heartbeat—grace coupled with unwavering truth—walked in the dust of our world.",
      },
      {
        id: "jn1-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q16.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Greek term for divine utterance and cosmic truth identifies Jesus in John 1?",
          choices: ["Logos", "Makarios", "Parakletos"],
          correctIndex: 0,
          explanation: "Logos is the eternal Word of God.",
        },
      },
    ],
  },

  // DAY 16: Matthew 5
  {
    bookSlug: "matthew",
    bookTitle: "Matthew",
    chapterNumber: 5,
    dayNumber: 16,
    arcName: WEEK_3_ARC,
    title: "The Sermon on the Mount & Beatitudes",
    subtitle: "The constitution of the Kingdom of God and the heart of true righteousness.",
    thematicHook: "Sitting on the Galilean hillside, Jesus turns earthly hierarchies upside down: the meek inherit the earth, and the peacemakers are called sons of God.",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q17.png",
    coinsReward: 50,
    sparks: {
      makarios: SPARKS_WEEK_3.makarios,
      pleroo: SPARKS_WEEK_3.pleroo,
    },
    verses: [
      { number: 3, text: "'Blessed are the poor in spirit, for theirs is the kingdom of heaven.'", sparkIds: ["makarios"] },
      { number: 4, text: "'Blessed are those who mourn, for they will be comforted.'" },
      { number: 5, text: "'Blessed are the meek, for they will inherit the earth.'" },
      { number: 6, text: "'Blessed are those who hunger and thirst for righteousness, for they will be filled.'" },
      { number: 7, text: "'Blessed are the merciful, for they will be shown mercy.'" },
      { number: 8, text: "'Blessed are the pure in heart, for they will see God.'" },
      { number: 9, text: "'Blessed are the peacemakers, for they will be called children of God.'" },
      { number: 14, text: "'You are the light of the world. A town built on a hill cannot be hidden.'" },
      { number: 16, text: "'In the same way, let your light shine before others, that they may see your good deeds and glorify your Father in heaven.'" },
      { number: 17, text: "'Do not think that I have come to abolish the Law or the Prophets; I have not come to abolish them but to fulfill them.'", sparkIds: ["pleroo"] },
    ],
    checkInQuestions: [
      {
        prompt: "What belongs to the 'poor in spirit' according to the first Beatitude?",
        choices: ["The treasures of Rome", "The kingdom of heaven", "Exemption from suffering", "Authority over kings"],
        correctIndex: 1,
        explanation: "Matthew 5:3 promises that recognizing our spiritual poverty opens the riches of the kingdom of heaven.",
      },
      {
        prompt: "What will the meek inherit according to Jesus in Matthew 5:5?",
        choices: ["The earth", "The gold of Ophir", "The high priesthood", "The admiration of men"],
        correctIndex: 0,
        explanation: "In contrast to worldly conquest, Jesus teaches that the gentle and meek will inherit the earth.",
      },
      {
        prompt: "Did Jesus come to abolish the Law and the Prophets?",
        choices: [
          "Yes, to discard them completely",
          "No, but to fulfill (pleroo) them to the full",
          "Only the writings of Solomon",
          "Only the ceremonies of the temple",
        ],
        correctIndex: 1,
        explanation: "Matthew 5:17 states Jesus came to bring the Law and Prophets to complete fruition and fulfillment.",
      },
    ],
    storySlides: [
      {
        id: "mt5-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q17.png",
        badge: "Day 16 · The Mount",
        title: "The Inverted Kingdom",
        text: "On a gentle hillside overlooking the Sea of Galilee, a carpenter’s son spoke words that upended every human empire.",
      },
      {
        id: "mt5-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q17.png",
        scriptureRef: "Matthew 5:3, 8",
        text: "“Blessed are the poor in spirit, for theirs is the kingdom of heaven... Blessed are the pure in heart, for they will see God.”",
        spark: SPARKS_WEEK_3.makarios,
      },
      {
        id: "mt5-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q17.png",
        scriptureRef: "Matthew 5:14, 16",
        text: "“You are the light of the world. Let your light shine before others, that they may see your good deeds and glorify your Father in heaven.”",
      },
      {
        id: "mt5-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q17.png",
        title: "Fulfilling the Heart of the Law",
        text: "Righteousness in Christ’s kingdom is not an outward mask of rules, but an inner transformation where love replaces anger and purity replaces lust.",
        spark: SPARKS_WEEK_3.pleroo,
      },
      {
        id: "mt5-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q17.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Greek word used throughout the Beatitudes means 'blessed, favored, deeply satisfied'?",
          choices: ["Makarios", "Logos", "Skenoo"],
          correctIndex: 0,
          explanation: "Makarios describes heavenly, unshakeable blessedness.",
        },
      },
    ],
  },

  // DAY 17: Matthew 6
  {
    bookSlug: "matthew",
    bookTitle: "Matthew",
    chapterNumber: 6,
    dayNumber: 17,
    arcName: WEEK_3_ARC,
    title: "The Lord's Prayer & Heavenly Treasure",
    subtitle: "Secret prayer, the pattern of intimacy, and freedom from anxious care.",
    thematicHook: "'Look at the birds of the air: they do not sow or reap, yet your heavenly Father feeds them. Are you not much more valuable than they?'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q18.png",
    coinsReward: 50,
    sparks: {
      abba: SPARKS_WEEK_3.abba,
    },
    verses: [
      { number: 6, text: "'When you pray, go into your room, close the door and pray to your Father, who is unseen. Then your Father, who sees what is done in secret, will reward you.'" },
      { number: 9, text: "'This, then, is how you should pray: Our Father in heaven, hallowed be your name,'", sparkIds: ["abba"] },
      { number: 10, text: "'your kingdom come, your will be done, on earth as it is in heaven.'" },
      { number: 11, text: "'Give us today our daily bread.'" },
      { number: 12, text: "'And forgive us our debts, as we also have forgiven our debtors.'" },
      { number: 13, text: "'And lead us not into temptation, but deliver us from the evil one.'" },
      { number: 25, text: "'Therefore I tell you, do not worry about your life, what you will eat or drink; or about your body, what you will wear. Is not life more than food, and the body more than clothes?'" },
      { number: 33, text: "'But seek first his kingdom and his righteousness, and all these things will be given to you as well.'" },
    ],
    checkInQuestions: [
      {
        prompt: "Where does Jesus instruct His followers to go when they pray in Matthew 6:6?",
        choices: ["To the street corners", "Into your room with the door closed in secret", "Before the Roman governor", "Into the marketplace"],
        correctIndex: 1,
        explanation: "True communion with God thrives in secret sincerity, away from the performance of hypocrites.",
      },
      {
        prompt: "What priority is commanded above all anxiety in Matthew 6:33?",
        choices: [
          "Building barns of grain",
          "Seeking first the kingdom of God and His righteousness",
          "Learning political diplomacy",
          "Securing gold reserves",
        ],
        correctIndex: 1,
        explanation: "Jesus promises that when we seek God's kingdom first, all earthly provisions follow.",
      },
      {
        prompt: "What conditional petition is embedded in the Lord's Prayer regarding forgiveness?",
        choices: [
          "'Forgive us our debts, as we also have forgiven our debtors'",
          "'Forgive us if we pay the temple tax'",
          "'Forgive only those who are related to us'",
          "'Forgive without changing our hearts'",
        ],
        correctIndex: 0,
        explanation: "Jesus links receiving divine forgiveness with our willingness to forgive those who trespass against us.",
      },
    ],
    storySlides: [
      {
        id: "mt6-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q18.png",
        badge: "Day 17 · The Secret Place",
        title: "The Heart at Rest",
        text: "The world prays to be seen by men, and frets endlessly about food, clothing, and tomorrow. Jesus invites us into quiet, fearless sonship.",
      },
      {
        id: "mt6-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q18.png",
        scriptureRef: "Matthew 6:9–10",
        text: "“Our Father in heaven, hallowed be Your name, Your kingdom come, Your will be done, on earth as it is in heaven.”",
        spark: SPARKS_WEEK_3.abba,
      },
      {
        id: "mt6-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q18.png",
        scriptureRef: "Matthew 6:33",
        text: "“Seek first His kingdom and His righteousness, and all these things will be given to you as well.”",
      },
      {
        id: "mt6-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q18.png",
        title: "Consider the Lilies",
        text: "Solomon in all his splendor was not clothed like a wildflower of the field. If God clothes the grass of today, how much more will He care for you?",
      },
      {
        id: "mt6-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q18.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Aramaic word for 'Father' conveys the tender familial intimacy Jesus revealed?",
          choices: ["Abba", "Bara", "Makarios"],
          correctIndex: 0,
          explanation: "Abba expresses warm, tender filial intimacy with God.",
        },
      },
    ],
  },

  // DAY 18: Luke 15
  {
    bookSlug: "luke",
    bookTitle: "Luke",
    chapterNumber: 15,
    dayNumber: 18,
    arcName: WEEK_3_ARC,
    title: "The Prodigal Son & The Father's Heart",
    subtitle: "A lost sheep, a lost coin, and a reckless father running to embrace a broken son.",
    thematicHook: "'While he was still a long way off, his father saw him and was filled with compassion; he ran to his son, threw his arms around him and kissed him.'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q19.png",
    coinsReward: 50,
    sparks: {
      splagchnizomai: SPARKS_WEEK_3.splagchnizomai,
    },
    verses: [
      { number: 11, text: "Jesus continued: 'There was a man who had two sons.'" },
      { number: 13, text: "'Not long after that, the younger son got together all he had, set off for a distant country and there squandered his wealth in wild living.'" },
      { number: 17, text: "'When he came to his senses, he said, How many of my father's hired servants have food to spare, and here I am starving to death!'" },
      { number: 20, text: "'So he got up and went to his father. But while he was still a long way off, his father saw him and was filled with compassion; he ran to his son, threw his arms around him and kissed him.'", sparkIds: ["splagchnizomai"] },
      { number: 22, text: "'But the father said to his servants, Quick! Bring the best robe and put it on him. Put a ring on his finger and sandals on his feet.'" },
      { number: 24, text: "'For this son of mine was dead and is alive again; he was lost and is found. So they began to celebrate.'" },
    ],
    checkInQuestions: [
      {
        prompt: "What did the younger son yearn to eat while feeding pigs in the distant country?",
        choices: ["The wheat bread of Egypt", "The carob pods the pigs were eating", "Dates from the palms", "Wild honey"],
        correctIndex: 1,
        explanation: "Luke 15:16 shows the depths of his destitution: he longed to fill his stomach with pig pods.",
      },
      {
        prompt: "What did the father do when he saw his returning son from a long way off?",
        choices: [
          "He stood by the gate demanding an apology",
          "He was moved with compassion, ran, threw his arms around him, and kissed him",
          "He sent his servants with a bill for the squandered inheritance",
          "He turned inside and closed the doors",
        ],
        correctIndex: 1,
        explanation: "In Middle Eastern culture, patriarchal elders never ran. The father threw off dignity in ecstatic love.",
      },
      {
        prompt: "What three items did the father command to be placed on the restored son?",
        choices: [
          "The best robe, a ring, and sandals",
          "A yoke, a staff, and an apron",
          "A bag of silver, a cloak, and a scroll",
          "A crown, a spear, and armor",
        ],
        correctIndex: 0,
        explanation: "The robe signified honor, the ring restored sonship authority, and sandals marked him as a free son rather than a barefoot slave.",
      },
    ],
    storySlides: [
      {
        id: "lk15-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q19.png",
        badge: "Day 18 · The Prodigal",
        title: "The Far Country",
        text: "Taking his inheritance early—effectively wishing his father dead—the younger son journeyed into darkness until only pig slop remained.",
      },
      {
        id: "lk15-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q19.png",
        scriptureRef: "Luke 15:20",
        text: "“While he was still a long way off, his father saw him and was filled with compassion; he ran to his son, threw his arms around him and kissed him.”",
        spark: SPARKS_WEEK_3.splagchnizomai,
      },
      {
        id: "lk15-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q19.png",
        scriptureRef: "Luke 15:24",
        text: "“'For this son of mine was dead and is alive again; he was lost and is found.' And they began to celebrate.”",
      },
      {
        id: "lk15-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q19.png",
        title: "The Running Father",
        text: "Dignified Middle Eastern elders did not run. But the father gathered his robes and raced down the dusty road, absorbing the son’s shame before the village could cast stones.",
      },
      {
        id: "lk15-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q19.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Greek verb expresses the father's visceral, gut-wrenching compassion for the son?",
          choices: ["Splagchnizomai", "Plēroō", "Paraklētos"],
          correctIndex: 0,
          explanation: "Splagchnizomai denotes deep, visceral compassion.",
        },
      },
    ],
  },

  // DAY 19: John 14
  {
    bookSlug: "john",
    bookTitle: "John",
    chapterNumber: 14,
    dayNumber: 19,
    arcName: WEEK_3_ARC,
    title: "The Way, the Truth, and the Life",
    subtitle: "The Upper Room discourse, peace not as the world gives, and the promised Advocate.",
    thematicHook: "'Do not let your hearts be troubled. You believe in God; believe also in me... I will not leave you as orphans; I will come to you.'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q20.png",
    coinsReward: 50,
    sparks: {
      parakletos: SPARKS_WEEK_3.parakletos,
    },
    verses: [
      { number: 1, text: "'Do not let your hearts be troubled. You believe in God; believe also in me.'" },
      { number: 2, text: "'My Father's house has many rooms; if that were not so, would I have told you that I am going there to prepare a place for you?'" },
      { number: 6, text: "Jesus answered, 'I am the way and the truth and the life. No one comes to the Father except through me.'" },
      { number: 16, text: "'And I will ask the Father, and he will give you another advocate to help you and be with you forever—'", sparkIds: ["parakletos"] },
      { number: 17, text: "'the Spirit of truth. The world cannot accept him, because it neither sees him nor knows him. But you know him, for he lives with you and will be in you.'" },
      { number: 27, text: "'Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.'" },
    ],
    checkInQuestions: [
      {
        prompt: "What threefold declaration does Jesus make about Himself in John 14:6?",
        choices: [
          "'I am the prophet, the teacher, and the guide'",
          "'I am the way and the truth and the life'",
          "'I am the builder, the pillar, and the roof'",
          "'I am the lawgiver and the judge'",
        ],
        correctIndex: 1,
        explanation: "John 14:6 is one of Jesus's definitive 'I AM' statements: 'I am the way and the truth and the life.'",
      },
      {
        prompt: "Who did Jesus promise the Father would send as an Advocate (Parakletos) to dwell within believers?",
        choices: ["The Archangel Gabriel", "Moses and Elijah", "The Spirit of Truth (Holy Spirit)", "The kings of the east"],
        correctIndex: 2,
        explanation: "Jesus promised the Holy Spirit as another Advocate to abide with and live within us forever.",
      },
      {
        prompt: "How does the peace Jesus gives differ from the world's peace in verse 27?",
        choices: [
          "It depends on military alliances",
          "It is given not as the world gives, overcoming troubled hearts",
          "It guarantees temporal wealth",
          "It lasts only during good health",
        ],
        correctIndex: 1,
        explanation: "Worldly peace is circumstantial; Christ's peace is an anchor in the midst of storms.",
      },
    ],
    storySlides: [
      {
        id: "jn14-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q20.png",
        badge: "Day 19 · The Upper Room",
        title: "The Night of Parting",
        text: "Hours before the cross, in the quiet glow of the Upper Room, Jesus looked into the anxious eyes of His disciples and gave them His peace.",
      },
      {
        id: "jn14-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q20.png",
        scriptureRef: "John 14:6",
        text: "“Jesus answered: 'I am the way and the truth and the life. No one comes to the Father except through Me.'”",
      },
      {
        id: "jn14-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q20.png",
        scriptureRef: "John 14:16, 27",
        text: "“I will ask the Father, and He will give you another Advocate to be with you forever... Peace I leave with you; My peace I give you.”",
        spark: SPARKS_WEEK_3.parakletos,
      },
      {
        id: "jn14-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q20.png",
        title: "Never Left as Orphans",
        text: "The Parakletos is the divine Counselor called alongside to guide, comfort, and empower us through every valley.",
      },
      {
        id: "jn14-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q20.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Greek title for the Holy Spirit means Advocate, Counselor, and Comforter?",
          choices: ["Parakletos", "Logos", "Skenoo"],
          correctIndex: 0,
          explanation: "Parakletos is the divine Advocate called alongside.",
        },
      },
    ],
  },

  // DAY 20: Luke 24
  {
    bookSlug: "luke",
    bookTitle: "Luke",
    chapterNumber: 24,
    dayNumber: 20,
    arcName: WEEK_3_ARC,
    title: "The Emmaus Road & Scriptures Opened",
    subtitle: "Two downcast disciples, an unrecognized Stranger, and hearts burning within.",
    thematicHook: "'Were not our hearts burning within us while he talked with us on the road and opened the Scriptures to us?'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q21.png",
    coinsReward: 50,
    sparks: {
      diermeneuo: SPARKS_WEEK_3.diermeneuo,
    },
    verses: [
      { number: 13, text: "Now that same day two of them were going to a village called Emmaus, about seven miles from Jerusalem." },
      { number: 15, text: "As they talked and discussed these things with each other, Jesus himself came up and walked along with them;" },
      { number: 16, text: "but they were kept from recognizing him." },
      { number: 27, text: "And beginning with Moses and all the Prophets, he explained to them what was said in all the Scriptures concerning himself.", sparkIds: ["diermeneuo"] },
      { number: 30, text: "When he was at the table with them, he took bread, gave thanks, broke it and began to give it to them." },
      { number: 31, text: "Then their eyes were opened and they recognized him, and he disappeared from their sight." },
      { number: 32, text: "They asked each other, 'Were not our hearts burning within us while he talked with us on the road and opened the Scriptures to us?'" },
    ],
    checkInQuestions: [
      {
        prompt: "From where did Jesus begin when interpreting all the Scriptures concerning Himself on the road?",
        choices: ["From Roman historical records", "Beginning with Moses and all the Prophets", "From Greek poems", "From the Talmud"],
        correctIndex: 1,
        explanation: "Luke 24:27 states Jesus began with Moses and all the Prophets, showing the entire Old Testament pointed to Him.",
      },
      {
        prompt: "At what moment were the disciples' eyes opened to recognize Jesus?",
        choices: [
          "When He performed a miracle at the city gate",
          "When He took bread, blessed, broke it, and gave it to them",
          "When they looked at His sandals",
          "When a rooster crowed",
        ],
        correctIndex: 1,
        explanation: "In the breaking of the bread, their eyes were unblinded and they recognized the risen Master.",
      },
      {
        prompt: "What sensation did Cleopas and his companion recall experiencing while Jesus spoke on the road?",
        choices: [
          "Cold chills of fear",
          "Their hearts burning within them as He opened the Scriptures",
          "Drowsy exhaustion",
          "Confusion and grief",
        ],
        correctIndex: 1,
        explanation: "Their hearts burned with divine illumination as Scripture converged on Christ.",
      },
    ],
    storySlides: [
      {
        id: "lk24-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q21.png",
        badge: "Day 20 · The Emmaus Walk",
        title: "The Dusty Road",
        text: "Grief-stricken by the crucifixion, two disciples walk seven miles away from Jerusalem. A stranger falls into step beside them.",
      },
      {
        id: "lk24-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q21.png",
        scriptureRef: "Luke 24:27",
        text: "“And beginning with Moses and all the Prophets, He explained to them what was said in all the Scriptures concerning Himself.”",
        spark: SPARKS_WEEK_3.diermeneuo,
      },
      {
        id: "lk24-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q21.png",
        scriptureRef: "Luke 24:30–32",
        text: "“When He broke the bread, their eyes were opened... They asked: 'Were not our hearts burning within us while He opened the Scriptures?'”",
      },
      {
        id: "lk24-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q21.png",
        title: "The Key to the Text",
        text: "Jesus is the interpretive key to the entire Bible. From Genesis 1 to Malachi, every altar, prophet, and covenant finds its destination in Him.",
      },
      {
        id: "lk24-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q21.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Greek verb describes Jesus unlocking and thoroughly explaining the Scriptures?",
          choices: ["Diermēneuō", "Makarios", "Plēroō"],
          correctIndex: 0,
          explanation: "Diermēneuō means to thoroughly interpret and unlock meaning.",
        },
      },
    ],
  },

  // DAY 21: John 20
  {
    bookSlug: "john",
    bookTitle: "John",
    chapterNumber: 20,
    dayNumber: 21,
    arcName: WEEK_3_ARC,
    title: "The Empty Tomb & The Risen Lord",
    subtitle: "A stone rolled away, graveclothes folded, and the dawn of the new creation.",
    thematicHook: "'Woman, why are you crying? Who is it you are looking for?' Thinking he was the gardener, she said: 'Sir, if you have carried him away, tell me...' Jesus said to her, 'Mary.'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q22.png",
    coinsReward: 50,
    sparks: {
      rabboni: SPARKS_WEEK_3.rabboni,
    },
    verses: [
      { number: 1, text: "Early on the first day of the week, while it was still dark, Mary Magdalene went to the tomb and saw that the stone had been removed from the entrance." },
      { number: 11, text: "Now Mary stood outside the tomb crying. As she wept, she bent over to look into the tomb" },
      { number: 14, text: "At this, she turned around and saw Jesus standing there, but she did not realize that it was Jesus." },
      { number: 15, text: "He asked her, 'Woman, why are you crying? Who is it you are looking for?' Thinking he was the gardener, she said, 'Sir, if you have carried him away, tell me where you have put him, and I will get him.'" },
      { number: 16, text: "Jesus said to her, 'Mary.' She turned toward him and cried out in Aramaic, 'Rabboni!' (which means 'Teacher').", sparkIds: ["rabboni"] },
      { number: 19, text: "On the evening of that first day of the week... Jesus came and stood among them and said, 'Peace be with you!'" },
      { number: 20, text: "After he said this, he showed them his hands and side. The disciples were overjoyed when they saw the Lord." },
      { number: 28, text: "Thomas said to him, 'My Lord and my God!'" },
      { number: 29, text: "Then Jesus told him, 'Because you have seen me, you have believed; blessed are those who have not seen and yet have believed.'" },
    ],
    checkInQuestions: [
      {
        prompt: "Who did Mary Magdalene initially mistake the risen Jesus for in the garden?",
        choices: ["The Roman centurion", "The gardener", "A temple guard", "Cleopas"],
        correctIndex: 1,
        explanation: "John 20:15 notes that Mary thought He was the gardener—a beautiful echo of Eden restored.",
      },
      {
        prompt: "What single word caused Mary to recognize her risen Master?",
        choices: [
          "'Look at my wounds'",
          "Jesus speaking her personal name: 'Mary'",
          "'I am alive'",
          "'Behold the dawn'",
        ],
        correctIndex: 1,
        explanation: "When the Good Shepherd called His sheep by name ('Mary'), her eyes were immediately opened.",
      },
      {
        prompt: "What did the Apostle Thomas confess when he touched Christ's wounded hands and side?",
        choices: [
          "'You are a mighty prophet'",
          "'My Lord and my God!'",
          "'Forgive my hesitation'",
          "'Great is Israel's king'",
        ],
        correctIndex: 1,
        explanation: "Thomas made the supreme confession of Christ's full deity: 'My Lord and my God!'",
      },
    ],
    storySlides: [
      {
        id: "jn20-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q22.png",
        badge: "Day 21 · Week 3 Milestone",
        title: "The Garden at Dawn",
        text: "While it was still dark on the first day of the week, death met its conqueror. The stone was rolled away, and the grave was empty.",
      },
      {
        id: "jn20-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q22.png",
        scriptureRef: "John 20:15–16",
        text: "“Jesus said to her, 'Mary.' She turned and cried out: 'Rabboni!' (which means 'Teacher').”",
        spark: SPARKS_WEEK_3.rabboni,
      },
      {
        id: "jn20-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q22.png",
        scriptureRef: "John 20:28–29",
        text: "“Thomas said: 'My Lord and my God!' Jesus told him: 'Blessed are those who have not seen and yet have believed.'”",
      },
      {
        id: "jn20-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q22.png",
        title: "The Living Lord",
        text: "Christianity is not the celebration of a dead philosopher's maxims. It is the announcement that Jesus Christ walked out of the tomb alive forevermore.",
      },
      {
        id: "jn20-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q22.png",
        title: "Week 3 Milestone Check",
        text: "Complete Week 3:",
        question: {
          prompt: "What did Mary Magdalene cry out upon recognizing Jesus outside the tomb?",
          choices: ["Rabboni!", "Logos!", "Bara!"],
          correctIndex: 0,
          explanation: "Rabboni is an Aramaic title meaning 'My Master / Teacher.'",
        },
      },
    ],
  },
];
