import type { Chapter, WordSpark } from "../types";

export const WEEK_1_ARC = "Week 1: Covenants & Deliverance";

// WordSparks for Week 1
export const SPARKS_WEEK_1: Record<string, WordSpark> = {
  bara: {
    id: "bara",
    term: "created",
    language: "Hebrew",
    originalScript: "בָּרָא",
    transliteration: "bārā'",
    rootMeaning: "to shape, fashion, create out of nothing (ex nihilo)",
    culturalInsight:
      "In the Hebrew Bible, 'bara' exclusively has God as its subject. Mortals build from existing materials; only God creates out of formless void by divine fiat.",
  },
  elohim: {
    id: "elohim",
    term: "God",
    language: "Hebrew",
    originalScript: "אֱלֹהִים",
    transliteration: "'ĕlōhîm",
    rootMeaning: "Mighty One, supreme God",
    culturalInsight:
      "A plural of majesty and supreme excellence. Throughout Genesis 1 it pairs with singular verbs, revealing the singular majesty of the Creator.",
  },
  ruach: {
    id: "ruach",
    term: "Spirit",
    language: "Hebrew",
    originalScript: "רוּחַ",
    transliteration: "rûaḥ",
    rootMeaning: "breath, wind, vibrant spirit",
    culturalInsight:
      "The 'Ruach Elohim' hovered over the deep. In Semitic thought, breath and wind represent invisible yet irresistible life-giving divine power.",
  },
  shamar: {
    id: "shamar",
    term: "to guard / keep",
    language: "Hebrew",
    originalScript: "שָׁמַר",
    transliteration: "šāmar",
    rootMeaning: "to watch over, protect, preserve sacred boundary",
    culturalInsight:
      "Adam was given the dual charge to 'work and keep' (avad and shamar) the garden—priestly terms used later for the Levites guarding the sanctuary.",
  },
  zera: {
    id: "zera",
    term: "seed / offspring",
    language: "Hebrew",
    originalScript: "זֶרַע",
    transliteration: "zera‘",
    rootMeaning: "seed, descendants, posterity",
    culturalInsight:
      "In Genesis 3:15 (the Protoevangelium), the promised 'seed of the woman' initiates the master scarlet thread leading directly to Christ overcoming the serpent.",
  },
  lech_lecha: {
    id: "lech_lecha",
    term: "Go forth",
    language: "Hebrew",
    originalScript: "לֶךְ־לְךָ",
    transliteration: "leḵ-lərā",
    rootMeaning: "go for yourself, journey into destiny",
    culturalInsight:
      "A rare idiomatic double imperative. It signifies not merely a relocation of geography, but an internal pilgrimage of total surrender and trust.",
  },
  berakhah: {
    id: "berakhah",
    term: "blessing",
    language: "Hebrew",
    originalScript: "בְּרָכָה",
    transliteration: "bərāḵāh",
    rootMeaning: "life-enriching favor, transmission of divine vitality",
    culturalInsight:
      "God's promise to Abram: 'In you all the families of the earth shall be blessed.' Election in Scripture is never for exclusion; it is for universal restoration.",
  },
  yahweh_yireh: {
    id: "yahweh_yireh",
    term: "The Lord will provide",
    language: "Hebrew",
    originalScript: "יְהוָה יִרְאֶה",
    transliteration: "Yahweh yir'eh",
    rootMeaning: "The Lord sees, and on His mount He will be seen / provided",
    culturalInsight:
      "On Mount Moriah, Abraham's substitution of the ram foreshadows the ultimate sacrificial Lamb provided by God on that same ridge outside Jerusalem.",
  },
  ehyeh: {
    id: "ehyeh",
    term: "I AM WHO I AM",
    language: "Hebrew",
    originalScript: "אֶהְיֶה אֲשֶׁר אֶהְיֶה",
    transliteration: "'ehyeh 'ăšer 'ehyeh",
    rootMeaning: "I will be what I will be, Self-Existent Eternal One",
    culturalInsight:
      "Revealed to Moses at the unburnt bush, this sacred name conveys uncaused existence, absolute unchangeability, and active covenant presence.",
  },
  kadosh: {
    id: "kadosh",
    term: "holy",
    language: "Hebrew",
    originalScript: "קָדוֹשׁ",
    transliteration: "qādōš",
    rootMeaning: "set apart, consecrated, blazing purity",
    culturalInsight:
      "'Take off your sandals, for the place where you stand is holy ground.' Holiness is not static detachment, but an active divine fire that sanctifies space.",
  },
  yeshuah: {
    id: "yeshuah",
    term: "salvation / deliverance",
    language: "Hebrew",
    originalScript: "יְשׁוּעָה",
    transliteration: "yəšû‘āh",
    rootMeaning: "rescue from peril, broad freedom, victorious salvation",
    culturalInsight:
      "At the Red Sea, Moses proclaims: 'Stand firm, and see the yeshuah of the Lord.' This is the linguistic root of the name Yeshua (Jesus).",
  },
  mitzvah: {
    id: "mitzvah",
    term: "commandment",
    language: "Hebrew",
    originalScript: "מִצְוָה",
    transliteration: "miṣwāh",
    rootMeaning: "covenant instruction, directive of love",
    culturalInsight:
      "The Decalogue (Ten Words) begins not with a demand, but with grace: 'I am the Lord your God, who brought you out of the land of Egypt.' Deliverance precedes duty.",
  },
};

export const WEEK_1_CHAPTERS: Chapter[] = [
  // DAY 1: Genesis 1
  {
    bookSlug: "genesis",
    bookTitle: "Genesis",
    chapterNumber: 1,
    dayNumber: 1,
    arcName: WEEK_1_ARC,
    title: "The Creation of the Cosmos",
    subtitle: "In the beginning, God formed the heavens and the earth out of formless void.",
    thematicHook: "Before the stars burned or continents took form, a solitary voice spoke across the deep: 'Let there be light.'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q6.png",
    coinsReward: 50,
    sparks: {
      bara: SPARKS_WEEK_1.bara,
      elohim: SPARKS_WEEK_1.elohim,
      ruach: SPARKS_WEEK_1.ruach,
    },
    verses: [
      { number: 1, text: "In the beginning God created the heavens and the earth.", sparkIds: ["bara", "elohim"] },
      { number: 2, text: "Now the earth was formless and void, and darkness was over the surface of the deep, and the Spirit of God was hovering over the waters.", sparkIds: ["ruach"] },
      { number: 3, text: "And God said, 'Let there be light,' and there was light." },
      { number: 4, text: "God saw that the light was good, and He separated the light from the darkness." },
      { number: 5, text: "God called the light 'day,' and the darkness He called 'night.' And there was evening, and there was morning—the first day." },
      { number: 26, text: "Then God said, 'Let Us make man in Our image, after Our likeness, to rule over the fish of the sea and the birds of the air, over the livestock, and over all the earth.'" },
      { number: 27, text: "So God created man in His own image; in the image of God He created him; male and female He created them." },
      { number: 31, text: "And God saw all that He had made, and behold, it was very good. And there was evening, and there was morning—the sixth day." },
    ],
    checkInQuestions: [
      {
        prompt: "What Hebrew word in Genesis 1:1 describes God creating something out of nothing?",
        choices: ["Bara", "Asah", "Yatsar", "Bavah"],
        correctIndex: 0,
        explanation: "Bara is reserved solely for God's divine act of creation out of nothingness.",
      },
      {
        prompt: "How does God evaluate creation on the sixth day after forming humanity?",
        choices: ["Satisfactory", "Very good", "Adequate for now", "Worthy of trial"],
        correctIndex: 1,
        explanation: "While earlier days were called 'good', Genesis 1:31 crowns the creation of humanity as 'very good'.",
      },
      {
        prompt: "What was the Spirit of God doing over the chaotic waters prior to the first command?",
        choices: ["Departing into heaven", "Sleeping", "Hovering / brooding with life", "Speaking judgement"],
        correctIndex: 2,
        explanation: "The Ruach Elohim was gently hovering over the waters, poised to impart structure and vibrant life.",
      },
    ],
    storySlides: [
      {
        id: "g1-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q6.png",
        badge: "Day 1 · Origins",
        title: "Before Time Began",
        text: "Before galaxies spun or breath filled human lungs, an uncreated voice shattered eternal silence: 'Let there be light.'",
      },
      {
        id: "g1-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q6.png",
        scriptureRef: "Genesis 1:1–2",
        text: "“In the beginning God created the heavens and the earth... and the Spirit of God was hovering over the face of the waters.”",
        spark: SPARKS_WEEK_1.bara,
      },
      {
        id: "g1-s3",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q6.png",
        title: "Bara: The Sovereign Touch",
        text: "Humans assemble and rearrange what already exists. But 'Bara' belongs to God alone—speaking realities into being where nothingness once reigned.",
        spark: SPARKS_WEEK_1.ruach,
      },
      {
        id: "g1-s4",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q6.png",
        scriptureRef: "Genesis 1:27",
        text: "“So God created man in His own image, in the image of God He created him; male and female He created them.”",
      },
      {
        id: "g1-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q6.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What word describes God forming the cosmos out of nothing?",
          choices: ["Bara", "Shamar", "Elohim"],
          correctIndex: 0,
          explanation: "Bara is the Hebrew verb for divine creation ex nihilo.",
        },
      },
    ],
  },

  // DAY 2: Genesis 3
  {
    bookSlug: "genesis",
    bookTitle: "Genesis",
    chapterNumber: 3,
    dayNumber: 2,
    arcName: WEEK_1_ARC,
    title: "The Fall & The Ancient Promise",
    subtitle: "The entrance of fracture into the garden, and the first whisper of redemption.",
    thematicHook: "In the shadow of rebellion, amid the ruins of Eden, God utters the first promise of the coming Deliverer.",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q11.png",
    coinsReward: 50,
    sparks: {
      shamar: SPARKS_WEEK_1.shamar,
      zera: SPARKS_WEEK_1.zera,
    },
    verses: [
      { number: 1, text: "Now the serpent was more crafty than any beast of the field that the Lord God had made. He said to the woman, 'Did God really say, You shall not eat of any tree in the garden?'" },
      { number: 6, text: "When the woman saw that the tree was good for food and pleasing to the eyes, and desirable for gaining wisdom, she took some and ate it. She also gave some to her husband with her, and he ate it." },
      { number: 9, text: "Then the Lord God called to the man, 'Where are you?'" },
      { number: 15, text: "And I will put enmity between you and the woman, and between your seed and her seed; he will crush your head, and you will strike his heel.", sparkIds: ["zera"] },
      { number: 21, text: "And the Lord God made garments of skin for Adam and his wife, and clothed them." },
    ],
    checkInQuestions: [
      {
        prompt: "What is Genesis 3:15 traditionally known as by biblical scholars?",
        choices: ["The Protoevangelium (First Gospel)", "The Mosaic Code", "The Edenic Ordinance", "The Abrahamic Benediction"],
        correctIndex: 0,
        explanation: "Genesis 3:15 is the Protoevangelium, the earliest biblical prophecy announcing Christ's victory over the serpent.",
      },
      {
        prompt: "What question did God ask the man as he hid among the trees?",
        choices: ["'Why have you rebelled?'", "'Where are you?'", "'What have you touched?'", "'Who told you to hide?'"],
        correctIndex: 1,
        explanation: "God gently called, 'Where are you?'—seeking communion and prompting honest confession.",
      },
      {
        prompt: "How did God clothe Adam and Eve after the fall?",
        choices: ["Garments of woven flax", "Garments of animal skin", "Robes of fig leaves", "Armor of bronze"],
        correctIndex: 1,
        explanation: "God provided skins of an animal, showing that covering human shame required sacrifice.",
      },
    ],
    storySlides: [
      {
        id: "g3-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q11.png",
        badge: "Day 2 · The Fracture",
        title: "The Question in the Mist",
        text: "“Did God really say?” With five deceptive words, doubt entered human consciousness, sundering unbroken intimacy.",
      },
      {
        id: "g3-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q11.png",
        scriptureRef: "Genesis 3:9",
        text: "“Then the Lord God called to the man, 'Where are you?'”",
        spark: SPARKS_WEEK_1.shamar,
      },
      {
        id: "g3-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q11.png",
        scriptureRef: "Genesis 3:15",
        text: "“I will put enmity between you and the woman, and between your offspring and hers; he will crush your head, and you will strike his heel.”",
        spark: SPARKS_WEEK_1.zera,
      },
      {
        id: "g3-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q11.png",
        title: "The Scarlet Thread Begins",
        text: "Even as the gates of Eden close, grace shines through. A bruised champion will come through the woman's line to deliver the mortal blow to evil.",
      },
      {
        id: "g3-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q11.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What does Genesis 3:15 promise the offspring of the woman will do to the serpent?",
          choices: ["Crush his head", "Make a treaty with him", "Drive him into Egypt"],
          correctIndex: 0,
          explanation: "He will crush the serpent's head, overcoming the power of sin and death.",
        },
      },
    ],
  },

  // DAY 3: Genesis 12
  {
    bookSlug: "genesis",
    bookTitle: "Genesis",
    chapterNumber: 12,
    dayNumber: 3,
    arcName: WEEK_1_ARC,
    title: "The Call of Abram",
    subtitle: "A radical departure from the familiar into a promise of universal blessing.",
    thematicHook: "Seventy-five years old and settled in Haran, Abram hears an impossible whisper: 'Leave everything, and I will make you a great nation.'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q12.png",
    coinsReward: 50,
    sparks: {
      lech_lecha: SPARKS_WEEK_1.lech_lecha,
      berakhah: SPARKS_WEEK_1.berakhah,
    },
    verses: [
      { number: 1, text: "Then the Lord said to Abram: 'Go forth from your country, your people, and your father's household to the land I will show you.'", sparkIds: ["lech_lecha"] },
      { number: 2, text: "I will make you into a great nation, and I will bless you; I will make your name great, and you will be a blessing.", sparkIds: ["berakhah"] },
      { number: 3, text: "I will bless those who bless you, and whoever curses you I will curse; and all peoples on earth will be blessed through you." },
      { number: 4, text: "So Abram went, as the Lord had told him, and Lot went with him. Abram was seventy-five years old when he departed from Haran." },
      { number: 7, text: "The Lord appeared to Abram and said, 'To your offspring I will give this land.' So Abram built an altar there to the Lord, who had appeared to him." },
    ],
    checkInQuestions: [
      {
        prompt: "How old was Abram when he departed Haran in obedience to God's call?",
        choices: ["50 years old", "75 years old", "99 years old", "120 years old"],
        correctIndex: 1,
        explanation: "Genesis 12:4 explicitly notes Abram was 75 years old when he ventured into the unknown.",
      },
      {
        prompt: "What is the ultimate global scope of God's promise to Abram?",
        choices: [
          "Only his immediate tribe will prosper",
          "All peoples on earth will be blessed through him",
          "He will conquer all surrounding empires",
          "His name will replace Pharaoh's",
        ],
        correctIndex: 1,
        explanation: "Genesis 12:3 promises that through Abraham, all families and nations on earth will find divine blessing.",
      },
      {
        prompt: "What did Abram build at Shechem when God appeared to confirm the land promise?",
        choices: ["A fortified city", "A watchtower", "An altar to the Lord", "A royal palace"],
        correctIndex: 2,
        explanation: "Abram built an altar, marking the land with sacrificial worship and consecration.",
      },
    ],
    storySlides: [
      {
        id: "g12-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q12.png",
        badge: "Day 3 · The Covenant",
        title: "Into the Unknown",
        text: "Leaving home, kin, and ancestral security, Abram stepped across the desert sands guided by an invisible promise.",
      },
      {
        id: "g12-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q12.png",
        scriptureRef: "Genesis 12:1–2",
        text: "“Leave your country, your people and your father’s household and go to the land I will show you... and you will be a blessing.”",
        spark: SPARKS_WEEK_1.lech_lecha,
      },
      {
        id: "g12-s3",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q12.png",
        title: "Blessed to Be a Blessing",
        text: "God's covenant with Abraham was never a private privilege—it was an engine of global redemption to touch every corner of the earth.",
        spark: SPARKS_WEEK_1.berakhah,
      },
      {
        id: "g12-s4",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q12.png",
        scriptureRef: "Genesis 12:3",
        text: "“All peoples on earth will be blessed through you.”",
      },
      {
        id: "g12-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q12.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Hebrew phrase means 'Go forth for yourself into destiny'?",
          choices: ["Lech-Lecha", "Elohim", "Ruach"],
          correctIndex: 0,
          explanation: "Lech-Lecha was God's radical commissioning phrase to Abram.",
        },
      },
    ],
  },

  // DAY 4: Genesis 22
  {
    bookSlug: "genesis",
    bookTitle: "Genesis",
    chapterNumber: 22,
    dayNumber: 4,
    arcName: WEEK_1_ARC,
    title: "Mount Moriah & The Lord Provides",
    subtitle: "The ultimate test of surrendered love and the ram in the thicket.",
    thematicHook: "On the slopes of Moriah, Isaac asks the agonizing question: 'Here is the fire and wood, but where is the lamb?'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q10.png",
    coinsReward: 50,
    sparks: {
      yahweh_yireh: SPARKS_WEEK_1.yahweh_yireh,
    },
    verses: [
      { number: 2, text: "Then God said, 'Take your son, your only son Isaac, whom you love, and go to the land of Moriah. Offer him there as a burnt offering on one of the mountains I will show you.'" },
      { number: 7, text: "Isaac spoke up and said to his father Abraham, 'Father?' 'Here I am, my son,' Abraham replied. 'The fire and wood are here,' Isaac said, 'but where is the lamb for the burnt offering?'" },
      { number: 8, text: "Abraham answered, 'God Himself will provide the lamb for the burnt offering, my son.' And the two of them walked on together.", sparkIds: ["yahweh_yireh"] },
      { number: 11, text: "But the angel of the Lord called to him from heaven, 'Abraham! Abraham!' 'Here I am,' he replied." },
      { number: 13, text: "Abraham looked up and there in a thicket he saw a ram caught by its horns. He went over and took the ram and sacrificed it as a burnt offering instead of his son." },
      { number: 14, text: "So Abraham called that place The Lord Will Provide. And to this day it is said, 'On the mountain of the Lord it will be provided.'" },
    ],
    checkInQuestions: [
      {
        prompt: "What name did Abraham give to the place where God provided the ram?",
        choices: ["El Shaddai", "Yahweh Yireh (The Lord Will Provide)", "Ebenezer", "Jehovah Nissi"],
        correctIndex: 1,
        explanation: "Abraham memorialized the mountain as Yahweh Yireh: 'The Lord Will Provide.'",
      },
      {
        prompt: "Where was the ram found that substituted for Isaac?",
        choices: ["Caught in a thorn thicket by its horns", "Resting beside the altar", "Wandering in the meadow", "Carried by an angel"],
        correctIndex: 0,
        explanation: "Genesis 22:13 states the ram was caught by its horns in a dense thicket.",
      },
      {
        prompt: "What city ridge corresponds historically to the region of Mount Moriah?",
        choices: ["Mount Sinai", "Jerusalem / Temple Mount", "Mount Carmel", "Mount Hebron"],
        correctIndex: 1,
        explanation: "2 Chronicles 3:1 reveals Solomon built the temple on Mount Moriah, where God provided for Abraham.",
      },
    ],
    storySlides: [
      {
        id: "g22-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q10.png",
        badge: "Day 4 · The Altar",
        title: "The Ascent of Surrender",
        text: "Climbing Mount Moriah, an aging father and trusting son carry wood up the ridge, entering the deepest crucible of faith.",
      },
      {
        id: "g22-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q10.png",
        scriptureRef: "Genesis 22:8",
        text: "“Abraham answered, 'God Himself will provide the lamb for the burnt offering, my son.' And the two walked on together.”",
        spark: SPARKS_WEEK_1.yahweh_yireh,
      },
      {
        id: "g22-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q10.png",
        scriptureRef: "Genesis 22:13",
        text: "“Abraham looked up and there in a thicket he saw a ram caught by its horns. He sacrificed it instead of his son.”",
      },
      {
        id: "g22-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q10.png",
        title: "The Shadow of Calvary",
        text: "Two thousand years later, on that same Jerusalem ridge, the Father gave His only Son—and this time, no angel stayed the stroke.",
      },
      {
        id: "g22-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q10.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What does 'Yahweh Yireh' translate to in English?",
          choices: ["The Lord Will Provide", "The Lord is Holy", "The Lord our Healer"],
          correctIndex: 0,
          explanation: "Yahweh Yireh means 'The Lord will see / provide.'",
        },
      },
    ],
  },

  // DAY 5: Exodus 3
  {
    bookSlug: "exodus",
    bookTitle: "Exodus",
    chapterNumber: 3,
    dayNumber: 5,
    arcName: WEEK_1_ARC,
    title: "The Burning Bush & The Name",
    subtitle: "Holy ground in the desert of Midian and the revelation of the Great I AM.",
    thematicHook: "A bush blazes with unquenchable celestial fire, yet its leaves do not turn to ash. A fugitive shepherd turns aside to behold the wonder.",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q3.png",
    coinsReward: 50,
    sparks: {
      ehyeh: SPARKS_WEEK_1.ehyeh,
      kadosh: SPARKS_WEEK_1.kadosh,
    },
    verses: [
      { number: 2, text: "There the angel of the Lord appeared to him in flames of fire from within a bush. Moses saw that though the bush was on fire it did not burn up." },
      { number: 5, text: "'Do not come any closer,' God said. 'Take off your sandals, for the place where you are standing is holy ground.'", sparkIds: ["kadosh"] },
      { number: 7, text: "The Lord said, 'I have indeed seen the misery of my people in Egypt. I have heard them crying out because of their slave drivers, and I am concerned about their suffering.'" },
      { number: 10, text: "'So now, go. I am sending you to Pharaoh to bring my people the Israelites out of Egypt.'" },
      { number: 14, text: "God said to Moses, 'I AM WHO I AM. This is what you are to say to the Israelites: I AM has sent me to you.'", sparkIds: ["ehyeh"] },
    ],
    checkInQuestions: [
      {
        prompt: "Why was Moses commanded to take off his sandals at Horeb?",
        choices: ["To respect Midianite custom", "Because the ground where he stood was holy", "To prepare for running", "As a sign of slavery"],
        correctIndex: 1,
        explanation: "Exodus 3:5 states the divine presence consecrated the desert earth into holy ground.",
      },
      {
        prompt: "What eternal name did God reveal to Moses when asked who sent him?",
        choices: ["Elohim Sabaoth", "I AM WHO I AM (Ehyeh Asher Ehyeh)", "El Shaddai", "Yahweh Shalom"],
        correctIndex: 1,
        explanation: "God declared His personal covenant name: 'I AM WHO I AM'—the self-existent, uncaused Lord.",
      },
      {
        prompt: "What prompted God's intervention according to Exodus 3:7?",
        choices: ["Moses's personal petition", "He saw the misery and heard the groaning of His people", "Egypt violated a trade treaty", "The elders built an altar"],
        correctIndex: 1,
        explanation: "God heard their cries under bondage, demonstrating His deep covenant compassion.",
      },
    ],
    storySlides: [
      {
        id: "ex3-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q3.png",
        badge: "Day 5 · Deliverance",
        title: "The Flame in the Desert",
        text: "Forty years an exiled shepherd in Midian. Then, on the slopes of Horeb, a thorn bush burns with unconsuming fire.",
      },
      {
        id: "ex3-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q3.png",
        scriptureRef: "Exodus 3:5",
        text: "“'Do not come any closer,' God said. 'Take off your sandals, for the place where you are standing is holy ground.'”",
        spark: SPARKS_WEEK_1.kadosh,
      },
      {
        id: "ex3-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q3.png",
        scriptureRef: "Exodus 3:14",
        text: "“God said to Moses, 'I AM WHO I AM. Tell the Israelites: I AM has sent me to you.'”",
        spark: SPARKS_WEEK_1.ehyeh,
      },
      {
        id: "ex3-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q3.png",
        title: "The Uncaused Fire",
        text: "Created fires need fuel to burn. God's fire burns on nothing, for He needs nothing to exist. He is the eternal, independent I AM.",
      },
      {
        id: "ex3-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q3.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Hebrew divine name means 'I AM WHO I AM'?",
          choices: ["Ehyeh Asher Ehyeh", "Kadosh Israel", "Bara Elohim"],
          correctIndex: 0,
          explanation: "Ehyeh Asher Ehyeh is God's self-revelation to Moses.",
        },
      },
    ],
  },

  // DAY 6: Exodus 14
  {
    bookSlug: "exodus",
    bookTitle: "Exodus",
    chapterNumber: 14,
    dayNumber: 6,
    arcName: WEEK_1_ARC,
    title: "Crossing the Red Sea",
    subtitle: "Trapped between chariot wheels and deep waters, Israel beholds salvation.",
    thematicHook: "Behind them, the rumble of six hundred iron chariots. Ahead, an impassable sea. Moses cries: 'Stand still, and see the salvation of the Lord!'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q4.png",
    coinsReward: 50,
    sparks: {
      yeshuah: SPARKS_WEEK_1.yeshuah,
    },
    verses: [
      { number: 10, text: "As Pharaoh approached, the Israelites looked up, and there were the Egyptians, marching after them. They were terrified and cried out to the Lord." },
      { number: 13, text: "Moses answered the people, 'Do not be afraid. Stand firm and you will see the deliverance the Lord will bring you today. The Egyptians you see today you will never see again.'", sparkIds: ["yeshuah"] },
      { number: 14, text: "'The Lord will fight for you; you need only to be still.'" },
      { number: 21, text: "Then Moses stretched out his hand over the sea, and all that night the Lord drove the sea back with a strong east wind and turned it into dry land. The waters were divided," },
      { number: 22, text: "and the Israelites went through the sea on dry ground, with a wall of water on their right and on their left." },
      { number: 31, text: "And when the Israelites saw the mighty hand of the Lord displayed against the Egyptians, the people feared the Lord and put their trust in him and in Moses his servant." },
    ],
    checkInQuestions: [
      {
        prompt: "What did Moses tell the terrified Israelites as the Egyptian chariots closed in?",
        choices: [
          "'Draw your swords and fight bravely'",
          "'The Lord will fight for you; you need only to be still'",
          "'Surrender and return to Goshen'",
          "'Scatter into the wilderness hills'",
        ],
        correctIndex: 1,
        explanation: "Exodus 14:14 records Moses's immortal words: 'The Lord will fight for you; you need only to be still.'",
      },
      {
        prompt: "What natural instrument did God use to push back the waters throughout the night?",
        choices: ["A sudden desert earthquake", "A strong east wind", "Torrential mountain rain", "Blinding hailstones"],
        correctIndex: 1,
        explanation: "Exodus 14:21 states the Lord drove back the sea with a strong east wind all night.",
      },
      {
        prompt: "What stood on Israel's left and right as they crossed the seabed?",
        choices: ["Rows of ancient cypress trees", "Walls of water", "Clouds of sulfur", "Shields of bronze"],
        correctIndex: 1,
        explanation: "The parted waters stood congealed as walls on their right hand and left.",
      },
    ],
    storySlides: [
      {
        id: "ex14-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q4.png",
        badge: "Day 6 · The Sea",
        title: "Trapped at the Shore",
        text: "With crashing waves before them and Pharaoh’s cavalry behind them, Israel faced certain doom. But man's extremity is God's opportunity.",
      },
      {
        id: "ex14-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q4.png",
        scriptureRef: "Exodus 14:13–14",
        text: "“Moses said: 'Do not be afraid. Stand firm and you will see the deliverance the Lord will bring you today... The Lord will fight for you; you need only to be still.'”",
        spark: SPARKS_WEEK_1.yeshuah,
      },
      {
        id: "ex14-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q4.png",
        scriptureRef: "Exodus 14:21–22",
        text: "“Moses stretched out his hand... and the Israelites went through the sea on dry ground, with a wall of water on their right and on their left.”",
      },
      {
        id: "ex14-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q4.png",
        title: "The Path Through the Waters",
        text: "God did not merely deliver them around their obstacle; He carved a highway straight through the depths of impossible waters.",
      },
      {
        id: "ex14-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q4.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Hebrew term for deliverance and rescue forms the name of Jesus?",
          choices: ["Yeshuah", "Bara", "Shamar"],
          correctIndex: 0,
          explanation: "Yeshuah means salvation/deliverance and is the root of the name Jesus.",
        },
      },
    ],
  },

  // DAY 7: Exodus 20
  {
    bookSlug: "exodus",
    bookTitle: "Exodus",
    chapterNumber: 20,
    dayNumber: 7,
    arcName: WEEK_1_ARC,
    title: "The Ten Commandments & Sinai",
    subtitle: "The voice from the smoking mountain and the covenant charter of love.",
    thematicHook: "Sinai trembles in fire, smoke, and trumpet blasts. The Creator speaks the Ten Words that shaped human moral consciousness forever.",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q5.png",
    coinsReward: 50,
    sparks: {
      mitzvah: SPARKS_WEEK_1.mitzvah,
    },
    verses: [
      { number: 1, text: "And God spoke all these words:" },
      { number: 2, text: "'I am the Lord your God, who brought you out of Egypt, out of the land of slavery.'" },
      { number: 3, text: "'You shall have no other gods before me.'" },
      { number: 4, text: "'You shall not make for yourself an image in the form of anything in heaven above or on the earth beneath or in the waters below.'" },
      { number: 7, text: "'You shall not misuse the name of the Lord your God, for the Lord will not hold anyone guiltless who misuses his name.'" },
      { number: 8, text: "'Remember the Sabbath day by keeping it holy.'" },
      { number: 12, text: "'Honor your father and your mother, so that you may live long in the land the Lord your God is giving you.'" },
      { number: 13, text: "'You shall not murder.'" },
      { number: 14, text: "'You shall not commit adultery.'" },
      { number: 15, text: "'You shall not steal.'" },
      { number: 16, text: "'You shall not give false testimony against your neighbor.'" },
      { number: 17, text: "'You shall not covet your neighbor's house. You shall not covet your neighbor's wife, or his male or female servant, his ox or donkey, or anything that belongs to your neighbor.'", sparkIds: ["mitzvah"] },
    ],
    checkInQuestions: [
      {
        prompt: "With what foundational truth does God open the Ten Commandments in Exodus 20:2?",
        choices: [
          "'I am a demanding sovereign'",
          "'I am the Lord your God, who brought you out of Egypt, out of the land of slavery'",
          "'Offer sacrifices before My face'",
          "'Woe unto those who break these statutes'",
        ],
        correctIndex: 1,
        explanation: "Grace precedes command: God reminds Israel that He is their Redeemer before laying down His law.",
      },
      {
        prompt: "Which is the first commandment that carries a specific promised blessing?",
        choices: [
          "Honoring the Sabbath day",
          "Honoring father and mother",
          "Having no other gods",
          "Not coveting",
        ],
        correctIndex: 1,
        explanation: "Ephesians 6:2 highlights Exodus 20:12: 'Honor your father and mother' is the first commandment with a promise.",
      },
      {
        prompt: "How does the final commandment differ from outward criminal statutes?",
        choices: [
          "It deals strictly with temple animals",
          "It addresses inner desires of the heart ('You shall not covet')",
          "It applies only to priests",
          "It requires financial restitution",
        ],
        correctIndex: 1,
        explanation: "Coveting addresses the internal motivations of the human heart, pointing forward to Jesus's teachings on the Mount.",
      },
    ],
    storySlides: [
      {
        id: "ex20-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q5.png",
        badge: "Day 7 · 7-Day Milestone",
        title: "The Voice From the Mountain",
        text: "Smoke wraps Sinai like an iron furnace. Amid trumpet calls, the Living God lays the moral foundation of a redeemed civilization.",
      },
      {
        id: "ex20-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q5.png",
        scriptureRef: "Exodus 20:2–3",
        text: "“I am the Lord your God, who brought you out of Egypt, out of the land of slavery. You shall have no other gods before Me.”",
        spark: SPARKS_WEEK_1.mitzvah,
      },
      {
        id: "ex20-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q5.png",
        scriptureRef: "Exodus 20:8, 12",
        text: "“Remember the Sabbath day, to keep it holy... Honor your father and your mother, that your days may be long.”",
      },
      {
        id: "ex20-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q5.png",
        title: "Freedom Bound in Love",
        text: "The law is not a cage; it is a guardrail on the edge of a precipice, showing a free people how to live in holy community with God and neighbor.",
      },
      {
        id: "ex20-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q5.png",
        title: "Week 1 Milestone Check",
        text: "Complete Week 1:",
        question: {
          prompt: "What Hebrew word means divine commandment and directive of covenant love?",
          choices: ["Mitzvah", "Bara", "Shamar"],
          correctIndex: 0,
          explanation: "Mitzvah is the biblical word for a sacred commandment.",
        },
      },
    ],
  },
];
