import type { Chapter, WordSpark } from "../types";

export const WEEK_2_ARC = "Week 2: Kingdom, Wisdom & Prophecy";

export const SPARKS_WEEK_2: Record<string, WordSpark> = {
  emunah: {
    id: "emunah",
    term: "faithfulness / steadfast trust",
    language: "Hebrew",
    originalScript: "אֱמוּנָה",
    transliteration: "'ĕmûnāh",
    rootMeaning: "firmness, steadfast stability, unwavering fidelity",
    culturalInsight:
      "When David confronted Goliath, his confidence rested not in armor or strength, but in God's emunah. Biblical faith is not passive optimism; it is grounded certainty in God's covenant power.",
  },
  qana: {
    id: "qana",
    term: "zeal / jealousy",
    language: "Hebrew",
    originalScript: "קָנָא",
    transliteration: "qānā'",
    rootMeaning: "burning intensity, passionate protectiveness",
    culturalInsight:
      "Elijah declared on Carmel: 'I have been very zealous (qana) for the Lord God of Hosts.' Divine zeal burns like holy fire to cleanse idolatry and restore wholehearted worship.",
  },
  mizmor: {
    id: "mizmor",
    term: "psalm / melody",
    language: "Hebrew",
    originalScript: "מִזְמוֹר",
    transliteration: "mizmōr",
    rootMeaning: "a song accompanied by plucked strings",
    culturalInsight:
      "David composed Psalm 23 reflecting on his youth as a shepherd boy in the rugged hills of Bethlehem, where predators prowled and green pastures had to be searched out.",
  },
  tsalmavet: {
    id: "tsalmavet",
    term: "valley of deep darkness",
    language: "Hebrew",
    originalScript: "צַלְמָוֶת",
    transliteration: "ṣalmāweṯ",
    rootMeaning: "shadow of death, darkest ravine",
    culturalInsight:
      "Judean shepherds led sheep through perilous wadis where flash floods and wolves lurked. The rod (club) defended against predators; the staff (crook) guided straying sheep.",
  },
  hesed: {
    id: "hesed",
    term: "steadfast covenant love",
    language: "Hebrew",
    originalScript: "חֶסֶד",
    transliteration: "ḥeseḏ",
    rootMeaning: "loyal kindness, unfailing covenant devotion",
    culturalInsight:
      "One of the richest words in Hebrew theology. 'Surely goodness and hesed shall follow me'—the shepherd's covenant love pursues us actively all our days.",
  },
  elyon: {
    id: "elyon",
    term: "Most High",
    language: "Hebrew",
    originalScript: "עֶלְיוֹן",
    transliteration: "‘Elyôn",
    rootMeaning: "Supreme Sovereign, elevated above all powers",
    culturalInsight:
      "In Psalm 91, whoever dwells in the secret place of 'Elyon' rests under the shadow of the Almighty (Shaddai). No pestilence or arrow can breach this heavenly fortress.",
  },
  batah: {
    id: "batah",
    term: "to trust",
    language: "Hebrew",
    originalScript: "בָּטַח",
    transliteration: "bāṭaḥ",
    rootMeaning: "to lean one's whole weight upon, feel completely secure",
    culturalInsight:
      "Proverbs 3:5 commands us to batah in the Lord with all our heart and lean not on our own understanding. It depicts falling back into loving arms with total abandon.",
  },
  shalom: {
    id: "shalom",
    term: "peace / wholeness",
    language: "Hebrew",
    originalScript: "שָׁלוֹם",
    transliteration: "šālôm",
    rootMeaning: "completeness, sound health, restored harmony",
    culturalInsight:
      "In Isaiah 53:5, 'the chastisement of our shalom was upon Him.' Biblical shalom is not just absence of conflict, but total spiritual and physical restoration through the cross.",
  },
  shaddai: {
    id: "shaddai",
    term: "Almighty",
    language: "Hebrew",
    originalScript: "שַׁדַּי",
    transliteration: "Šadday",
    rootMeaning: "All-Sufficient Provider, Sovereign Overthrower of nature",
    culturalInsight:
      "When Daniel was lowered into the pit of lions, he trusted that El Shaddai reigns over the fiercest jaws of beasts and empires alike.",
  },
};

export const WEEK_2_CHAPTERS: Chapter[] = [
  // DAY 8: 1 Samuel 17
  {
    bookSlug: "1-samuel",
    bookTitle: "1 Samuel",
    chapterNumber: 17,
    dayNumber: 8,
    arcName: WEEK_2_ARC,
    title: "David and Goliath",
    subtitle: "A shepherd boy with five smooth stones against a nine-foot champion.",
    thematicHook: "For forty days the giant roared blasphemies across the valley of Elah. A teenager with a sling answered: 'The battle belongs to the Lord!'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q7.png",
    coinsReward: 50,
    sparks: {
      emunah: SPARKS_WEEK_2.emunah,
    },
    verses: [
      { number: 4, text: "A champion named Goliath, who was from Gath, came out of the Philistine camp. His height was six cubits and a span." },
      { number: 40, text: "Then David took his staff in his hand, chose five smooth stones from the stream, put them in the pouch of his shepherd's bag and, with his sling in his hand, approached the Philistine." },
      { number: 45, text: "David said to the Philistine, 'You come against me with sword and spear and javelin, but I come against you in the name of the Lord of hosts, the God of the armies of Israel, whom you have defied.'", sparkIds: ["emunah"] },
      { number: 47, text: "'All those gathered here will know that it is not by sword or spear that the Lord saves; for the battle is the Lord's, and he will give all of you into our hands.'" },
      { number: 49, text: "Reaching into his bag and taking out a stone, he slung it and struck the Philistine on the forehead. The stone sank into his forehead, and he fell facedown on the ground." },
    ],
    checkInQuestions: [
      {
        prompt: "In whose name did David declare he was confronting Goliath?",
        choices: [
          "In the name of King Saul",
          "In the name of the Lord of Hosts, God of the armies of Israel",
          "In the name of his father Jesse",
          "In the honor of Bethlehem",
        ],
        correctIndex: 1,
        explanation: "1 Samuel 17:45 shows David relied entirely on the name and covenant authority of Yahweh Sabaoth.",
      },
      {
        prompt: "How many smooth stones did David select from the stream bed?",
        choices: ["Three", "Five", "Seven", "Twelve"],
        correctIndex: 1,
        explanation: "David picked five smooth stones from the dry brook for his sling.",
      },
      {
        prompt: "Where did David's sling stone strike Goliath?",
        choices: ["Between his armor plates", "On his forehead", "On his throat", "Through his shield"],
        correctIndex: 1,
        explanation: "The stone sank directly into Goliath's forehead, bringing the giant to the ground.",
      },
    ],
    storySlides: [
      {
        id: "1s17-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q7.png",
        badge: "Day 8 · The Valley",
        title: "The Roar in the Valley",
        text: "Morning and evening for forty days, Goliath defied the armies of Israel. Armor-clad warriors trembled, but a shepherd boy looked with eyes of faith.",
      },
      {
        id: "1s17-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q7.png",
        scriptureRef: "1 Samuel 17:45",
        text: "“David said: 'You come against me with sword and spear and javelin, but I come against you in the name of the Lord of hosts.'”",
        spark: SPARKS_WEEK_2.emunah,
      },
      {
        id: "1s17-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q7.png",
        scriptureRef: "1 Samuel 17:47",
        text: "“'All those gathered here will know that it is not by sword or spear that the Lord saves; for the battle is the Lord's.'”",
      },
      {
        id: "1s17-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q7.png",
        title: "Faith Sees the Unseen",
        text: "Israel saw how big Goliath was compared to themselves. David saw how small Goliath was compared to the Living God.",
      },
      {
        id: "1s17-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q7.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Hebrew word means steadfast certainty and faithful courage in God?",
          choices: ["Emunah", "Mitzvah", "Shamar"],
          correctIndex: 0,
          explanation: "Emunah is unwavering covenant trust.",
        },
      },
    ],
  },

  // DAY 9: 1 Kings 18
  {
    bookSlug: "1-kings",
    bookTitle: "1 Kings",
    chapterNumber: 18,
    dayNumber: 9,
    arcName: WEEK_2_ARC,
    title: "Elijah on Mount Carmel",
    subtitle: "One prophet against four hundred and fifty, and the fire falling from heaven.",
    thematicHook: "Three years of drought. King Ahab calls Elijah a troubler of Israel. The prophet summons all the nation: 'The God who answers by fire, He is God!'",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q8.png",
    coinsReward: 50,
    sparks: {
      qana: SPARKS_WEEK_2.qana,
    },
    verses: [
      { number: 21, text: "Elijah went before the people and said, 'How long will you waver between two opinions? If the Lord is God, follow him; but if Baal is God, follow him.' But the people said nothing." },
      { number: 36, text: "At the time of sacrifice, the prophet Elijah stepped forward and prayed: 'Lord, the God of Abraham, Isaac and Israel, let it be known today that you are God in Israel and that I am your servant.'" },
      { number: 37, text: "'Answer me, Lord, answer me, so these people will know that you, Lord, are God, and that you are turning their hearts back again.'", sparkIds: ["qana"] },
      { number: 38, text: "Then the fire of the Lord fell and burned up the sacrifice, the wood, the stones and the soil, and also licked up the water in the trench." },
      { number: 39, text: "When all the people saw this, they fell prostrate and cried, 'The Lord—he is God! The Lord—he is God!'" },
    ],
    checkInQuestions: [
      {
        prompt: "What did Elijah pour over his altar three times before praying for fire?",
        choices: ["Olive oil", "Jars of water", "Grain offering", "Sweet wine"],
        correctIndex: 1,
        explanation: "Elijah drenched the sacrifice and stones with twelve large jars of water until the trench overflowed.",
      },
      {
        prompt: "What did the fire of the Lord consume when it fell on Carmel?",
        choices: [
          "Only the bull",
          "The sacrifice, wood, stones, dust, and the trench water",
          "The prophets of Baal immediately",
          "The crown of Mount Carmel's trees",
        ],
        correctIndex: 1,
        explanation: "1 Kings 18:38 emphasizes that the celestial fire licked up everything, including the stones and water.",
      },
      {
        prompt: "What did the people cry out when they saw the fire consume the drenched altar?",
        choices: [
          "'The Lord—He is God! The Lord—He is God!'",
          "'Elijah is king over Israel!'",
          "'Woe unto Samaria!'",
          "'Rain is coming!'",
        ],
        correctIndex: 0,
        explanation: "The people fell on their faces in awe, confessing Yahweh's undeniable supremacy.",
      },
    ],
    storySlides: [
      {
        id: "1k18-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q8.png",
        badge: "Day 9 · The Altar of Fire",
        title: "The Contest on Carmel",
        text: "On the ridge overlooking the Mediterranean, 450 pagan prophets screamed and slashed themselves from dawn till evening. Baal gave no answer.",
      },
      {
        id: "1k18-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q8.png",
        scriptureRef: "1 Kings 18:21",
        text: "“Elijah said: 'How long will you waver between two opinions? If the Lord is God, follow Him; but if Baal, follow him.'”",
      },
      {
        id: "1k18-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q8.png",
        scriptureRef: "1 Kings 18:38–39",
        text: "“Then the fire of the Lord fell and burned up the sacrifice, stones, and dust... The people fell prostrate and cried: 'The Lord—He is God!'”",
        spark: SPARKS_WEEK_2.qana,
      },
      {
        id: "1k18-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q8.png",
        title: "The Quiet Prayer",
        text: "The false prophets danced in hysteria for hours. Elijah prayed for sixty seconds in calm covenant assurance—and heaven opened.",
      },
      {
        id: "1k18-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q8.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Hebrew term reflects righteous zeal and holy intensity for God's honor?",
          choices: ["Qana", "Batah", "Hesed"],
          correctIndex: 0,
          explanation: "Qana denotes burning divine zeal and devotion.",
        },
      },
    ],
  },

  // DAY 10: Psalm 23
  {
    bookSlug: "psalms",
    bookTitle: "Psalms",
    chapterNumber: 23,
    dayNumber: 10,
    arcName: WEEK_2_ARC,
    title: "The Lord is My Shepherd",
    subtitle: "A song of peaceful provision, dark valleys, and an overflowing cup.",
    thematicHook: "Written by a shepherd who became king, six verses that have comforted weary souls for three thousand years.",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q9.png",
    coinsReward: 50,
    sparks: {
      mizmor: SPARKS_WEEK_2.mizmor,
      tsalmavet: SPARKS_WEEK_2.tsalmavet,
      hesed: SPARKS_WEEK_2.hesed,
    },
    verses: [
      { number: 1, text: "The Lord is my shepherd, I lack nothing.", sparkIds: ["mizmor"] },
      { number: 2, text: "He makes me lie down in green pastures, he leads me beside quiet waters," },
      { number: 3, text: "he refreshes my soul. He guides me along the right paths for his name's sake." },
      { number: 4, text: "Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.", sparkIds: ["tsalmavet"] },
      { number: 5, text: "You prepare a table before me in the presence of my enemies. You anoint my head with oil; my cup overflows." },
      { number: 6, text: "Surely your goodness and love will follow me all the days of my life, and I will dwell in the house of the Lord forever.", sparkIds: ["hesed"] },
    ],
    checkInQuestions: [
      {
        prompt: "Why does the psalmist state he fears no evil in the darkest valley?",
        choices: ["He carries a bronze sword", "For You are with me", "He is swifter than wolves", "The daylight never fades"],
        correctIndex: 1,
        explanation: "The ground of fearlessness is not personal power, but the shepherd's comforting presence: 'For You are with me.'",
      },
      {
        prompt: "What two instruments does the shepherd carry to comfort the sheep?",
        choices: ["A bow and quiver", "A rod and a staff", "A lamp and a bell", "A rope and a horn"],
        correctIndex: 1,
        explanation: "The rod guards against beasts; the staff gently guides and rescues straying sheep.",
      },
      {
        prompt: "What does the psalmist declare will actively follow him all his days?",
        choices: ["Honor and riches", "Goodness and covenant love (hesed)", "Triumph over foes", "Peaceful weather"],
        correctIndex: 1,
        explanation: "Psalm 23:6 crowns the journey: 'Surely goodness and hesed shall follow me all the days of my life.'",
      },
    ],
    storySlides: [
      {
        id: "ps23-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q9.png",
        badge: "Day 10 · The Pasture",
        title: "The Good Shepherd",
        text: "In the stony wilderness of Judea, sheep cannot survive without a watchful shepherd. David knew: I am the sheep, and Yahweh is my keeper.",
      },
      {
        id: "ps23-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q9.png",
        scriptureRef: "Psalm 23:1–3",
        text: "“The Lord is my shepherd, I lack nothing. He makes me lie down in green pastures; He leads me beside quiet waters.”",
        spark: SPARKS_WEEK_2.mizmor,
      },
      {
        id: "ps23-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q9.png",
        scriptureRef: "Psalm 23:4",
        text: "“Even though I walk through the darkest valley, I will fear no evil, for You are with me; Your rod and Your staff comfort me.”",
        spark: SPARKS_WEEK_2.tsalmavet,
      },
      {
        id: "ps23-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q9.png",
        title: "Pursued by Lovingkindness",
        text: "The Hebrew verb for 'follow' (yirdəpûnî) implies active pursuit. God's hesed doesn't casually trail behind—it hunts us down with grace.",
        spark: SPARKS_WEEK_2.hesed,
      },
      {
        id: "ps23-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q9.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Hebrew term means unfailing covenant love and loyal kindness?",
          choices: ["Hesed", "Tsalmavet", "Mizmor"],
          correctIndex: 0,
          explanation: "Hesed is God's enduring steadfast covenant love.",
        },
      },
    ],
  },

  // DAY 11: Psalm 91
  {
    bookSlug: "psalms",
    bookTitle: "Psalms",
    chapterNumber: 91,
    dayNumber: 11,
    arcName: WEEK_2_ARC,
    title: "The Secret Place of the Most High",
    subtitle: "A psalm of divine shelter, angelic guardianship, and fearless refuge.",
    thematicHook: "A thousand may fall at your side and ten thousand at your right hand. But whoever dwells under the shadow of the Almighty stands unassailable.",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q13.png",
    coinsReward: 50,
    sparks: {
      elyon: SPARKS_WEEK_2.elyon,
      shaddai: SPARKS_WEEK_2.shaddai,
    },
    verses: [
      { number: 1, text: "Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty.", sparkIds: ["elyon", "shaddai"] },
      { number: 2, text: "I will say of the Lord, 'He is my refuge and my fortress, my God, in whom I trust.'" },
      { number: 4, text: "He will cover you with his feathers, and under his wings you will find refuge; his faithfulness will be your shield and rampart." },
      { number: 5, text: "You will not fear the terror of night, nor the arrow that flies by day," },
      { number: 11, text: "For he will command his angels concerning you to guard you in all your ways;" },
      { number: 12, text: "they will lift you up in their hands, so that you will not strike your foot against a stone." },
      { number: 14, text: "'Because he loves me,' says the Lord, 'I will rescue him; I will protect him, for he acknowledges my name.'" },
    ],
    checkInQuestions: [
      {
        prompt: "Where does the believer rest according to Psalm 91:1?",
        choices: ["Behind fortified palace walls", "In the shadow of the Almighty (Shaddai)", "At the summit of Mount Carmel", "Beside the Jordan"],
        correctIndex: 1,
        explanation: "Psalm 91:1 declares that dwelling with the Most High grants rest in the shadow of El Shaddai.",
      },
      {
        prompt: "What metaphor describes God's tender protective coverage in verse 4?",
        choices: ["A tower of iron", "Covering you with His feathers and wings", "A fiery chariot", "A stone moat"],
        correctIndex: 1,
        explanation: "Like a protective eagle sheltering its young, God covers His faithful under His wings.",
      },
      {
        prompt: "What divine command is given regarding angels in Psalm 91:11?",
        choices: [
          "To wage war in distant nations",
          "To guard you in all your ways",
          "To observe human trials silently",
          "To build the temple",
        ],
        correctIndex: 1,
        explanation: "God charges His angels with continuous personal guardianship over those who abide in Him.",
      },
    ],
    storySlides: [
      {
        id: "ps91-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q13.png",
        badge: "Day 11 · The Fortress",
        title: "The Unbreachable Fortress",
        text: "In a world of pestilence, arrows by day, and terrors by night, there is a hidden sanctuary where anxiety cannot reign.",
      },
      {
        id: "ps91-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q13.png",
        scriptureRef: "Psalm 91:1–2",
        text: "“Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty. I will say: 'He is my refuge and my fortress.'”",
        spark: SPARKS_WEEK_2.elyon,
      },
      {
        id: "ps91-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q13.png",
        scriptureRef: "Psalm 91:11",
        text: "“For He will command His angels concerning you to guard you in all your ways.”",
      },
      {
        id: "ps91-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q13.png",
        title: "Dwelling vs. Visiting",
        text: "The promise is not for those who occasionally visit God in crisis, but for those who 'dwell' (sit and abide) continually in His presence.",
        spark: SPARKS_WEEK_2.shaddai,
      },
      {
        id: "ps91-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q13.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Hebrew name for God means 'Most High' and exalted above all?",
          choices: ["Elyon", "Shamar", "Zera"],
          correctIndex: 0,
          explanation: "El Elyon denotes God as the Most High Sovereign.",
        },
      },
    ],
  },

  // DAY 12: Proverbs 3
  {
    bookSlug: "proverbs",
    bookTitle: "Proverbs",
    chapterNumber: 3,
    dayNumber: 12,
    arcName: WEEK_2_ARC,
    title: "Trust in the Lord With All Your Heart",
    subtitle: "The gold standard of biblical wisdom and the paths made straight.",
    thematicHook: "Human intellect is a magnificent tool, but a terrible god. Solomon directs us to a higher anchor: wholehearted surrender.",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q14.png",
    coinsReward: 50,
    sparks: {
      batah: SPARKS_WEEK_2.batah,
    },
    verses: [
      { number: 5, text: "Trust in the Lord with all your heart and lean not on your own understanding;", sparkIds: ["batah"] },
      { number: 6, text: "in all your ways submit to him, and he will make your paths straight." },
      { number: 7, text: "Do not be wise in your own eyes; fear the Lord and shun evil." },
      { number: 8, text: "This will bring health to your body and nourishment to your bones." },
      { number: 13, text: "Blessed are those who find wisdom, those who gain understanding," },
      { number: 15, text: "She is more precious than rubies; nothing you desire can compare with her." },
    ],
    checkInQuestions: [
      {
        prompt: "What are believers commanded NOT to lean on in Proverbs 3:5?",
        choices: ["The counsel of elders", "Their own understanding", "The scriptures", "The king's decree"],
        correctIndex: 1,
        explanation: "Proverbs 3:5 instructs us to trust God with all our heart and not rely on our limited human perception.",
      },
      {
        prompt: "What will God do when we acknowledge and submit to Him in all our ways?",
        choices: [
          "Make our paths straight",
          "Remove every trial instantly",
          "Give us the throne of Tyre",
          "Multiply gold coins without measure",
        ],
        correctIndex: 0,
        explanation: "Proverbs 3:6 promises that submitting all our ways to Him results in cleared, straightened paths.",
      },
      {
        prompt: "What is biblical wisdom valued above in Proverbs 3:15?",
        choices: ["Fine linen", "Rubies and all earthly treasures", "Royal chariots", "Cedar wood"],
        correctIndex: 1,
        explanation: "Solomon declares wisdom is more precious than rubies—nothing comparable exists.",
      },
    ],
    storySlides: [
      {
        id: "pr3-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q14.png",
        badge: "Day 12 · Wisdom",
        title: "The Crossroad of Counsel",
        text: "Every day presents two advisors: our own frail intellect or the infinite wisdom of the Creator. Solomon gives timeless direction.",
      },
      {
        id: "pr3-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q14.png",
        scriptureRef: "Proverbs 3:5–6",
        text: "“Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to Him, and He will make your paths straight.”",
        spark: SPARKS_WEEK_2.batah,
      },
      {
        id: "pr3-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q14.png",
        scriptureRef: "Proverbs 3:13, 15",
        text: "“Blessed are those who find wisdom... She is more precious than rubies; nothing you desire can compare with her.”",
      },
      {
        id: "pr3-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q14.png",
        title: "The Posture of Batah",
        text: "Batah means leaning your entire weight upon God. When you stop white-knuckling control of your life, He straightens the jagged road ahead.",
      },
      {
        id: "pr3-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q14.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Hebrew verb means to lean one's whole weight upon God in complete trust?",
          choices: ["Batah", "Bara", "Shaddai"],
          correctIndex: 0,
          explanation: "Batah expresses total surrendered reliance.",
        },
      },
    ],
  },

  // DAY 13: Isaiah 53
  {
    bookSlug: "isaiah",
    bookTitle: "Isaiah",
    chapterNumber: 53,
    dayNumber: 13,
    arcName: WEEK_2_ARC,
    title: "The Suffering Servant",
    subtitle: "The profound seventh-century BC portrait of the Lamb pierced for our transgressions.",
    thematicHook: "Written seven hundred years before the Roman cross, Isaiah unveils the heart of the Gospel: substitutionary atonement.",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q15.png",
    coinsReward: 50,
    sparks: {
      shalom: SPARKS_WEEK_2.shalom,
    },
    verses: [
      { number: 3, text: "He was despised and rejected by mankind, a man of suffering, and familiar with pain. Like one from whom people hide their faces he was despised, and we held him in low esteem." },
      { number: 4, text: "Surely he took up our pain and bore our suffering, yet we considered him punished by God, stricken by him, and afflicted." },
      { number: 5, text: "But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was on him, and by his wounds we are healed.", sparkIds: ["shalom"] },
      { number: 6, text: "We all, like sheep, have gone astray, each of us has turned to our own way; and the Lord has laid on him the iniquity of us all." },
      { number: 7, text: "He was oppressed and afflicted, yet he did not open his mouth; he was led like a lamb to the slaughter, and as a sheep before its shearers is silent, so he did not open his mouth." },
      { number: 11, text: "After he has suffered, he will see the light of life and be satisfied; by his knowledge my righteous servant will justify many, and he will bear their iniquities." },
    ],
    checkInQuestions: [
      {
        prompt: "Why was the Servant pierced and crushed according to Isaiah 53:5?",
        choices: [
          "For his own errors in judgment",
          "For our transgressions and iniquities",
          "Because of Roman law",
          "To satisfy the Sanhedrin",
        ],
        correctIndex: 1,
        explanation: "Isaiah 53:5 teaches substitution: 'He was pierced for our transgressions, he was crushed for our iniquities.'",
      },
      {
        prompt: "What universal human condition is described in verse 6?",
        choices: [
          "All like sheep have gone astray, each turning to his own way",
          "Humanity sought God with clean hands",
          "The nations were united in justice",
          "The righteous stood without blemish",
        ],
        correctIndex: 0,
        explanation: "Isaiah notes that all of us have wandered like lost sheep, yet God laid our guilt on the Servant.",
      },
      {
        prompt: "How did the Servant respond while being oppressed and led to slaughter?",
        choices: [
          "He summoned legions of angels",
          "He cursed his persecutors",
          "He did not open his mouth, silent like a lamb",
          "He demanded a legal appeal",
        ],
        correctIndex: 2,
        explanation: "Like a silent lamb before its shearers, Jesus submitted without bitterness or retaliation.",
      },
    ],
    storySlides: [
      {
        id: "is53-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q15.png",
        badge: "Day 13 · The Prophecy",
        title: "The Scarlet Chapter",
        text: "Seven centuries before Golgotha, the prophet Isaiah drew the silhouette of a wounded Savior who would bear the cosmic weight of human sin.",
      },
      {
        id: "is53-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q15.png",
        scriptureRef: "Isaiah 53:5",
        text: "“He was pierced for our transgressions, He was crushed for our iniquities; the punishment that brought us peace was on Him, and by His wounds we are healed.”",
        spark: SPARKS_WEEK_2.shalom,
      },
      {
        id: "is53-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q15.png",
        scriptureRef: "Isaiah 53:6–7",
        text: "“We all like sheep have gone astray... and the Lord has laid on Him the iniquity of us all. He was led like a lamb to the slaughter, yet opened not His mouth.”",
      },
      {
        id: "is53-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q15.png",
        title: "The Divine Exchange",
        text: "The chastisement that brought our shalom fell on Him. He took our guilt, nakedness, and shame, that we might take His righteousness and eternal peace.",
      },
      {
        id: "is53-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q15.png",
        title: "Anchor Check",
        text: "Test your recall:",
        question: {
          prompt: "What Hebrew concept of complete wholeness and restoration was secured by Christ's wounds?",
          choices: ["Shalom", "Mizmor", "Qana"],
          correctIndex: 0,
          explanation: "Shalom is the profound biblical peace purchased by the Servant.",
        },
      },
    ],
  },

  // DAY 14: Daniel 6
  {
    bookSlug: "daniel",
    bookTitle: "Daniel",
    chapterNumber: 6,
    dayNumber: 14,
    arcName: WEEK_2_ARC,
    title: "Daniel in the Lions' Den",
    subtitle: "Uncompromising integrity under imperial decree and the mouths of lions shut.",
    thematicHook: "A Persian decree forbids prayer on pain of death. An eighty-year-old statesman opens his windows toward Jerusalem three times a day as before.",
    artworkUrl: "/images/quizzes/look-at-the-picture-bible/q1.png",
    coinsReward: 50,
    sparks: {
      shaddai: SPARKS_WEEK_2.shaddai,
    },
    verses: [
      { number: 10, text: "Now when Daniel learned that the decree had been published, he went home to his upstairs room where the windows opened toward Jerusalem. Three times a day he got down on his knees and prayed, giving thanks to his God, just as he had done before." },
      { number: 16, text: "So the king gave the order, and they brought Daniel and threw him into the lions' den. The king said to Daniel, 'May your God, whom you serve continually, rescue you!'" },
      { number: 19, text: "At the first light of dawn, the king got up and hurried to the lions' den." },
      { number: 20, text: "When he came near the den, he called to Daniel in an anguished voice, 'Daniel, servant of the living God, has your God, whom you serve continually, been able to rescue you from the lions?'" },
      { number: 21, text: "Daniel answered, 'May the king live forever!'" },
      { number: 22, text: "'My God sent his angel, and he shut the mouths of the lions. They have not hurt me, because I was found blameless in his sight.'", sparkIds: ["shaddai"] },
      { number: 23, text: "The king was overjoyed... And when Daniel was lifted from the den, no wound was found on him, because he had trusted in his God." },
    ],
    checkInQuestions: [
      {
        prompt: "What did Daniel do immediately after learning the royal decree banning prayer was signed?",
        choices: [
          "He hid his prayer closet in the cellar",
          "He fled into Judea",
          "He opened his windows toward Jerusalem and prayed three times a day as before",
          "He petitioned Darius for an exemption",
        ],
        correctIndex: 2,
        explanation: "Daniel 6:10 records that Daniel maintained his faithful habit of open prayer without compromise.",
      },
      {
        prompt: "How did God protect Daniel through the night in the pit of predators?",
        choices: [
          "He put the lions to sleep with herbs",
          "He sent His angel, who shut the lions' mouths",
          "The guards threw bread to distract them",
          "Daniel frightened them with torches",
        ],
        correctIndex: 1,
        explanation: "Daniel testified that God sent His angel to shut the mouths of the beasts.",
      },
      {
        prompt: "Why was no wound found on Daniel when he was lifted out at dawn?",
        choices: [
          "Because he had trusted in his God",
          "Because the lions were not hungry",
          "Because his armor protected him",
          "Because Darius changed his mind",
        ],
        correctIndex: 0,
        explanation: "Daniel 6:23 summarizes: 'No wound was found on him, because he had trusted in his God.'",
      },
    ],
    storySlides: [
      {
        id: "dan6-s1",
        type: "hook",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q1.png",
        badge: "Day 14 · Week 2 Milestone",
        title: "The Open Window",
        text: "Babylon fell, and Persia arose. But Daniel’s loyalty remained anchored to the King of Heaven. When prayer became illegal, he knelt openly.",
      },
      {
        id: "dan6-s2",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q1.png",
        scriptureRef: "Daniel 6:10",
        text: "“He went home to his upstairs room where the windows opened toward Jerusalem. Three times a day he got down on his knees and prayed, giving thanks to God.”",
      },
      {
        id: "dan6-s3",
        type: "verse",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q1.png",
        scriptureRef: "Daniel 6:22",
        text: "“Daniel answered: 'My God sent His angel, and He shut the mouths of the lions. They have not hurt me, because I was found blameless.'”",
        spark: SPARKS_WEEK_2.shaddai,
      },
      {
        id: "dan6-s4",
        type: "insight",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q1.png",
        title: "The Lion of Judah",
        text: "The empires of this world boast roaring beasts and ruthless decrees. But the Almighty reigns over hungry lions and imperial crowns alike.",
      },
      {
        id: "dan6-s5",
        type: "question",
        artworkUrl: "/images/quizzes/look-at-the-picture-bible/q1.png",
        title: "Week 2 Milestone Check",
        text: "Complete Week 2:",
        question: {
          prompt: "What divine name reveals God as the All-Sufficient Almighty who protects His servants?",
          choices: ["El Shaddai", "Bara", "Tsalmavet"],
          correctIndex: 0,
          explanation: "El Shaddai is the Almighty Protector of His people.",
        },
      },
    ],
  },
];
