import type { Category, Quiz, Series } from "./types";
import { RESTAURANT_FILL_QUESTIONS } from "./quizzes/restaurant-fill";
import { DAILY_LENGTH } from "./economy";

export const CATEGORIES: Category[] = [
  {
    slug: "survival",
    name: "Survival",
    description: "Wilderness skills, preparedness, and staying alive when plans fail.",
    expert: "Field instructors",
  },
  {
    slug: "history",
    name: "History",
    description: "Civilizations, turning points, and the people who shaped them.",
    expert: "Historians",
  },
  {
    slug: "science",
    name: "Science",
    description: "Earth, space, the body, and how the physical world actually works.",
    expert: "STEM educators",
  },
  {
    slug: "geography",
    name: "Geography",
    description: "Countries, capitals, cities, and the map of the living world.",
  },
  {
    slug: "food",
    name: "Food & Dining",
    description: "Restaurants, kitchens, and the difference between a drive-thru and a tasting menu.",
  },
  {
    slug: "sports",
    name: "Sports",
    description: "Rules, records, and the stories behind the scoreboard.",
  },
  {
    slug: "entertainment",
    name: "Entertainment",
    description: "Film, music, and pop culture without the clickbait.",
  },
  {
    slug: "diy",
    name: "DIY",
    description: "Tools, repairs, and practical know-how around the house.",
  },
  {
    slug: "cars",
    name: "Cars & Trucks",
    description: "Engines, marques, and the road that got us here.",
  },
  {
    slug: "bible",
    name: "Bible",
    description: "People, places, and stories from scripture.",
  },
];

function q(
  prompt: string,
  choices: string[],
  answerIndex: number,
  explanation: string,
) {
  return { prompt, choices, answerIndex, explanation };
}

export const QUIZZES: Quiz[] = [
  {
    slug: "get-your-fill-restaurant",
    title: "Get Your Fill: The Restaurant Floor Quiz",
    blurb:
      "Original remix of a long-form restaurant hit: fast food, family dining, and fine dining — 50+ questions so the sitting is long enough to matter.",
    category: "food",
    isLongform: true,
    coinsOnComplete: 250,
    questions: RESTAURANT_FILL_QUESTIONS,
  },
  {
    slug: "worlds-largest-cities",
    title: "World's Largest Cities",
    blurb: "Can you rank the megacities that actually hold the most people?",
    category: "geography",
    seriesSlug: "geography-1",
    coinsOnComplete: 80,
    questions: [
      q("By city proper population, which of these is typically the largest?", ["Tokyo", "Chongqing", "Paris", "Chicago"], 1, "Chongqing's administrative city proper is enormous; metro rankings look different."),
      q("Which African city is routinely among the continent's most populous urban areas?", ["Cape Town", "Lagos", "Nairobi", "Accra"], 1, "Lagos is Nigeria's commercial capital and a true megacity."),
      q("New York City sits primarily on which river's estuary?", ["Mississippi", "Hudson", "Ohio", "Colorado"], 1, "Manhattan and the harbor sit on the Hudson estuary."),
      q("Which city is the capital of Australia?", ["Sydney", "Melbourne", "Canberra", "Perth"], 2, "Canberra was planned as a compromise capital between Sydney and Melbourne."),
      q("Mumbai was formerly widely known in English as:", ["Bombay", "Calcutta", "Madras", "Ceylon"], 0, "The official English name changed to Mumbai in 1995."),
      q("Which city is both a country and a city-state in Southeast Asia?", ["Hong Kong", "Macau", "Singapore", "Brunei"], 2, "Singapore is a sovereign city-state."),
    ],
  },
  {
    slug: "us-states",
    title: "How Well Do You Know the States?",
    blurb: "Borders, nicknames, and the odd facts that trip people up.",
    category: "geography",
    seriesSlug: "geography-1",
    coinsOnComplete: 80,
    questions: [
      q("Which state has the most coastline?", ["California", "Florida", "Alaska", "Hawaii"], 2, "Alaska's fjords and islands give it by far the longest coastline."),
      q("The Four Corners monument marks the meeting of Utah, Colorado, New Mexico, and:", ["Arizona", "Nevada", "Texas", "Wyoming"], 0, "It is the only point in the U.S. where four states meet."),
      q("Which is the smallest U.S. state by area?", ["Delaware", "Rhode Island", "Connecticut", "Vermont"], 1, "Rhode Island is the smallest by land area."),
      q("Juneau, Alaska is unusual among state capitals because it:", ["Has no airport", "Is not connected to the rest of the state by road", "Sits below sea level", "Has no legislature"], 1, "Juneau is accessible primarily by air or sea."),
      q("Which state is nicknamed the Lone Star State?", ["Nevada", "Texas", "Montana", "Idaho"], 1, "The nickname comes from the Texas flag."),
      q("Yellowstone National Park is primarily in which state?", ["Idaho", "Montana", "Wyoming", "Colorado"], 2, "Most of Yellowstone lies in Wyoming."),
    ],
  },
  {
    slug: "latin-america",
    title: "Latin American Countries",
    blurb: "Capitals, languages, and landmarks from Mexico to Patagonia.",
    category: "geography",
    seriesSlug: "geography-1",
    coinsOnComplete: 80,
    questions: [
      q("What is the capital of Colombia?", ["Medellín", "Cali", "Bogotá", "Cartagena"], 2, "Bogotá sits on a high plateau in the Andes."),
      q("Which country is the largest by area in South America?", ["Argentina", "Brazil", "Peru", "Colombia"], 1, "Brazil covers nearly half the continent."),
      q("Machu Picchu is located in:", ["Chile", "Bolivia", "Peru", "Ecuador"], 2, "The Inca citadel is in the Andes of Peru."),
      q("The Atacama Desert is primarily in:", ["Brazil", "Chile", "Uruguay", "Panama"], 1, "The Atacama is one of the driest places on Earth."),
      q("Which Central American country has no standing army (constitutionally abolished)?", ["Honduras", "Guatemala", "Costa Rica", "Belize"], 2, "Costa Rica abolished its army in 1948."),
      q("Portuguese is the official language of:", ["Argentina", "Brazil", "Mexico", "Cuba"], 1, "Brazil is the only Portuguese-speaking country in the Americas at national scale."),
    ],
  },
  {
    slug: "us-capitals",
    title: "U.S. Capitals",
    blurb: "Not every famous city is the capital. Prove you know the difference.",
    category: "geography",
    seriesSlug: "geography-1",
    coinsOnComplete: 80,
    questions: [
      q("The capital of California is:", ["Los Angeles", "San Francisco", "Sacramento", "San Diego"], 2, "Sacramento has been the capital since the 1850s."),
      q("The capital of New York is:", ["New York City", "Buffalo", "Albany", "Rochester"], 2, "Albany sits on the Hudson River."),
      q("The capital of Illinois is:", ["Chicago", "Springfield", "Peoria", "Naperville"], 1, "Springfield, not Chicago, is the state capital."),
      q("The capital of Florida is:", ["Miami", "Orlando", "Tampa", "Tallahassee"], 3, "Tallahassee is in the state's panhandle."),
      q("The capital of Texas is:", ["Dallas", "Houston", "Austin", "San Antonio"], 2, "Austin is the capital; Houston is larger."),
      q("The capital of Pennsylvania is:", ["Philadelphia", "Pittsburgh", "Harrisburg", "Erie"], 2, "Harrisburg sits on the Susquehanna River."),
    ],
  },
  {
    slug: "european-countries",
    title: "European Countries",
    blurb: "Borders that moved, languages that stayed, and capitals you should know.",
    category: "geography",
    seriesSlug: "geography-1",
    coinsOnComplete: 80,
    questions: [
      q("Which country is not on the Iberian Peninsula?", ["Spain", "Portugal", "Andorra", "Belgium"], 3, "Belgium is in northwest Europe."),
      q("The capital of Poland is:", ["Kraków", "Gdańsk", "Warsaw", "Wrocław"], 2, "Warsaw is Poland's capital and largest city."),
      q("Which country uses the forint as its currency (not the euro)?", ["Austria", "Hungary", "Ireland", "Finland"], 1, "Hungary retained the forint."),
      q("Fjords are a defining coastal feature of:", ["Greece", "Norway", "Malta", "Netherlands"], 1, "Norway's west coast is famous for glacial fjords."),
      q("The Danube River empties into the:", ["North Sea", "Baltic Sea", "Black Sea", "Adriatic Sea"], 2, "It flows southeast to the Black Sea."),
      q("Vatican City is an enclave within:", ["France", "Switzerland", "Italy", "Austria"], 2, "It sits inside Rome."),
    ],
  },
  {
    slug: "geography-review",
    title: "Geography 1 Review",
    blurb: "Score 70% or better after finishing the pack to earn a Certificate of Mastery.",
    category: "geography",
    seriesSlug: "geography-1",
    isReview: true,
    coinsOnComplete: 120,
    questions: [
      q("Which U.S. state has the longest coastline?", ["Florida", "California", "Alaska", "Maine"], 2, "Alaska dominates U.S. coastline length."),
      q("Canberra is the capital of:", ["New Zealand", "Australia", "Fiji", "Papua New Guinea"], 1, "Australia's planned capital is Canberra."),
      q("The capital of Texas is:", ["Houston", "Dallas", "Austin", "Fort Worth"], 2, "Austin is the capital."),
      q("Machu Picchu is in:", ["Mexico", "Peru", "Brazil", "Chile"], 1, "It is in Peru."),
      q("Singapore is best described as a:", ["U.S. territory", "Chinese province", "Sovereign city-state", "Malaysian state"], 2, "Singapore is independent."),
      q("The Danube flows into the:", ["Atlantic", "Black Sea", "Mediterranean near Gibraltar", "North Sea"], 1, "The Danube delta is on the Black Sea."),
      q("Costa Rica is known for having:", ["The Amazon's source", "No standing army", "The Andes' highest peak", "Europe's largest desert"], 1, "The army was abolished in 1948."),
      q("The capital of Illinois is:", ["Chicago", "Springfield", "St. Louis", "Indianapolis"], 1, "Springfield, Illinois."),
    ],
  },
  {
    slug: "wilderness-essentials",
    title: "Wilderness Essentials",
    blurb: "Priorities when you are cold, lost, or unprepared.",
    category: "survival",
    seriesSlug: "survival-essentials",
    expert: "Field instructors",
    coinsOnComplete: 80,
    questions: [
      q("The classic survival priority order usually starts with:", ["Food first", "Shelter and protection from exposure", "Hunting a large animal", "Building a raft"], 1, "Exposure can kill faster than hunger."),
      q("The Rule of Threes is a rough guide for:", ["How many matches to pack", "Air, shelter, water, and food time limits", "How many people in a search party", "Calorie counts"], 1, "Roughly 3 minutes without air, 3 hours in harsh exposure, 3 days without water, 3 weeks without food."),
      q("The safest general advice for drinking untreated stream water is:", ["It is always safe if it looks clear", "Treat or filter it", "Boil only if it smells", "Add sugar"], 1, "Clear water can still carry pathogens."),
      q("Hypothermia is primarily a problem of:", ["Losing core body heat", "Too much salt", "Sunburn", "High altitude only"], 0, "It is dangerously low core temperature."),
      q("A whistle is useful because:", ["Animals always flee from it", "Sound carries farther than shouting and costs less energy", "It purifies water", "It starts fires"], 1, "Three blasts is a common distress signal."),
      q("If you are lost and people know your plan, the best default is often:", ["Keep walking all night", "Stay put and make yourself findable", "Follow every animal trail", "Climb the tallest cliff at dusk"], 1, "Searchers start from last known points."),
    ],
  },
  {
    slug: "shelter-building",
    title: "Shelter When the Weather Turns",
    blurb: "Stay dry, stay warm, stay off the wind.",
    category: "survival",
    seriesSlug: "survival-essentials",
    expert: "Field instructors",
    coinsOnComplete: 80,
    questions: [
      q("A debris hut works mainly by:", ["Reflecting radar", "Trapping dead air in insulation", "Attracting animals for heat", "Collecting rain as a pool"], 1, "Leaves and debris create insulating air pockets."),
      q("You should generally avoid building shelter:", ["Near a water source you can see", "In a dry gully that could flash flood", "On slightly higher ground", "Behind a windbreak"], 1, "Dry washes can flood suddenly."),
      q("A space blanket helps primarily by:", ["Generating chemical heat forever", "Reflecting radiant heat back to your body", "Filtering viruses", "Replacing a sleeping bag in arctic winter by itself"], 1, "It is a radiant barrier, not magic."),
      q("In rain, a roof should:", ["Be perfectly flat to collect water on you", "Slope so water runs off", "Be made only of metal", "Touch the ground on all four sides with no venting ever"], 1, "Shedding water is the point."),
      q("Ground insulation matters because:", ["Soil is always warmer than air", "Conduction into cold ground steals heat fast", "It hides you from satellites", "Bugs cannot crawl on leaves"], 1, "You lose heat quickly into cold earth."),
      q("A lean-to is typically:", ["A fully sealed cabin", "A simple angled roof against a ridgepole or wall", "An underground bunker", "A snow cave only"], 1, "It is a fast, open-sided shelter."),
    ],
  },
  {
    slug: "water-and-fire",
    title: "Water and Fire",
    blurb: "Two systems that decide whether a night is merely uncomfortable.",
    category: "survival",
    seriesSlug: "survival-essentials",
    expert: "Field instructors",
    coinsOnComplete: 80,
    questions: [
      q("Boiling water is effective because:", ["It adds minerals", "Heat kills many pathogens", "It removes heavy metals completely", "It carbonates the water"], 1, "Boil time recommendations vary; heat is the mechanism."),
      q("Tinder should be:", ["Wet logs", "Fine, dry, easy to ignite material", "Green leaves", "River stones"], 1, "You build from tinder to kindling to fuel."),
      q("A ferro rod spark needs:", ["Soaking the rod first", "Fine dry tinder and a practiced strike", "Gasoline only", "Direct sunlight"], 1, "Technique and tinder quality matter."),
      q("Collecting rain is often safer than stagnant ponds because:", ["Rain never needs treatment", "It has not sat in a contaminated pool, though you should still treat when possible", "It is always sterile", "It contains more salt"], 1, "Airborne contaminants exist; it is still usually cleaner."),
      q("A fire lay like a teepee helps because:", ["Smoke cannot rise", "Air can feed the flame as fuel dries and catches", "It hides the fire", "It uses no tinder"], 1, "Structure and airflow matter."),
      q("Never start a fire:", ["On a designated fire ring when allowed", "Under a low dead canopy in high wind during a ban", "With wet gloves", "At dusk"], 1, "Wildfire risk and legality come first."),
    ],
  },
  {
    slug: "field-first-aid",
    title: "Field First Aid Basics",
    blurb: "Stop the bleed, protect the airway, get help.",
    category: "survival",
    seriesSlug: "survival-essentials",
    expert: "Field instructors",
    coinsOnComplete: 80,
    questions: [
      q("For severe bleeding, the first action is usually:", ["Give water immediately", "Apply direct pressure", "Elevate only and wait", "Remove all clothing and walk"], 1, "Direct pressure is the core first step."),
      q("A tourniquet is for:", ["Splinters", "Life-threatening limb bleeding that is not controlled", "Sunburn", "Headaches"], 1, "It is a last-resort tool for massive limb hemorrhage."),
      q("If someone may have a spinal injury after a fall:", ["Shake them to check", "Minimize unnecessary movement and get trained help", "Sit them up quickly", "Give them a running start"], 1, "Do not casually manipulate the spine."),
      q("Heat stroke is a:", ["Mild thirst", "Medical emergency with high core temp and altered mental status", "Only a skin problem", "Cure for hypothermia"], 1, "Cooling and emergency care are urgent."),
      q("Clean water for irrigation of a dirty wound is used to:", ["Cauterize", "Flush debris", "Replace stitches", "Tattoo the area"], 1, "Irrigation reduces contamination."),
      q("The emergency signal of three of anything (whistle, fires, flashes) commonly means:", ["All is well", "Distress", "Dinner is ready", "Property line"], 1, "Triples are a widespread distress convention."),
    ],
  },
  {
    slug: "navigation-basics",
    title: "Stay Found: Navigation",
    blurb: "Maps, compasses, and the discipline of a trip plan.",
    category: "survival",
    seriesSlug: "survival-essentials",
    expert: "Field instructors",
    coinsOnComplete: 80,
    questions: [
      q("A compass needle points toward:", ["True geographic north exactly always", "Magnetic north, which differs from true north by declination", "The nearest city", "South in the northern hemisphere"], 1, "You adjust for declination on precise bearings."),
      q("A contour line on a topographic map shows:", ["Average rainfall", "Equal elevation", "Cell coverage", "Property owners"], 1, "Tight contours mean steep ground."),
      q("Telling someone your route and return time is:", ["Optional trivia", "A core safety practice", "Only for experts", "A way to lose privacy with no benefit"], 1, "It starts the clock for a search."),
      q("GPS devices can fail because of:", ["Batteries, canopy, canyons, or signal loss", "Too much paper", "Having a map", "Daylight"], 0, "Always have a non-electronic backup."),
      q("Following a drainage downhill in unknown terrain:", ["Always leads to a road immediately", "Can work but may cliff-out or enter worse brush and water", "Is illegal", "Replaces a compass"], 1, "Terrain still wins."),
      q("Handrails in navigation are:", ["Only wooden fences", "Linear features like rivers or ridges you can follow", "Always roads", "Stars exclusively"], 1, "They help you stay oriented."),
    ],
  },
  {
    slug: "survival-review",
    title: "Survival Essentials Review",
    blurb: "Mastery requires 70% or better on this review after the five field quizzes.",
    category: "survival",
    seriesSlug: "survival-essentials",
    isReview: true,
    expert: "Field instructors",
    coinsOnComplete: 120,
    questions: [
      q("Exposure is dangerous mainly because:", ["You get bored", "You can lose core heat quickly", "Food spoils instantly", "Compasses reverse"], 1, "Shelter and insulation come early."),
      q("Treat water because:", ["Clear water can still make you sick", "All water is poisonous", "Boiling adds calories", "Filters are decorative"], 0, "Pathogens are invisible."),
      q("Direct pressure is first-line for:", ["Most severe bleeding", "Broken glasses", "Insect bites only", "Blisters only"], 0, "Stop the bleed."),
      q("Declination relates to:", ["Rain", "The difference between magnetic and true north", "Calorie math", "Tinder size"], 1, "Compass work needs it."),
      q("Avoid camping in a dry wash because of:", ["Too many stars", "Flash flood risk", "Better cell signal", "Too much shade"], 1, "Water returns fast."),
      q("Three whistle blasts commonly signal:", ["Victory", "Distress", "Lunch", "Boundary"], 1, "Learn local conventions too."),
      q("Tinder should be:", ["Soaked", "Fine and dry", "A wet log", "A boulder"], 1, "Fire needs a small start."),
      q("If people will search for you, a good default is:", ["Wander randomly at night", "Stay put and signal", "Hide", "Discard your pack"], 1, "Be findable."),
    ],
  },
  {
    slug: "ancient-world",
    title: "The Ancient World",
    blurb: "Rivers, empires, and the first written records.",
    category: "history",
    seriesSlug: "history-foundations",
    expert: "Historians",
    coinsOnComplete: 80,
    questions: [
      q("Mesopotamia sits between which rivers?", ["Nile and Congo", "Tigris and Euphrates", "Danube and Rhine", "Yellow and Yangtze"], 1, "The name means land between rivers."),
      q("Hieroglyphs are most associated with ancient:", ["Greece", "Egypt", "Mongolia", "Inuit cultures of the Arctic exclusively"], 1, "Egyptian writing used hieroglyphs."),
      q("The Roman Republic traditionally began in:", ["509 BCE", "1492", "1066", "476 CE"], 0, "The last king was expelled around 509 BCE."),
      q("Alexander the Great was from:", ["Sparta", "Macedonia", "Carthage", "Persia"], 1, "He inherited the Macedonian kingdom."),
      q("The Great Wall's most famous surviving stone sections date largely from the:", ["Ming dynasty", "Victorian era", "Aztec empire", "Ottoman 20th century"], 0, "Ming-era walls are the iconic ones."),
      q("Cuneiform was pressed into:", ["Silk", "Clay tablets", "Iron coins only", "Papyrus exclusively in Rome"], 1, "Sumerian and later scribes used clay."),
    ],
  },
  {
    slug: "us-history-core",
    title: "U.S. History Core",
    blurb: "Founding documents, expansion, and the Civil War.",
    category: "history",
    seriesSlug: "history-foundations",
    expert: "Historians",
    coinsOnComplete: 80,
    questions: [
      q("The Declaration of Independence was adopted in:", ["1776", "1789", "1812", "1861"], 0, "July 4, 1776 is the traditional date."),
      q("The U.S. Constitution was written in:", ["Philadelphia in 1787", "Boston in 1620", "Richmond in 1861", "New York in 1929"], 0, "The Constitutional Convention met in Philadelphia."),
      q("The Louisiana Purchase was bought from:", ["Spain", "France", "Britain", "Mexico"], 1, "Napoleon's France sold it in 1803."),
      q("The Civil War began in:", ["1861", "1775", "1914", "1941"], 0, "Fort Sumter was 1861."),
      q("The 13th Amendment:", ["Created the Senate", "Abolished slavery", "Gave women the vote", "Prohibited alcohol"], 1, "Ratified in 1865."),
      q("The Bill of Rights is:", ["The first ten amendments", "The Declaration only", "State tax code", "A Civil War treaty"], 0, "It enumerates key liberties."),
    ],
  },
  {
    slug: "world-wars",
    title: "The World Wars",
    blurb: "Alliances, turning points, and how the map changed.",
    category: "history",
    seriesSlug: "history-foundations",
    expert: "Historians",
    coinsOnComplete: 80,
    questions: [
      q("World War I began in:", ["1914", "1939", "1815", "1968"], 0, "The July Crisis followed the assassination in Sarajevo."),
      q("D-Day refers primarily to the 1944 Allied landing in:", ["Normandy, France", "Pearl Harbor", "Stalingrad", "Iwo Jima only"], 0, "Operation Overlord opened a Western Front."),
      q("The U.S. entered World War II after:", ["The fall of Rome in 476", "The attack on Pearl Harbor in 1941", "The Louisiana Purchase", "The moon landing"], 1, "December 7, 1941."),
      q("The Treaty of Versailles is associated with the end of:", ["WWI", "The American Revolution", "The Korean War", "The Cold War"], 0, "It formally ended the war with Germany in 1919."),
      q("The Manhattan Project developed:", ["Radar only", "Nuclear weapons", "Penicillin", "Jet airliners"], 1, "It was a WWII Allied program."),
      q("VE Day commemorates victory in:", ["Europe in 1945", "Vietnam in 1975", "Korea in 1950", "The War of 1812"], 0, "Germany surrendered in May 1945."),
    ],
  },
  {
    slug: "explorers-and-routes",
    title: "Explorers and Trade Routes",
    blurb: "Who went where, and why the oceans became highways.",
    category: "history",
    seriesSlug: "history-foundations",
    expert: "Historians",
    coinsOnComplete: 80,
    questions: [
      q("Zheng He led massive treasure voyages for:", ["Ming China", "Portugal", "The Inca", "Vikings"], 0, "Early 15th century expeditions."),
      q("Magellan's expedition is famous for:", ["The first circumnavigation (completed after his death)", "Discovering Antarctica's capital", "Inventing the compass", "Mapping the Mississippi only"], 0, "One ship made it all the way around."),
      q("The Silk Road was primarily:", ["A single paved highway with one toll", "A network of overland and connected trade routes", "A railroad in 1800", "A Roman aqueduct"], 1, "It linked East Asia with the Mediterranean world."),
      q("Ibn Battuta is known for:", ["Extensive 14th-century travel across the Islamic world and beyond", "Inventing movable type in Mainz", "Commanding at Trafalgar", "Painting the Sistine Chapel"], 0, "His rihla is a major travel account."),
      q("The Columbian Exchange describes:", ["NYSE trading hours", "Transfer of plants, animals, people, and diseases after 1492", "NATO only", "The gold standard of 1971"], 1, "It remade ecologies and societies."),
      q("Vasco da Gama reached India by:", ["Crossing the Pacific from Mexico", "Sailing around Africa", "The Northwest Passage", "The trans-Siberian railway"], 1, "Portugal's Cape route."),
    ],
  },
  {
    slug: "civilizations",
    title: "Civilizations Compared",
    blurb: "Cities, writing, and the habits of complex societies.",
    category: "history",
    seriesSlug: "history-foundations",
    expert: "Historians",
    coinsOnComplete: 80,
    questions: [
      q("A hallmark of many early civilizations is:", ["Zero agriculture", "Cities plus surplus food and specialized labor", "No pottery ever", "Total isolation from rivers"], 1, "Surplus enables specialists."),
      q("The Inca road system was centered in:", ["The Andes", "The Australian Outback", "Scandinavia", "The Congo Basin exclusively"], 0, "It tied a mountain empire together."),
      q("Tenochtitlan was the capital of the:", ["Aztec empire", "Mali empire", "Tokugawa shogunate", "Ottoman Balkans only"], 0, "It stood on an island in Lake Texcoco."),
      q("The printing press associated with Gutenberg spread in Europe in the:", ["1400s", "300s BCE", "1900s only", "2100s"], 0, "Movable type transformed literacy."),
      q("Mansa Musa is associated with:", ["Mali and trans-Saharan gold", "Viking Greenland only", "Meiji Japan", "The California Gold Rush as governor"], 0, "His hajj became legendary for wealth."),
      q("Democracy in classical Athens was:", ["A modern nation-state identical to today", "A limited citizen assembly, excluding women, slaves, and many residents", "A global UN system", "A monarchy with no assemblies"], 1, "It was radical and also exclusionary."),
    ],
  },
  {
    slug: "history-review",
    title: "History Foundations Review",
    blurb: "Earn mastery with 70% or better after completing the pack.",
    category: "history",
    seriesSlug: "history-foundations",
    isReview: true,
    expert: "Historians",
    coinsOnComplete: 120,
    questions: [
      q("The U.S. Constitution was drafted in:", ["1787", "1492", "1914", "2001"], 0, "Philadelphia, 1787."),
      q("WWII for the United States began after:", ["Pearl Harbor", "The Boston Tea Party", "Appomattox", "The moon landing"], 0, "1941."),
      q("Mesopotamia lies between the:", ["Tigris and Euphrates", "Amazon and Nile", "Hudson and Seine", "Ganges and Thames"], 0, "Classic definition."),
      q("The 13th Amendment:", ["Abolished slavery", "Created NASA", "Ended WWI", "Founded the UN"], 0, "1865."),
      q("Zheng He sailed for:", ["Ming China", "Spain under Isabella only", "The Dutch VOC as admiral of Europe", "Hawaii's monarchy"], 0, "Treasure fleets."),
      q("Tenochtitlan was:", ["Aztec capital", "A Viking capital in Iceland", "The Roman forum's nickname", "A WWII code name for Italy only"], 0, "Mexico."),
      q("D-Day 1944 was in:", ["Normandy", "Gettysburg", "Pearl Harbor harbor mouth as a landing", "Moscow"], 0, "France."),
      q("The Columbian Exchange began after:", ["1492 contacts across the Atlantic", "The invention of the iPhone", "The fall of the Berlin Wall", "The Battle of Hastings only"], 0, "Biological and cultural transfer."),
    ],
  },
  {
    slug: "human-body",
    title: "Human Body Basics",
    blurb: "Systems that keep you upright and thinking.",
    category: "science",
    seriesSlug: "science-basics",
    expert: "STEM educators",
    coinsOnComplete: 80,
    questions: [
      q("The primary job of red blood cells is to:", ["Digest fat only", "Carry oxygen", "Store memories", "Produce vitamin D in bone marrow exclusively"], 1, "Hemoglobin binds oxygen."),
      q("The femur is found in the:", ["Skull", "Thigh", "Wrist", "Ear"], 1, "It is the thigh bone."),
      q("Insulin helps regulate:", ["Blood glucose", "Hair color", "Echo location", "Tidal volume of the ocean"], 0, "It is a pancreatic hormone."),
      q("The alveoli are where:", ["Food is chewed", "Gas exchange happens in the lungs", "Urine is stored", "Antibodies are bones"], 1, "Tiny air sacs."),
      q("Neurons communicate across synapses using:", ["Only sound waves", "Chemical neurotransmitters (and electrical signals within the cell)", "Photosynthesis", "Plate tectonics"], 1, "Electrochemical signaling."),
      q("Skin is part of the:", ["Integumentary system", "Only the digestive system", "Only the skeletal system", "Atmosphere"], 0, "Barrier and temperature roles."),
    ],
  },
  {
    slug: "earth-science",
    title: "Earth Science",
    blurb: "Rocks, weather, and a restless crust.",
    category: "science",
    seriesSlug: "science-basics",
    expert: "STEM educators",
    coinsOnComplete: 80,
    questions: [
      q("Earth's inner core is:", ["Liquid water", "Primarily solid iron-nickel", "Pure oxygen ice", "Empty"], 1, "Extreme pressure keeps it solid."),
      q("Tectonic plates move because of:", ["Moonlight friction only", "Mantle convection and related forces", "Airline traffic", "Coral growth"], 1, "The mantle is not static."),
      q("Igneous rocks form from:", ["Cooled magma or lava", "Only compressed mud with no heat ever", "Evaporated plastic", "Clouds"], 0, "Granite and basalt are examples."),
      q("The greenhouse effect is:", ["Glasshouses only", "Atmospheric gases trapping outgoing heat", "The ozone hole's other name", "Earth's magnetic field"], 1, "Water vapor and CO2 matter."),
      q("A hurricane's energy comes mainly from:", ["Cold desert air", "Warm ocean water", "Earthquakes", "Auroras"], 1, "Latent heat from evaporation."),
      q("Fossils are most commonly found in:", ["Igneous granite freshly cooled", "Sedimentary rock", "Pure gold veins only", "The ozone layer"], 1, "Sediments bury remains."),
    ],
  },
  {
    slug: "space-basics",
    title: "Space Basics",
    blurb: "A modest tour of the neighborhood.",
    category: "science",
    seriesSlug: "science-basics",
    expert: "STEM educators",
    coinsOnComplete: 80,
    questions: [
      q("The Sun is a:", ["Planet", "Star", "Comet", "Black hole we live inside"], 1, "A G-type main-sequence star."),
      q("A light-year measures:", ["Brightness", "Distance", "Mass of the Moon", "Temperature of Mars"], 1, "How far light travels in a year."),
      q("Earth's seasons are caused mainly by:", ["Changing distance to the Sun alone", "Axial tilt", "Lunar eclipses monthly", "Jupiter's shadow"], 1, "Tilt changes sunlight angle and day length."),
      q("Saturn is famous for:", ["Liquid surface water oceans for cities", "A prominent ring system", "Being the closest star", "Having no moons"], 1, "Ice and rock rings."),
      q("The Moon's gravity is the main driver of:", ["Earth's daily rotation", "Most ocean tides", "Continental color", "The ozone layer"], 1, "The Sun also contributes."),
      q("A galaxy is:", ["A single planet", "A vast system of stars, gas, and dust", "An asteroid", "A meteor shower"], 1, "The Milky Way is ours."),
    ],
  },
  {
    slug: "chemistry-kitchen",
    title: "Chemistry You Can Taste",
    blurb: "Atoms, reactions, and the science of everyday stuff.",
    category: "science",
    seriesSlug: "science-basics",
    expert: "STEM educators",
    coinsOnComplete: 80,
    questions: [
      q("pH below 7 means a solution is:", ["Acidic", "Exactly neutral", "A noble gas", "A metal crystal"], 0, "Acids donate protons."),
      q("Water's chemical formula is:", ["CO2", "H2O", "NaCl", "O3"], 1, "Two hydrogen, one oxygen."),
      q("Rusting of iron is an example of:", ["Oxidation", "Nuclear fission in the backyard", "Sublimation of salt", "Photosynthesis"], 0, "Iron reacts with oxygen."),
      q("Table salt is primarily:", ["Sodium chloride", "Pure gold", "Methane", "Helium"], 0, "NaCl."),
      q("A catalyst:", ["Is always used up as a reactant", "Speeds a reaction without being consumed as a reactant", "Stops all motion", "Is another name for an acid"], 1, "Enzymes are biological catalysts."),
      q("Carbon is special in organic chemistry because it:", ["Cannot bond", "Forms four bonds and long chains", "Is a noble gas", "Has no electrons"], 1, "That versatility is the backbone of life."),
    ],
  },
  {
    slug: "biology-101",
    title: "Biology 101",
    blurb: "Cells, genes, and why evolution is not a rumor.",
    category: "science",
    seriesSlug: "science-basics",
    expert: "STEM educators",
    coinsOnComplete: 80,
    questions: [
      q("The basic unit of life is the:", ["Atom of gold", "Cell", "Organ only", "Biome only"], 1, "Cells make tissues."),
      q("DNA's role is to:", ["Store genetic information", "Digest only cellulose in humans as its only job", "Carry oxygen like hemoglobin exclusively", "Form the cell wall of animals"], 0, "Sequence of bases encodes genes."),
      q("Photosynthesis occurs mainly in:", ["Animal muscle", "Chloroplasts of plants and algae", "Human liver", "Granite"], 1, "Light to chemical energy."),
      q("Natural selection requires:", ["Variation, heredity, and differential success", "A committee vote", "Identical clones only", "No environment"], 0, "Darwin's core insight."),
      q("Mitochondria are often called the cell's:", ["Powerhouses", "Libraries of the nucleus only", "Cell walls", "Vacuoles of plants exclusively as a nickname"], 0, "They produce ATP."),
      q("Antibiotics target:", ["Viruses as their original design in every case", "Bacteria (typically)", "Broken bones", "Starlight"], 1, "Viruses need other tools."),
    ],
  },
  {
    slug: "science-review",
    title: "Science Basics Review",
    blurb: "70% or better unlocks the Certificate of Mastery for this pack.",
    category: "science",
    seriesSlug: "science-basics",
    isReview: true,
    expert: "STEM educators",
    coinsOnComplete: 120,
    questions: [
      q("Red blood cells mainly:", ["Carry oxygen", "Store fat only", "Form enamel", "Pump the heart valves as muscle"], 0, "Hemoglobin."),
      q("Earth seasons come from:", ["Axial tilt", "Monthly black holes", "The stock market", "Coral bleaching alone"], 0, "Tilt."),
      q("H2O is:", ["Salt", "Water", "Ozone", "Rust"], 1, "Water."),
      q("Sedimentary rock is where we often find:", ["Fossils", "The inner core", "The ozone hole", "Neutron stars"], 0, "Burial and layers."),
      q("A light-year is a unit of:", ["Distance", "Time of day on Mars clocks only", "Mass", "Temperature"], 0, "Distance."),
      q("Cells are:", ["The basic unit of life", "Always visible without microscopes as houses", "Stars", "Tectonic plates"], 0, "Biology starts here."),
      q("A catalyst:", ["Speeds a reaction", "Is a type of hurricane", "Is Earth's core", "Is a bone"], 0, "Not consumed as a reactant."),
      q("Insulin regulates:", ["Blood glucose", "Tides", "Galaxies", "Igneous cooling rates"], 0, "Hormone."),
    ],
  },
  {
    slug: "sports-rules",
    title: "Sports Rules That Matter",
    blurb: "A fast pass through the games people actually argue about.",
    category: "sports",
    coinsOnComplete: 70,
    questions: [
      q("In American football, a touchdown is worth:", ["3 points", "6 points", "2 points before extras", "1 point"], 1, "Then PAT or two-point try."),
      q("A soccer (association football) match is typically:", ["Two halves of 45 minutes plus stoppage", "Nine innings", "Four 12-minute quarters only as FIFA default", "A single 20-minute period"], 0, "The referee adds time."),
      q("In basketball, a shot from beyond the arc is worth:", ["2 points", "3 points", "4 points", "1 point"], 1, "The three-point line."),
      q("A marathon is officially:", ["26.2 miles (42.195 km)", "10 km", "100 miles", "1 mile"], 0, "Olympic standard."),
      q("In baseball, three strikes typically mean:", ["A walk", "An out", "A home run", "Extra innings immediately"], 1, "Strikeout."),
      q("Offside in soccer is judged at the moment:", ["The goalkeeper blinks", "The ball is played by a teammate", "The referee drinks water", "Halftime starts"], 1, "Position when the ball is played."),
    ],
  },
  {
    slug: "film-and-story",
    title: "Film Craft, Not Gossip",
    blurb: "How movies are built, from shots to scores.",
    category: "entertainment",
    coinsOnComplete: 70,
    questions: [
      q("A close-up typically shows:", ["A whole city from orbit", "A face or small detail", "Only the credits", "The catering table"], 1, "It directs attention."),
      q("Diegetic sound is:", ["Sound the characters could hear in their world", "Only the studio logo sting", "Silence", "The director's commentary on the Blu-ray exclusively"], 0, "Vs. non-diegetic score."),
      q("A montage is:", ["A single unedited 3-hour take always", "A sequence of shots compressing time or building an idea", "A type of camera battery", "The legal department"], 1, "Eisenstein to Rocky training."),
      q("Aspect ratio describes:", ["Ticket price", "Frame width vs height", "Actor age", "Film budget only"], 1, "1.85:1, 2.39:1, etc."),
      q("A MacGuffin is:", ["A lighting gel", "An object that motivates the plot more than its own details", "A union rule", "A type of boom mic"], 1, "Hitchcock popularized the term."),
      q("Continuity editing aims to:", ["Make geography and time feel coherent", "Randomize every cut", "Remove all sound", "Film only in IMAX by law"], 0, "Invisible craft."),
    ],
  },
  {
    slug: "home-repair",
    title: "DIY Without the Disaster",
    blurb: "The boring skills that save a Saturday.",
    category: "diy",
    coinsOnComplete: 70,
    questions: [
      q("Before drilling into a wall, you should:", ["Guess", "Check for wires and pipes", "Use water on the bit as a default for drywall", "Remove the circuit breaker panel entirely"], 1, "Stud finders and caution."),
      q("A GFCI outlet is designed to:", ["Increase voltage", "Cut power if it detects a ground fault", "Charge phones wirelessly", "Replace smoke alarms"], 1, "Kitchens, baths, outdoors."),
      q("Pilot holes help when driving screws because they:", ["Paint the wood", "Reduce splitting and wandering", "Magnetize the house", "Replace anchors in concrete always"], 1, "Especially near edges."),
      q("The main shutoff for a home water leak is often:", ["The roof vent", "Near where the supply enters, or at the meter", "The doorbell transformer", "The chimney cap"], 1, "Know it before you need it."),
      q("PPE for grinding metal should include:", ["Open-toe sandals", "Eye protection", "A wool scarf in the wheel", "No hearing protection ever"], 1, "Eyes first."),
      q("A stud is typically spaced (in many U.S. houses):", ["Every 16 or 24 inches on center", "Every 8 feet exactly always", "Randomly", "Only in the attic"], 0, "Confirm, do not assume."),
    ],
  },
  {
    slug: "engines-and-roads",
    title: "Engines and the Open Road",
    blurb: "What that noise might mean, and a little history.",
    category: "cars",
    coinsOnComplete: 70,
    questions: [
      q("A four-stroke engine cycle is:", ["Intake, compression, power, exhaust", "Only exhaust twice", "Steam, then coal", "Charge, then skip"], 0, "Otto cycle in gasoline engines."),
      q("ABS is meant to:", ["Always shorten stopping distance on every surface equally", "Help you retain steering while braking hard by limiting lockup", "Increase horsepower", "Replace brake pads automatically"], 1, "Anti-lock braking."),
      q("Tire pressure should be set:", ["By the sidewall maximum as the daily target always", "To the vehicle placard, usually on the door jamb", "To zero in winter", "By kicking only"], 1, "Sidewall max is not the fill spec."),
      q("A hybrid typically combines:", ["Sail and steam only", "An internal combustion engine and electric motor(s)", "Two diesel aircraft engines", "Only regenerative brakes with no battery"], 1, "Many architectures exist."),
      q("Catalytic converters reduce:", ["Tire noise", "Certain exhaust pollutants", "Radio static only", "Cabin humidity as their main job"], 1, "They need to be hot to work well."),
      q("Overheating after a lost serpentine belt can happen because:", ["The belt often drives the water pump", "Belts cool the cabin by magic", "Gasoline freezes", "ABS disables the radiator"], 0, "Know what your belt drives."),
    ],
  },
  {
    slug: "scripture-places",
    title: "People and Places in Scripture",
    blurb: "A respectful knowledge quiz, not a sermon.",
    category: "bible",
    coinsOnComplete: 70,
    questions: [
      q("The Exodus narrative is set as a departure from:", ["Rome", "Egypt", "Babylon as the only setting", "Nineveh exclusively"], 1, "Moses and the Israelites."),
      q("Bethlehem is associated in the Gospels with:", ["The birth of Jesus", "The building of the Parthenon", "Paul's shipwreck only", "The Council of Nicaea"], 0, "Matthew and Luke."),
      q("The Jordan River is significant as:", ["A setting of crossing and baptism narratives", "The capital of Persia", "A desert in Arabia with no water", "A mountain in Sinai only"], 0, "Geography of the Levant."),
      q("King David is traditionally associated with:", ["Athens", "Jerusalem", "Rome's founding as first emperor", "Mecca as a Biblical king"], 1, "The united monarchy tradition."),
      q("Paul's letters are part of the:", ["New Testament", "Analects of Confucius", "U.S. Constitution", "Epic of Gilgamesh"], 0, "Epistles."),
      q("The Psalms are primarily:", ["Legal tax tables", "Poems and songs", "Roman military manuals", "Ship logs"], 1, "Worship poetry."),
    ],
  },
  {
    slug: "secret-odd-knowledge",
    title: "Secret Quiz: Odd Knowledge",
    blurb: "The weirdly useful facts we keep off the homepage.",
    category: "general-knowledge",
    isSecret: true,
    coinsOnComplete: 150,
    questions: [
      q("A baker's dozen is:", ["12", "13", "11", "24"], 1, "Traditional extra roll."),
      q("The QWERTY layout was designed in the era of:", ["Touchscreens", "Typewriters", "Quantum computers", "Carrier pigeons as keyboards"], 1, "To manage jamming, among other debates."),
      q("Zero as a number concept in South Asia is associated with scholars such as:", ["Brahmagupta", "Homer", "Euclid only as the inventor of zero", "Newton as a child"], 0, "Indian mathematics was pivotal."),
      q("The international distress call Mayday comes from:", ["Spanish for help", "French m'aider (help me)", "A pirate code", "Morse for Z"], 1, "Aviation and marine radio."),
      q("UTC is:", ["A U.S. tax code only", "Coordinated Universal Time", "A type of engine oil", "A basketball defense"], 1, "Civil time's backbone."),
      q("A palindrome reads the same:", ["In Morse only", "Forward and backward", "In pig latin only", "Upside down always"], 1, "Like racecar."),
    ],
  },
  {
    slug: "secret-brain-teasers",
    title: "Secret Quiz: Careful Thinking",
    blurb: "Premium-feeling puzzles. Ads for free accounts; quiet for members.",
    category: "general-knowledge",
    isSecret: true,
    coinsOnComplete: 150,
    questions: [
      q("If all bloops are razzes and some razzes are zings, which must be true?", ["Some bloops are zings", "No bloops are razzes", "All bloops are razzes, so bloops are a kind of razz; zings may or may not overlap bloops", "All zings are bloops"], 2, "The overlap with zings is not guaranteed."),
      q("A fair coin flipped twice. Probability of two heads:", ["1/2", "1/3", "1/4", "1"], 2, "HH is one of four equally likely outcomes."),
      q("The next number in 2, 3, 5, 8, 13 is:", ["18", "21", "20", "15"], 1, "Fibonacci-style sums."),
      q("You have a 3- and 5-minute hourglass. To measure 4 minutes you can:", ["Run them in overlapping starts (classic puzzle pattern)", "It is impossible", "Break both", "Use only the 3 twice and ignore the 5"], 0, "Classic water-clock style timing."),
      q("Correlation is not:", ["A statistic people compute", "Causation", "A word", "Used in science"], 1, "Third variables exist."),
      q("Occam's razor suggests preferring:", ["The most supernatural extra parts", "Explanations that do not multiply entities without need", "The longest essay", "Whoever shouts"], 1, "A heuristic, not a proof."),
    ],
  },
];

export const SERIES: Series[] = [
  {
    slug: "geography-1",
    title: "Geography 1",
    description: "Cities, states, capitals, and countries. Finish the pack and pass the review to master the topic.",
    category: "geography",
    quizSlugs: [
      "worlds-largest-cities",
      "us-states",
      "latin-america",
      "us-capitals",
      "european-countries",
    ],
    reviewSlug: "geography-review",
    masteryThreshold: 70,
  },
  {
    slug: "survival-essentials",
    title: "Survival Essentials",
    description: "Shelter, water, fire, first aid, and staying found — written in the spirit of field instruction.",
    category: "survival",
    quizSlugs: [
      "wilderness-essentials",
      "shelter-building",
      "water-and-fire",
      "field-first-aid",
      "navigation-basics",
    ],
    reviewSlug: "survival-review",
    masteryThreshold: 70,
  },
  {
    slug: "history-foundations",
    title: "History Foundations",
    description: "Ancient worlds, U.S. civics, global conflict, and the routes that connected them.",
    category: "history",
    quizSlugs: [
      "ancient-world",
      "us-history-core",
      "world-wars",
      "explorers-and-routes",
      "civilizations",
    ],
    reviewSlug: "history-review",
    masteryThreshold: 70,
  },
  {
    slug: "science-basics",
    title: "Science Basics",
    description: "Body, planet, sky, matter, and life — a gym for the scientific mind.",
    category: "science",
    quizSlugs: [
      "human-body",
      "earth-science",
      "space-basics",
      "chemistry-kitchen",
      "biology-101",
    ],
    reviewSlug: "science-review",
    masteryThreshold: 70,
  },
];

const DAILY_BANK: { prompt: string; choices: string[]; answerIndex: number; explanation: string }[] = [
  q("Which planet is known for its Great Red Spot?", ["Mars", "Jupiter", "Venus", "Mercury"], 1, "A long-lived anticyclonic storm."),
  q("The chemical symbol for gold is:", ["Ag", "Au", "Gd", "Go"], 1, "From Latin aurum."),
  q("Mount Everest lies on the border of Nepal and:", ["India only", "China (Tibet)", "Bhutan only", "Pakistan"], 1, "The summit ridge is the border."),
  q("Shakespeare wrote:", ["The Odyssey", "Hamlet", "The Aeneid", "Beowulf as original author"], 1, "A tragedy."),
  q("The Pacific is:", ["The smallest ocean", "The largest ocean", "A sea in Europe", "A river"], 1, "By far the largest."),
  q("A heptagon has how many sides?", ["5", "6", "7", "8"], 2, "Hepta means seven."),
  q("The author of Pride and Prejudice is:", ["Charlotte Brontë", "Jane Austen", "George Eliot", "Mary Shelley"], 1, "Published 1813."),
  q("Sound travels fastest through:", ["Vacuum", "Steel (typically vs air)", "Outer space", "A perfect vacuum on Earth"], 1, "Solids generally beat gases."),
  q("The capital of Canada is:", ["Toronto", "Ottawa", "Vancouver", "Montreal"], 1, "Ottawa, Ontario."),
  q("Photosynthesis releases:", ["Nitrogen as the main product people cite", "Oxygen", "Helium", "Crude oil"], 1, "From splitting water."),
  q("A marathon is officially:", ["26.2 miles", "25 miles", "30 kilometers exactly", "50 miles"], 0, "26 miles and 385 yards."),
  q("The primary colors of light (additive) are:", ["Red, yellow, blue", "Red, green, blue", "Cyan, magenta, yellow", "Black, white, gray"], 1, "RGB mixing makes white."),
  q("The Nile's two major tributaries meet near:", ["Cairo only", "Khartoum", "Alexandria", "Aswan exclusively"], 1, "The Blue and White Nile meet at Khartoum."),
  q("Penicillin was famously isolated from:", ["Algae", "Mold", "Sand", "Coal tar only"], 1, "A Penicillium mold."),
  q("The smallest prime number is:", ["0", "1", "2", "3"], 2, "2 is the only even prime."),
  q("Hertz measure:", ["Mass", "Frequency", "Temperature", "Luminous intensity"], 1, "Cycles per second."),
  q("The Great Barrier Reef is off:", ["California", "Queensland, Australia", "Norway", "Kenya"], 1, "It sits in the Coral Sea."),
  q("HTML is primarily a:", ["Database", "Markup language", "Operating system", "Compiler"], 1, "HyperText Markup Language."),
  q("The boiling point of water at standard pressure is:", ["0°C", "32°C", "100°C", "212°C only in Celsius"], 2, "100 degrees Celsius."),
];

export function getDailyQuiz(now = new Date()): Quiz {
  const start = new Date(Date.UTC(now.getUTCFullYear(), 0, 0));
  const utc = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate());
  const day = Math.floor((utc - start.getTime()) / 86400000);
  const questions = Array.from({ length: DAILY_LENGTH }, (_, offset) => {
    return DAILY_BANK[(day * 3 + offset) % DAILY_BANK.length];
  });
  const dateLabel = now.toISOString().slice(0, 10);
  return {
    slug: `daily-${dateLabel}`,
    title: `Quiz of the Day — ${dateLabel}`,
    blurb: "Ten fresh questions every UTC day. Streak your mind, not your screen time.",
    category: "general-knowledge",
    isDaily: true,
    coinsOnComplete: 90,
    questions,
  };
}

export function getCategory(slug: string) {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function getQuiz(slug: string) {
  if (slug.startsWith("daily-")) return getDailyQuiz();
  return QUIZZES.find((q) => q.slug === slug);
}

export function getSeries(slug: string) {
  return SERIES.find((s) => s.slug === slug);
}

export function quizzesInCategory(slug: string) {
  return QUIZZES.filter((q) => q.category === slug && !q.isSecret);
}

export function seriesInCategory(slug: string) {
  return SERIES.filter((s) => s.category === slug);
}

export function getSeriesForQuiz(quiz: Quiz) {
  if (!quiz.seriesSlug) return undefined;
  return getSeries(quiz.seriesSlug);
}

export const SECRET_QUIZZES = QUIZZES.filter((q) => q.isSecret);
export const FEATURED_EXPERTS = [
  { category: "survival", name: "Field instructors", line: "Priorities, not panics." },
  { category: "history", name: "Working historians", line: "Sources over slogans." },
  { category: "science", name: "STEM educators", line: "Mechanisms, not myths." },
];
