import type { EBook } from "./types";

export const BIBLE_FOUNDATIONS_EBOOK: EBook = {
  slug: "bible-foundations",
  title: "Bible Foundations",
  subtitle: "100 Essential Scripture Facts Every Reader Should Know",
  author: "Lampstand Editorial Desk",
  publicationDate: "2026 Edition",
  coverImage: "/images/ebooks/bible-foundations-cover.png",
  readingTimeMinutes: 25,
  description:
    "An illustrated, easy-to-understand reference guide covering the 100 fundamental facts of biblical history, major figures, covenant theology, Gospels, early Church growth, and ancient geography.",
  chapters: [
    {
      id: "ch1-patriarchs-exodus",
      number: 1,
      title: "Patriarchs, Exodus & The Law",
      subtitle: "From Creation to the Promised Land",
      image: "/images/ebooks/ch1-patriarchs.png",
      description:
        "The foundational narratives of Genesis and Exodus — covenants, patriarchs, deliverance from Egypt, and the giving of the Law at Sinai.",
      facts: [
        {
          id: 1,
          title: "Genesis Means 'Origin' or 'Beginning'",
          fact: "The first book of the Hebrew Bible and Old Testament takes its English name from the Greek Genesis, meaning origin or birth.",
          explanation: "Genesis sets the framework for all Scripture, opening with the creation of the cosmos, humanity in Eden, the fall, and God's covenant promises.",
          biblicalReference: "Genesis 1:1",
          category: "patriarchs",
        },
        {
          id: 2,
          title: "Noah & The Covenant of the Rainbow",
          fact: "Following the flood, God established a covenant with Noah, sealed with the rainbow as a pledge never to destroy all flesh by flood again.",
          explanation: "Noah built an ark according to divine instructions to preserve his family and animal life during the catastrophic waters.",
          biblicalReference: "Genesis 9:12–17",
          category: "patriarchs",
        },
        {
          id: 3,
          title: "Abraham's Call from Ur",
          fact: "Abram was called out of Ur of the Chaldeans to journey to Canaan, receiving promises of land, offspring, and global blessing.",
          explanation: "Abraham is considered the father of faith, responding in obedience to God's covenant call at age seventy-five.",
          biblicalReference: "Genesis 12:1–3",
          category: "patriarchs",
        },
        {
          id: 4,
          title: "The Binding of Isaac (Akedah)",
          fact: "Abraham was tested at Mount Moriah when commanded to offer his son Isaac, where a ram was provided as a substitute.",
          explanation: "This event foreshadows sacrificial atonement and demonstrates Abraham's unwavering trust in God's promises.",
          biblicalReference: "Genesis 22:1–14",
          category: "patriarchs",
        },
        {
          id: 5,
          title: "Jacob Renamed Israel",
          fact: "Jacob wrestled with a divine messenger at Penuel and was renamed Israel, meaning 'struggles with God'.",
          explanation: "Israel's twelve sons became the ancestral heads of the Twelve Tribes of Israel.",
          biblicalReference: "Genesis 32:28",
          category: "patriarchs",
        },
        {
          id: 6,
          title: "Joseph's Coat & Egyptian Exiles",
          fact: "Joseph was sold into slavery by his brothers, rose to second-in-command over Egypt through dream interpretation, and saved his family from famine.",
          explanation: "Joseph famously declared to his brothers: 'You intended to harm me, but God intended it for good.'",
          biblicalReference: "Genesis 50:20",
          category: "patriarchs",
        },
        {
          id: 7,
          title: "Moses & The Burning Bush at Mount Horeb",
          fact: "God revealed His covenant name 'I AM WHO I AM' (Yahweh) to Moses out of a burning bush that was not consumed.",
          explanation: "Moses was commissioned to return to Egypt to demand Pharaoh release the enslaved Israelites.",
          biblicalReference: "Exodus 3:14",
          category: "patriarchs",
        },
        {
          id: 8,
          title: "The Ten Plagues & Passover",
          fact: "The tenth plague—death of the firstborn—led to the institution of Passover, where blood on doorposts spared Israelite homes.",
          explanation: "Passover remains the foundational deliverance festival commemorating redemption from Egyptian bondage.",
          biblicalReference: "Exodus 12:11–13",
          category: "patriarchs",
        },
        {
          id: 9,
          title: "Crossing the Red Sea (Yam Suph)",
          fact: "Moses stretched out his staff, and God parted the Red Sea, allowing Israel to walk through on dry land before the Egyptian army was swallowed.",
          explanation: "This event stands as the supreme Old Testament act of divine salvation and liberation.",
          biblicalReference: "Exodus 14:21–29",
          category: "patriarchs",
        },
        {
          id: 10,
          title: "The Ten Commandments (Decalogue)",
          fact: "Given on two stone tablets at Mount Sinai, the Ten Commandments outline duties toward God (first four) and neighbor (last six).",
          explanation: "The Decalogue forms the moral cornerstone of the Mosaic Law given to the nation of Israel.",
          biblicalReference: "Exodus 20:1–17",
          category: "patriarchs",
        },
        {
          id: 11,
          title: "Manna & Quail in the Wilderness",
          fact: "During forty years of desert wanderings, God fed Israel daily with bread from heaven called manna and evening quail.",
          explanation: "Manna rained down six days a week, with a double portion on Friday to honor the Sabbath day.",
          biblicalReference: "Exodus 16:14–35",
          category: "patriarchs",
        },
        {
          id: 12,
          title: "The Tabernacle & The Ark of the Covenant",
          fact: "The Tabernacle was a portable sanctuary built according to heavenly specifications, housing the Ark of the Covenant in the Most Holy Place.",
          explanation: "The Ark contained the stone tablets, Aaron's budded staff, and a jar of manna beneath the mercy seat.",
          biblicalReference: "Exodus 25:10–22",
          category: "patriarchs",
        },
        {
          id: 13,
          title: "Leviticus & The Day of Atonement (Yom Kippur)",
          fact: "Once a year, the High Priest entered the Holy of Holies to offer blood for national sins and send away a scapegoat into the wilderness.",
          explanation: "Leviticus emphasizes holiness: 'Be holy, for I am holy.'",
          biblicalReference: "Leviticus 16:15–22",
          category: "patriarchs",
        },
        {
          id: 14,
          title: "Numbers & The Twelve Spies",
          fact: "Twelve spies surveyed Canaan for forty days; only Joshua and Caleb returned with a faithful report urging conquest.",
          explanation: "Because of disbelief, the wilderness wandering was extended to forty years until a new generation arose.",
          biblicalReference: "Numbers 13:30–33",
          category: "patriarchs",
        },
        {
          id: 15,
          title: "The Bronze Serpent",
          fact: "When venomous snakes bit rebellious Israelites, Moses lifted a bronze serpent on a pole, and all who looked upon it lived.",
          explanation: "Jesus cited this event in John 3:14 as a picture of His own crucifixion.",
          biblicalReference: "Numbers 21:8–9",
          category: "patriarchs",
        },
        {
          id: 16,
          title: "Deuteronomy & The Shema",
          fact: "Deuteronomy 6:4 contains the central confession of Judaism: 'Hear, O Israel: The LORD our God, the LORD is one.'",
          explanation: "Moses delivered these farewell discourses on the plains of Moab before his death on Mount Nebo.",
          biblicalReference: "Deuteronomy 6:4–5",
          category: "patriarchs",
        },
        {
          id: 17,
          title: "Joshua & The Fall of Jericho",
          fact: "Israel crossed the Jordan River into Canaan, and the walls of Jericho collapsed after priests blew trumpets on the seventh day.",
          explanation: "Rahab the innkeeper sheltered the Hebrew spies and was spared, entering the lineage of David and Jesus.",
          biblicalReference: "Joshua 6:20",
          category: "patriarchs",
        },
        {
          id: 18,
          title: "The Period of the Judges",
          fact: "Before Israel had kings, military leaders called Judges (such as Deborah, Gideon, and Samson) delivered Israel from oppressors.",
          explanation: "The book of Judges records a repeating cycle: Sin -> Oppression -> Repentance -> Deliverance.",
          biblicalReference: "Judges 2:16–19",
          category: "patriarchs",
        },
        {
          id: 19,
          title: "Ruth the Moabite",
          fact: "Ruth demonstrated steadfast loyalty to her mother-in-law Naomi ('Where you go I will go'), married Boaz, and became great-grandmother to King David.",
          explanation: "Ruth highlights God's grace extending beyond national boundaries to Gentiles.",
          biblicalReference: "Ruth 1:16, 4:17",
          category: "patriarchs",
        },
        {
          id: 20,
          title: "Samuel the Prophet & Anointing Kings",
          fact: "Samuel was dedicated to God as a child in Shiloh and grew up to be Israel's last judge and prophet who anointed both Saul and David.",
          explanation: "Samuel warned Israel about the burdens of monarchy when they demanded a king 'like all the nations'.",
          biblicalReference: "1 Samuel 8:10–18",
          category: "patriarchs",
        },
      ],
    },
    {
      id: "ch2-prophets-kings",
      number: 2,
      title: "Kings, Prophets & Poetic Writings",
      subtitle: "The Monarchy, Temple, Exile & Wisdom Literature",
      image: "/images/ebooks/ch1-patriarchs.png",
      description:
        "The rise of David, Solomon's Temple, the split kingdom, the major and minor prophets, and the Psalms of Israel.",
      facts: [
        {
          id: 21,
          title: "King David & Goliath",
          fact: "Young David defeated the Philistine champion Goliath using a sling and five smooth stones, trusting in God rather than armor.",
          explanation: "David was anointed king by Samuel as 'a man after God's own heart'.",
          biblicalReference: "1 Samuel 17:45–50",
          category: "prophets",
        },
        {
          id: 22,
          title: "Jerusalem Made David's Capital",
          fact: "David captured the fortress of Zion (Jerusalem) from the Jebusites and brought the Ark of the Covenant there with dancing.",
          explanation: "Jerusalem became known as the City of David and the spiritual center of Israel.",
          biblicalReference: "2 Samuel 5:6–10",
          category: "prophets",
        },
        {
          id: 23,
          title: "The Davidic Covenant",
          fact: "God promised David that his royal line and kingdom would endure forever.",
          explanation: "Christians identify Jesus of Nazareth as the fulfillment of the Davidic eternal throne.",
          biblicalReference: "2 Samuel 7:12–16",
          category: "prophets",
        },
        {
          id: 24,
          title: "Solomon's Wisdom & Building the Temple",
          fact: "King Solomon prayed for wisdom to govern Israel, constructed the First Temple in Jerusalem over seven years, and welcomed the Queen of Sheba.",
          explanation: "Solomon's reign marked the golden economic and architectural age of united Israel.",
          biblicalReference: "1 Kings 3:9, 6:1–38",
          category: "prophets",
        },
        {
          id: 25,
          title: "Division of the Kingdom (930 BC)",
          fact: "Following Solomon's death, Israel split into the Northern Kingdom (Israel, 10 tribes) and Southern Kingdom (Judah, 2 tribes).",
          explanation: "Jeroboam ruled Israel in Samaria while Rehoboam ruled Judah in Jerusalem.",
          biblicalReference: "1 Kings 12:16–20",
          category: "prophets",
        },
        {
          id: 26,
          title: "Elijah on Mount Carmel",
          fact: "The prophet Elijah challenged 450 prophets of Baal to a contest of fire, proving Yahweh is the true God when fire consumed his water-soaked altar.",
          explanation: "Elijah was later taken up to heaven in a chariot of fire.",
          biblicalReference: "1 Kings 18:36–39, 2 Kings 2:11",
          category: "prophets",
        },
        {
          id: 27,
          title: "Elisha's Double Portion",
          fact: "Elisha succeeded Elijah, performing miracles including multiplying oil for a widow, healing Naaman's leprosy, and raising a Shunammite's son.",
          explanation: "Elisha requested and received a double portion of Elijah's prophetic spirit.",
          biblicalReference: "2 Kings 2:9–15",
          category: "prophets",
        },
        {
          id: 28,
          title: "Fall of Samaria to Assyria (722 BC)",
          fact: "The Northern Kingdom of Israel was conquered by the Assyrian Empire under Sargon II, resulting in the dispersion of the ten northern tribes.",
          explanation: "Prophets like Amos and Hosea had warned Israel of impending judgment due to idolatry and social injustice.",
          biblicalReference: "2 Kings 17:5–6",
          category: "prophets",
        },
        {
          id: 29,
          title: "Isaiah's Vision & Messianic Prophecies",
          fact: "Isaiah saw the Lord high and exalted in the Temple (Isaiah 6) and prophesied the Virgin Birth (7:14) and Suffering Servant (Isaiah 53).",
          explanation: "Isaiah is often called the 'Evangelical Prophet' because of his abundant prophecies fulfilled in Christ.",
          biblicalReference: "Isaiah 6:1–8, 53:4–6",
          category: "prophets",
        },
        {
          id: 30,
          title: "King Hezekiah & The Assyrian Siege",
          fact: "When Sennacherib besieged Jerusalem, Hezekiah prayed in the Temple, and an angel struck down 185,000 Assyrian soldiers in one night.",
          explanation: "Hezekiah built the famous Siloam Tunnel to secure Jerusalem's water supply during the siege.",
          biblicalReference: "2 Kings 19:35",
          category: "prophets",
        },
        {
          id: 31,
          title: "Josiah's Reform & The Rediscovered Law",
          fact: "King Josiah renovated the Temple, rediscovered the Book of the Law, tore his clothes in repentance, and renewed the covenant across Judah.",
          explanation: "Josiah removed pagan high places and restored the national celebration of Passover.",
          biblicalReference: "2 Kings 22:8–13",
          category: "prophets",
        },
        {
          id: 32,
          title: "Jeremiah the Weeping Prophet",
          fact: "Jeremiah prophesied the fall of Jerusalem, endured imprisonment in a cistern, and foresaw a coming 'New Covenant' written on human hearts.",
          explanation: "Jeremiah wrote the book of Lamentations mourning the destruction of Jerusalem.",
          biblicalReference: "Jeremiah 31:31–34",
          category: "prophets",
        },
        {
          id: 33,
          title: "Fall of Jerusalem & Babylonian Exile (586 BC)",
          fact: "King Nebuchadnezzar of Babylon destroyed Solomon's Temple, tore down Jerusalem's walls, and carried Judah into 70 years of exile.",
          explanation: "This cataclysm forced Israel to preserve their holy writings and worship without a central temple.",
          biblicalReference: "2 Kings 25:8–12",
          category: "prophets",
        },
        {
          id: 34,
          title: "Ezekiel's Vision of Dry Bones",
          fact: "In exile in Babylon, Ezekiel saw a valley of dry bones come together, breath enter them, and stand up as a vast army.",
          explanation: "This vision symbolized God's promise of national resurrection and spiritual restoration for Israel.",
          biblicalReference: "Ezekiel 37:1–14",
          category: "prophets",
        },
        {
          id: 35,
          title: "Daniel in the Lions' Den & The Fiery Furnace",
          fact: "Daniel was preserved unharmed in a den of hungry lions after praying to God, while his three companions survived Nebuchadnezzar's fiery furnace.",
          explanation: "Daniel served faithfully in the courts of Babylonian and Persian emperors.",
          biblicalReference: "Daniel 3:24–27, 6:16–23",
          category: "prophets",
        },
        {
          id: 36,
          title: "Return under Cyrus & Rebuilding the Temple (538 BC)",
          fact: "Cyrus the Great of Persia issued a decree permitting Jewish exiles to return to Jerusalem and rebuild the Second Temple under Zerubbabel.",
          explanation: "The prophets Haggai and Zechariah encouraged the returning exiles to finish the temple construction.",
          biblicalReference: "Ezra 1:1–4, 6:14–15",
          category: "prophets",
        },
        {
          id: 37,
          title: "Nehemiah Rebuilds Jerusalem's Walls",
          fact: "Nehemiah, cupbearer to the Persian king, traveled to Jerusalem and rallied the people to rebuild the city walls in just 52 days despite intense opposition.",
          explanation: "Ezra the scribe read the Law publicly to the assembled community in a great spiritual revival.",
          biblicalReference: "Nehemiah 6:15, 8:1–8",
          category: "prophets",
        },
        {
          id: 38,
          title: "Queen Esther Saves Her People",
          fact: "Esther, a Jewish orphan who became Queen of Persia, risked her life by approaching King Ahasuerus to foil Haman's plot to annihilate the Jews.",
          explanation: "This deliverance is celebrated annually during the Jewish festival of Purim.",
          biblicalReference: "Esther 4:14, 9:26",
          category: "prophets",
        },
        {
          id: 39,
          title: "The Book of Psalms: Israel's Songbook",
          fact: "The Psalter contains 150 poetic prayers and hymns authored by David, Asaph, the sons of Korah, Solomon, and Moses.",
          explanation: "Psalm 23 ('The LORD is my shepherd') is the most famous psalm in Christian and Jewish tradition.",
          biblicalReference: "Psalm 23:1, 150:6",
          category: "prophets",
        },
        {
          id: 40,
          title: "Proverbs, Job & Ecclesiastes (Wisdom Literature)",
          fact: "Proverbs provides practical moral instruction, Job wrestles with human suffering, and Ecclesiastes reflects on the meaning of life ('All is vanity without God').",
          explanation: "Proverbs 9:10 states: 'The fear of the LORD is the beginning of wisdom.'",
          biblicalReference: "Proverbs 9:10, Job 19:25, Ecclesiastes 12:13",
          category: "prophets",
        },
      ],
    },
    {
      id: "ch3-gospels",
      number: 3,
      title: "The Life & Ministry of Jesus",
      subtitle: "The Four Gospels, Parables, Miracles & Resurrection",
      image: "/images/ebooks/ch1-patriarchs.png",
      description:
        "The incarnation of Christ, John the Baptist, the Sermon on the Mount, passion week, crucifixion, and resurrection.",
      facts: [
        {
          id: 41,
          title: "The Four Gospels (Evangelists)",
          fact: "Matthew (written for Jewish readers), Mark (action-oriented), Luke (orderly historical account), and John (theological divinity) record the life of Jesus.",
          explanation: "Matthew, Mark, and Luke are called Synoptic ('seeing together') because of their shared outline.",
          biblicalReference: "Luke 1:1–4, John 20:30–31",
          category: "gospels",
        },
        {
          id: 42,
          title: "Incarnation & Birth in Bethlehem",
          fact: "Jesus was born of the Virgin Mary in Bethlehem of Judea in fulfillment of Micah 5:2, laid in a manger because there was no room in the inn.",
          explanation: "Angels announced His birth to shepherds, and Wise Men (Magi) brought gifts of gold, frankincense, and myrrh.",
          biblicalReference: "Matthew 2:1–11, Luke 2:1–20",
          category: "gospels",
        },
        {
          id: 43,
          title: "John the Baptist's Ministry",
          fact: "John the Baptist preached repentance in the Judean wilderness, dressed in camel's hair, and baptized Jesus in the Jordan River.",
          explanation: "John identified Jesus as 'the Lamb of God who takes away the sin of the world'.",
          biblicalReference: "Matthew 3:1–17, John 1:29",
          category: "gospels",
        },
        {
          id: 44,
          title: "Temptation in the Wilderness",
          fact: "Jesus fasted forty days in the desert and resisted three temptations from Satan by quoting Scripture from Deuteronomy.",
          explanation: "Jesus demonstrated perfect obedience where Adam and Israel had failed.",
          biblicalReference: "Matthew 4:1–11",
          category: "gospels",
        },
        {
          id: 45,
          title: "Calling the Twelve Apostles",
          fact: "Jesus called twelve disciples—including fishermen Peter, Andrew, James, and John, and Matthew the tax collector—to be His core companions.",
          explanation: "He promised to make them 'fishers of men'.",
          biblicalReference: "Mark 3:13–19",
          category: "gospels",
        },
        {
          id: 46,
          title: "The Sermon on the Mount & The Beatitudes",
          fact: "Delivered on a Galilean hillside, the Sermon on the Mount opens with eight Beatitudes ('Blessed are the poor in spirit') and includes the Lord's Prayer.",
          explanation: "Jesus taught that He came not to abolish the Law, but to fulfill it.",
          biblicalReference: "Matthew 5:1–7:29",
          category: "gospels",
        },
        {
          id: 47,
          title: "First Miracle at Cana",
          fact: "At a wedding feast in Cana of Galilee, Jesus turned six stone jars of water into choice wine at His mother Mary's request.",
          explanation: "John records this as the first of seven miraculous signs revealing Jesus' glory.",
          biblicalReference: "John 2:1–11",
          category: "gospels",
        },
        {
          id: 48,
          title: "Nicodemus & Born Again (John 3:16)",
          fact: "Jesus told Nicodemus the Pharisee that one must be 'born again' of water and the Spirit to see the kingdom of God.",
          explanation: "John 3:16 summarizes the Gospel: 'For God so loved the world that He gave His only Son...'",
          biblicalReference: "John 3:1–21",
          category: "gospels",
        },
        {
          id: 49,
          title: "Woman at the Well in Samaria",
          fact: "Jesus broke social barriers by speaking with a Samaritan woman at Jacob's well, offering her 'living water' that springs up to eternal life.",
          explanation: "She declared Him to her village as the Messiah.",
          biblicalReference: "John 4:7–29",
          category: "gospels",
        },
        {
          id: 50,
          title: "Feeding the 5,000",
          fact: "Jesus multiplied five barley loaves and two small fish provided by a young boy to feed five thousand men besides women and children.",
          explanation: "Twelve baskets of leftovers were gathered, and this is the only miracle recorded in all four Gospels.",
          biblicalReference: "Matthew 14:13–21, John 6:1–14",
          category: "gospels",
        },
        {
          id: 51,
          title: "Walking on Water & Calming the Storm",
          fact: "Jesus walked on the stormy Sea of Galilee toward His disciples' boat and commanded the wind and waves: 'Peace! Be still!'",
          explanation: "Peter stepped out on the water in faith before sinking when he looked at the waves.",
          biblicalReference: "Matthew 14:22–33, Mark 4:35–41",
          category: "gospels",
        },
        {
          id: 52,
          title: "Peter's Confession at Caesarea Philippi",
          fact: "When Jesus asked, 'Who do you say I am?', Peter replied: 'You are the Christ, the Son of the living God.'",
          explanation: "Jesus declared He would build His Church upon this foundational truth.",
          biblicalReference: "Matthew 16:13–18",
          category: "gospels",
        },
        {
          id: 53,
          title: "The Transfiguration",
          fact: "Jesus took Peter, James, and John up a high mountain where His face shone like the sun, and Moses and Elijah appeared talking with Him.",
          explanation: "A voice from the cloud affirmed: 'This is my beloved Son; listen to Him!'",
          biblicalReference: "Matthew 17:1–8",
          category: "gospels",
        },
        {
          id: 54,
          title: "The Parable of the Prodigal Son",
          fact: "A rebellious younger son wasted his inheritance, returned home in repentance, and was welcomed with open arms by a merciful father.",
          explanation: "Luke 15 presents three lost-and-found parables: the lost sheep, lost coin, and lost son.",
          biblicalReference: "Luke 15:11–32",
          category: "gospels",
        },
        {
          id: 55,
          title: "Raising Lazarus from the Dead",
          fact: "Four days after Lazarus died in Bethany, Jesus wept at his tomb and commanded: 'Lazarus, come out!', restoring him to life.",
          explanation: "This dramatic miracle accelerated the Sanhedrin's plot to put Jesus to death.",
          biblicalReference: "John 11:1–44",
          category: "gospels",
        },
        {
          id: 56,
          title: "Triumphal Entry (Palm Sunday)",
          fact: "Jesus rode into Jerusalem on a donkey as crowds waved palm branches and shouted 'Hosanna to the Son of David!'",
          explanation: "This fulfilled Zechariah 9:9 prophesying the humble entrance of Zion's King.",
          biblicalReference: "Matthew 21:1–11",
          category: "gospels",
        },
        {
          id: 57,
          title: "The Last Supper & The New Covenant",
          fact: "During Passover in the Upper Room, Jesus washed the disciples' feet and instituted the Lord's Supper using bread and wine as symbols of His body and blood.",
          explanation: "He gave them a new commandment: 'Love one another as I have loved you.'",
          biblicalReference: "Luke 22:14–20, John 13:34",
          category: "gospels",
        },
        {
          id: 58,
          title: "Agony in Gethsemane & Arrest",
          fact: "Jesus prayed in anguish on the Mount of Olives ('Not my will, but yours be done') before Judas Iscariot betrayed Him with a kiss.",
          explanation: "Jesus was arrested and subjected to illegal trials before the Sanhedrin and Pontius Pilate.",
          biblicalReference: "Matthew 26:36–56",
          category: "gospels",
        },
        {
          id: 59,
          title: "Crucifixion at Golgotha (Good Friday)",
          fact: "Jesus was crucified at Golgotha ('Place of the Skull') between two thieves, bearing the sins of humanity and declaring: 'It is finished.'",
          explanation: "At His death, the temple curtain was torn in two from top to bottom.",
          biblicalReference: "Matthew 27:32–54, John 19:30",
          category: "gospels",
        },
        {
          id: 60,
          title: "The Empty Tomb & Resurrection (Easter)",
          fact: "On the third day, Mary Magdalene and the women found the tomb empty; angels announced: 'He is not here; He has risen!'",
          explanation: "Jesus appeared to Mary, the Emmaus disciples, the Eleven apostles, and over 500 witnesses.",
          biblicalReference: "Matthew 28:1–10, 1 Corinthians 15:3–8",
          category: "gospels",
        },
      ],
    },
    {
      id: "ch4-early-church",
      number: 4,
      title: "The Acts of the Apostles & Early Church",
      subtitle: "Pentecost, Gentile Mission, Paul's Journeys & Revelation",
      image: "/images/ebooks/ch1-patriarchs.png",
      description:
        "The outpouring of the Holy Spirit, the expansion of the early movement, Paul's missionary travels, epistles, and final victory.",
      facts: [
        {
          id: 61,
          title: "The Great Commission & Ascension",
          fact: "Before ascending into heaven from the Mount of Olives, Jesus commanded: 'Go and make disciples of all nations, baptizing them.'",
          explanation: "He promised His followers power when the Holy Spirit comes upon them.",
          biblicalReference: "Matthew 28:18–20, Acts 1:8–9",
          category: "church",
        },
        {
          id: 62,
          title: "Day of Pentecost & Birth of the Church",
          fact: "The Holy Spirit descended like tongues of fire on 120 believers in Jerusalem; Peter preached, and 3,000 people were baptized.",
          explanation: "Believers gathered daily for the apostles' teaching, fellowship, breaking of bread, and prayer.",
          biblicalReference: "Acts 2:1–47",
          category: "church",
        },
        {
          id: 63,
          title: "Stephen: First Christian Martyr",
          fact: "Stephen, one of the seven appointed deacons, delivered a defense before the Sanhedrin and was stoned to death while praying for his executioners.",
          explanation: "A young Pharisee named Saul of Tarsus stood by holding the coats of those who stoned Stephen.",
          biblicalReference: "Acts 6:8–7:60",
          category: "church",
        },
        {
          id: 64,
          title: "Conversion of Saul on the Damascus Road",
          fact: "Saul was blinded by a radiant light on his way to arrest Christians in Damascus; Jesus asked him: 'Saul, Saul, why do you persecute me?'",
          explanation: "Saul was healed by Ananias, baptized, and became the Apostle Paul.",
          biblicalReference: "Acts 9:1–19",
          category: "church",
        },
        {
          id: 65,
          title: "Peter & Cornelius (Gentile Salvation)",
          fact: "Peter received a vision of a sheet filled with animals, learning that God treats no person as unclean; he baptized Cornelius' household in Caesarea.",
          explanation: "This marked the official opening of the Gospel to non-Jewish Gentiles without requiring circumcised conversion first.",
          biblicalReference: "Acts 10:1–48",
          category: "church",
        },
        {
          id: 66,
          title: "First Called 'Christians' at Antioch",
          fact: "The multi-ethnic church in Syrian Antioch became the springboard for foreign missions, where believers were first nicknamed 'Christians'.",
          explanation: "Barnabas and Paul taught the church in Antioch for a full year.",
          biblicalReference: "Acts 11:25–26",
          category: "church",
        },
        {
          id: 67,
          title: "Paul's First Missionary Journey",
          fact: "Commissioned by Antioch, Paul and Barnabas traveled across Cyprus and Galatia (Iconium, Lystra, Derbe), planting churches.",
          explanation: "They established elders in every church before returning to report to Antioch.",
          biblicalReference: "Acts 13:1–14:28",
          category: "church",
        },
        {
          id: 68,
          title: "The Council of Jerusalem (Acts 15)",
          fact: "Apostles and elders met in Jerusalem to resolve whether Gentile converts needed to follow the Law of Moses; Peter and James confirmed salvation is by grace through faith.",
          explanation: "This decision preserved Gospel unity and freed Gentile believers from ceremonial obligations.",
          biblicalReference: "Acts 15:1–29",
          category: "church",
        },
        {
          id: 69,
          title: "Paul's Second Journey & The Macedonian Call",
          fact: "Paul saw a vision of a man from Macedonia pleading 'Come over to Macedonia and help us', carrying the Gospel into Europe for the first time.",
          explanation: "Lydia the purple merchant became the first European convert in Philippi.",
          biblicalReference: "Acts 16:9–15",
          category: "church",
        },
        {
          id: 70,
          title: "Philippian Jailer Converted",
          fact: "An earthquake opened prison doors while Paul and Silas sang hymns at midnight; the jailer asked 'What must I do to be saved?' and believed.",
          explanation: "Paul answered: 'Believe in the Lord Jesus, and you will be saved—you and your household.'",
          biblicalReference: "Acts 16:25–34",
          category: "church",
        },
        {
          id: 71,
          title: "Paul at the Areopagus in Athens",
          fact: "Paul preached to Greek philosophers at Mars Hill (Areopagus), using their altar 'To an Unknown God' to explain the Creator and Resurrection.",
          explanation: "Paul demonstrated contextual evangelism in the intellectual heart of the Greco-Roman world.",
          biblicalReference: "Acts 17:16–34",
          category: "church",
        },
        {
          id: 72,
          title: "Priscilla, Aquila & Apollos in Corinth & Ephesus",
          fact: "Tentmakers Priscilla and Aquila partnered with Paul in Corinth and later instructed Apollos more accurately in the Way at Ephesus.",
          explanation: "Their partnership highlights lay leadership and team ministry in the early church.",
          biblicalReference: "Acts 18:1–28",
          category: "church",
        },
        {
          id: 73,
          title: "Ephesus Riot & The Gospel Impact on Trade",
          fact: "Paul ministered in Ephesus for three years; so many turned from idols that silversmith Demetrius incited a stadium riot over lost shrine sales.",
          explanation: "The Gospel transformed personal ethics and local economies.",
          biblicalReference: "Acts 19:23–41",
          category: "church",
        },
        {
          id: 74,
          title: "Paul's Farewell to the Ephesian Elders",
          fact: "At Miletus, Paul wept with Ephesian elders, reminding them: 'It is more blessed to give than to receive.'",
          explanation: "He charged them to shepherd the flock of God bought with His own blood.",
          biblicalReference: "Acts 20:17–38",
          category: "church",
        },
        {
          id: 75,
          title: "Arrest in Jerusalem & Shipwreck at Malta",
          fact: "Paul was falsely accused in Jerusalem, appealed his case to Caesar, survived a violent 14-day shipwreck at Malta, and reached Rome.",
          explanation: "Acts ends with Paul under house arrest in Rome, unhinderedly preaching the Kingdom of God.",
          biblicalReference: "Acts 21:27–28:31",
          category: "church",
        },
        {
          id: 76,
          title: "The Epistle to the Romans",
          fact: "Paul wrote Romans from Corinth, presenting a systematic exposition of righteousness, justification by faith, and living sacrifices.",
          explanation: "Romans 1:16 declares: 'The Gospel is the power of God for salvation to everyone who believes.'",
          biblicalReference: "Romans 1:16–17, 12:1–2",
          category: "church",
        },
        {
          id: 77,
          title: "The Armor of God (Ephesians 6)",
          fact: "Written from prison, Ephesians calls believers to put on the belt of truth, breastplate of righteousness, shield of faith, and sword of the Spirit.",
          explanation: "Believers stand firm against spiritual forces through divine weaponry.",
          biblicalReference: "Ephesians 6:10–18",
          category: "church",
        },
        {
          id: 78,
          title: "The Hymn of Christ (Philippians 2)",
          fact: "Philippians records that Christ, though equal with God, humbled Himself to the point of death on a cross, wherefore God exalted Him above every name.",
          explanation: "This classic passage (Carmen Christi) is one of the earliest Christian hymns.",
          biblicalReference: "Philippians 2:5–11",
          category: "church",
        },
        {
          id: 79,
          title: "The General Epistles (Hebrews to Jude)",
          fact: "Hebrews presents Jesus as superior to angels, Moses, and Levitical priests, while James, Peter, John, and Jude exhort holy living and endurance.",
          explanation: "Hebrews 11 lists the 'Hall of Faith' heroes who trusted God's promises.",
          biblicalReference: "Hebrews 11:1–40, James 2:17, 1 John 4:7–12",
          category: "church",
        },
        {
          id: 80,
          title: "Revelation & The New Jerusalem",
          fact: "Exiled on Patmos, John received visions of Christ's ultimate victory, culminating in a new heaven, a new earth, and the holy city New Jerusalem.",
          explanation: "Revelation closes Scripture with the promise: 'He will wipe away every tear... Behold, I am making all things new.'",
          biblicalReference: "Revelation 21:1–5, 22:20",
          category: "church",
        },
      ],
    },
    {
      id: "ch5-geography-facts",
      number: 5,
      title: "Geography, Context & Essential Facts",
      subtitle: "The Physical World of Scripture & How We Got the Text",
      image: "/images/ebooks/ch1-patriarchs.png",
      description:
        "Key biblical places, rivers, mountains, language origins, and foundational facts every Bible reader should know.",
      facts: [
        {
          id: 81,
          title: "Languages of the Original Text",
          fact: "The Old Testament was written primarily in Biblical Hebrew (with portions in Aramaic), while the New Testament was written in Koine ('Common') Greek.",
          explanation: "Koine Greek was the universal language of commerce across the Roman Empire following Alexander the Great's conquests.",
          biblicalReference: "Luke 23:38, John 19:20",
          category: "geography",
        },
        {
          id: 82,
          title: "The Fertile Crescent",
          fact: "The arc of arable land stretching from Mesopotamia through Syria to Canaan and Egypt formed the geographic stage for Old Testament history.",
          explanation: "Trade routes and empire conflicts continuously passed through Israel due to its land bridge location.",
          biblicalReference: "Genesis 15:18",
          category: "geography",
        },
        {
          id: 83,
          title: "The Jordan River & Dead Sea",
          fact: "The Jordan River flows south from Mount Hermon through the Sea of Galilee to the Dead Sea, the lowest point on earth (1,400 feet below sea level).",
          explanation: "The Dead Sea's extreme salinity (34%) prevents fish from surviving in its waters.",
          biblicalReference: "Joshua 3:15–17, Ezekiel 47:8",
          category: "geography",
        },
        {
          id: 84,
          title: "Mount Sinai / Horeb",
          fact: "Located in the Sinai Peninsula, Mount Sinai is the peak where God gave Moses the Law, the Ten Commandments, and the Tabernacle plans.",
          explanation: "Elijah later fled to the same mountain when discouraged, hearing God's voice in a gentle whisper.",
          biblicalReference: "Exodus 19:11, 1 Kings 19:11–12",
          category: "geography",
        },
        {
          id: 85,
          title: "Mount Carmel & Mount Hermon",
          fact: "Mount Carmel overlooks the Mediterranean Sea and Jezreel Valley; Mount Hermon in the far north is Israel's highest peak, snow-capped for much of the year.",
          explanation: "Carmel hosted Elijah's contest; Hermon's dew is praised in Psalm 133.",
          biblicalReference: "1 Kings 18:19, Psalm 133:3",
          category: "geography",
        },
        {
          id: 86,
          title: "The Sea of Galilee (Kinneret)",
          fact: "A fresh-water lake 13 miles long by 7 miles wide, surrounded by hills prone to sudden violent windstorms.",
          explanation: "Jesus based His public ministry in Galilean towns like Capernaum, Bethsaida, and Magdala.",
          biblicalReference: "Matthew 4:13–18",
          category: "geography",
        },
        {
          id: 87,
          title: "Jerusalem & Mount Zion",
          fact: "Situated in the Judean mountains at 2,500 feet elevation, Jerusalem has been destroyed and rebuilt over 20 times in documented history.",
          explanation: "Scripture commands believers to 'Pray for the peace of Jerusalem' (Psalm 122:6).",
          biblicalReference: "Psalm 48:1–3, 122:6",
          category: "geography",
        },
        {
          id: 88,
          title: "The Mount of Olives & Kidron Valley",
          fact: "A ridge east of Jerusalem separated from the Temple Mount by the deep Kidron Valley, site of Gethsemane and Jesus' Ascension.",
          explanation: "Zechariah 14 prophesies the Messiah's return to the Mount of Olives.",
          biblicalReference: "Zechariah 14:4, Luke 22:39",
          category: "geography",
        },
        {
          id: 89,
          title: "Nazareth in Galilee",
          fact: "A small, obscure village in lower Galilee where Jesus grew up into adulthood as a carpenter ('Can anything good come out of Nazareth?').",
          explanation: "Today Nazareth is the largest Arab city in northern Israel.",
          biblicalReference: "Matthew 2:23, John 1:46",
          category: "geography",
        },
        {
          id: 90,
          title: "Capernaum: Town of Jesus",
          fact: "Located on the northern shore of the Sea of Galilee, Capernaum served as Jesus' headquarters where He healed Peter's mother-in-law and the paralytic.",
          explanation: "Excavations have unearthed a 1st-century synagogue and a house tradition associates with Simon Peter.",
          biblicalReference: "Mark 1:21–31, 2:1–12",
          category: "geography",
        },
        {
          id: 91,
          title: "Dead Sea Scrolls Discovery (1947)",
          fact: "Discovered in caves near Qumran by Bedouin shepherds, these 2,000-year-old manuscripts contained biblical fragments 1,000 years older than previously known copies.",
          explanation: "The Isaiah Scroll proved the astounding textual accuracy of the Old Testament over centuries of copying.",
          biblicalReference: "Isaiah 40:8",
          category: "geography",
        },
        {
          id: 92,
          title: "Structure of the Christian Bible (66 Books)",
          fact: "The Protestant Bible comprises 66 books: 39 in the Old Testament and 27 in the New Testament, written over 1,500 years by 40 authors.",
          explanation: "Despite varied human authors (kings, scholars, fishermen, shepherds), Scripture presents a unified redemption narrative.",
          biblicalReference: "2 Timothy 3:16",
          category: "geography",
        },
        {
          id: 93,
          title: "The Pentateuch / Torah",
          fact: "The first five books (Genesis, Exodus, Leviticus, Numbers, Deuteronomy) are called the Torah in Hebrew or the Pentateuch ('five scrolls') in Greek.",
          explanation: "Traditionally attributed to Moses, they contain law, history, and creation.",
          biblicalReference: "Luke 24:44",
          category: "geography",
        },
        {
          id: 94,
          title: "Major vs. Minor Prophets",
          fact: "The designation 'Major' (Isaiah, Jeremiah, Ezekiel, Daniel) vs. 'Minor' (Hosea to Malachi) refers to scroll length, not theological importance.",
          explanation: "Isaiah has 66 chapters; Obadiah has only 21 verses.",
          biblicalReference: "Luke 24:27",
          category: "geography",
        },
        {
          id: 95,
          title: "The Septuagint (LXX)",
          fact: "The translation of the Hebrew Old Testament into Greek produced in Alexandria, Egypt around 250 BC by ~70 scholars.",
          explanation: "The Septuagint was the Bible quoted by New Testament writers and apostles across the Roman world.",
          biblicalReference: "Acts 7:14",
          category: "geography",
        },
        {
          id: 96,
          title: "The Intertestamental Period ('400 Silent Years')",
          fact: "The ~400 years between Malachi and Matthew when no canonical prophets spoke in Israel, spanning Persian, Greek (Ptolemaic/Seleucid), and Roman rule.",
          explanation: "During this era, the Maccabean Revolt gave rise to the Hanukkah celebration.",
          biblicalReference: "Galatians 4:4",
          category: "geography",
        },
        {
          id: 97,
          title: "Herod the Great & Temple Expansion",
          fact: "Herod the Great, appointed King of Judea by Rome, expanded the Second Temple into a massive architectural wonder of white marble and gold plates.",
          explanation: "This magnificent structure was the Temple visited by Jesus during His earthly ministry.",
          biblicalReference: "Mark 13:1, John 2:20",
          category: "geography",
        },
        {
          id: 98,
          title: "The Destruction of the Second Temple (70 AD)",
          fact: "Roman legions under General Titus burned Jerusalem and dismantled the Second Temple, fulfilling Jesus' prophecy in Matthew 24:2 ('Not one stone left upon another').",
          explanation: "This event ended animal sacrifices and reshaped Judaism into synagogue-based rabbinic practice.",
          biblicalReference: "Matthew 24:1–2",
          category: "geography",
        },
        {
          id: 99,
          title: "The Canon of Scripture",
          fact: "The list of books recognized as inspired, authoritative Holy Scripture, affirmed through early church councils based on apostolic origin and widespread church adoption.",
          explanation: "The word 'canon' comes from a Greek measuring reed, denoting a standard of truth.",
          biblicalReference: "2 Peter 3:15–16",
          category: "geography",
        },
        {
          id: 100,
          title: "The Central Promise: Grace Through Faith",
          fact: "The entire biblical storyline culminates in God's gift of salvation through faith in Jesus Christ, not by works of human self-righteousness.",
          explanation: "Ephesians 2:8–9 summarizes: 'For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, not a result of works, so that no one may boast.'",
          biblicalReference: "Ephesians 2:8–9, John 20:31",
          category: "geography",
        },
      ],
    },
  ],
};
